const ABILITIES={
 knight:[['Sword slash','⚔','melee',.55,3,1,3],['Throwing axe','➶','shot',.8,27,1,2],['Shield bash','▣','cone',5,4,1.2,18],['Whirlwind','✺','nova',8,4.5,1.5,8],['Rally','✚','heal',18,0,35,0],['Bull rush','»','dash',7,7,1,15]],
 ranger:[['Aimed shot','➶','shot',.48,32,1,2],['Twin blades','⚔','melee',.7,3,1.2,2],['Gust arrow','↝','pushShot',4,30,1.1,20],['Arrow volley','☄','area',7,26,1.8,5],['Field dressing','✚','heal',18,0,28,0],['Evasive roll','»','dash',5,6,.7,6]],
 pyromancer:[['Firebolt','✹','fireShot',.7,28,1,3],['Flame fan','♨','cone',1.5,5,1.3,5],['Blast wave','✺','nova',6,5,1.4,22],['Meteor','☄','area',9,28,2.8,13],['Kindle','✚','heal',18,0,30,0],['Cinder step','»','dash',7,6,1.1,9]]};
BUILDS.push({id:'gale',name:'Gale pylon',cost:90,blocks:true,range:9,dmg:8,cd:2,color:0x8ce5ec});
const oldTowerMesh=towerMesh;
towerMesh=function(b){if(b.id!=='gale')return oldTowerMesh(b);const g=new THREE.Group(),base=new THREE.Mesh(new THREE.CylinderGeometry(.65,.8,.8,8),new THREE.MeshStandardMaterial({color:0x465869})),orb=new THREE.Mesh(new THREE.OctahedronGeometry(.65),new THREE.MeshStandardMaterial({color:0x99e9ec,emissive:0x227799,emissiveIntensity:.8}));base.position.y=.4;orb.position.y=1.5;g.add(base,orb);g.userData.top=orb;g.traverse(o=>{o.castShadow=true;});return g;};
let selectedEnemy=null,combatUIReady=false;
const names={grunt:'Ashborn Grunt',runner:'Briar Runner',brute:'Stonehide Brute',shaman:'Hollow Shaman',boss:'The Siege Lord'};
function combatMode(){return G?.combatMode||'free';}
function livingTarget(){return selectedEnemy&&!selectedEnemy.dead&&G.enemies.includes(selectedEnemy)?selectedEnemy:null;}
function nearestEnemy(range=34){return G.enemies.filter(e=>!e.dead&&e.pos.distanceTo(G.player.pos)<=range).sort((a,b)=>a.pos.distanceToSquared(G.player.pos)-b.pos.distanceToSquared(G.player.pos))[0]||null;}
function shotOrigin(){return G.player.pos.clone().add(V3(0,1.25,0));}
function sceneAim(pointer=false){if(!G||!raycaster)return{point:V3(),enemy:null};updateCamera();camera.updateMatrixWorld(true);G.world.updateMatrixWorld(true);raycaster.setFromCamera(pointer||G.view==='top'?mouse:{x:0,y:0},camera);let point=raycaster.ray.at(40,V3()),enemy=null,distance=40;const exclusions=new Set([G.playerMesh,G.cursor,G.rangeRing,G.wallOutline,G.targetRing,G.aoePreview,G.capturePreview,G.coreGhost,...G.enemies.map(e=>e.mesh),...G.bolts.map(b=>b.mesh),...(G.effects||[]).map(e=>e.mesh),...(G.moveAnimations||[]).map(e=>e.mesh),...(G.skills||[]).map(e=>e.mesh)]);const objects=G.world.children.filter(o=>!exclusions.has(o)&&o.type!=='Line'&&o.type!=='LineLoop');for(const hit of raycaster.intersectObjects(objects,true)){if(!hit.object.isMesh)continue;if(hit.distance<distance){point=hit.point;distance=hit.distance;}break;}for(const e of G.enemies){if(e.dead)continue;const hit=raycaster.ray.intersectSphere(new THREE.Sphere(e.pos.clone().add(V3(0,e.d.size,0)),e.d.size+.12),V3());if(hit&&hit.distanceTo(raycaster.ray.origin)<distance){distance=hit.distanceTo(raycaster.ray.origin);point=hit;enemy=e;}}return{point,enemy};}
function abilityAim(){const target=combatMode()==='auto'?nearestEnemy():combatMode()==='target'?livingTarget():null;return target?{point:target.pos.clone().add(V3(0,target.d.size,0)),enemy:target}:sceneAim(combatMode()==='target');}
function pushEnemy(e,from,power){if(!e||e.dead)return;const d=e.pos.clone().sub(from);d.y=0;if(d.lengthSq()<.01)d.set(0,0,1);d.normalize();e.impulse=(e.impulse||V3()).add(d.multiplyScalar(power/(e.type==='boss'?3:e.type==='brute'?1.5:1)));e.vy=Math.max(e.vy||0,power*.12);e.next=null;}
function hitEnemy(e,amt,origin,push=0){damage(e,amt);if(push&&!e.dead)pushEnemy(e,origin,push);}
function effectRing(pos,r,color=0xffb65c){const m=new THREE.Mesh(new THREE.RingGeometry(r*.92,r,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y+=.08;G.world.add(m);G.effects=G.effects||[];G.effects.push({mesh:m,ttl:.5});}
function castAbility(index){if(!G||menuPaused||G.buildMode||G.phase==='over'||G.player.dead>0||!$('draft').classList.contains('hidden'))return false;const a=ABILITIES[G.classId][index];if(!a)return false;G.abilityCds=G.abilityCds||[];if((G.abilityCds[index]||0)>0)return false;const [name,glyph,type,cd,range,mult,push]=a,P=G.player,aim=abilityAim(),from=shotOrigin(),delta=aim.point.clone().sub(from),target=livingTarget();if(combatMode()==='target'&&['shot','pushShot','fireShot','melee','cone'].includes(type)&&!target){log('Select an enemy first');return false;}if(combatMode()==='target'&&target&&['shot','pushShot','fireShot','melee','cone'].includes(type)&&target.pos.distanceTo(P.pos)>range+target.d.size){log('Target is out of range');return false;}const haste=['heal','dash'].includes(type)?1:Math.min(P.meleeCd/CLASSES[G.classId].meleeCd,P.rangedCd/CLASSES[G.classId].rangedCd);G.abilityCds[index]=G.admin?.noCooldown?0:cd*haste;const dir=delta.lengthSq()>.001?delta.normalize():facing();P.yaw=Math.atan2(dir.x,dir.z);P.baseYaw=P.yaw;const dmg=(['melee','cone','nova','dash'].includes(type)?P.melee:P.ranged)*mult*(has('glass')?2:1);P.swing=.25;
 if(type==='heal'){P.hp=Math.min(P.maxHp,P.hp+mult);effectRing(P.pos,2,0x79e2a2);}
 else if(type==='dash'){for(let i=0;i<range*5;i++)tryMove(P.pos,dir.x*.2,dir.z*.2);for(const e of G.enemies)if(!e.dead&&e.pos.distanceTo(P.pos)<3)hitEnemy(e,dmg,P.pos,push);effectRing(P.pos,3);}
 else if(['melee','cone','nova','area'].includes(type)){const center=type==='area'?aim.point.clone():P.pos.clone();if(type==='area'){const off=center.clone().sub(P.pos);if(off.length()>range)center.copy(P.pos).add(off.normalize().multiplyScalar(range));center.y=heightAt(center.x,center.z);}let meleeHits=0;const radius=type==='area'?4.5:range;effectRing(center,radius,G.classId==='pyromancer'?0xff722e:0xa0dbe2);for(const e of G.enemies){if(e.dead||e.pos.distanceTo(center)>radius+e.d.size)continue;const d=e.pos.clone().sub(P.pos);if(['melee','cone'].includes(type)&&d.normalize().dot(V3(dir.x,0,dir.z).normalize())<.2)continue;hitEnemy(e,dmg,center,push);meleeHits++;if(G.classId==='pyromancer'){e.burn=4;e.burnT=3;}}if(type==='melee'&&has('bloodlust'))P.hp=Math.min(P.maxHp,P.hp+3*meleeHits);}
 else{const mesh=new THREE.Mesh(new THREE.SphereGeometry(type==='fireShot'?.22:.12,8,6),new THREE.MeshBasicMaterial({color:type==='fireShot'?0xff8a32:0xb8eeff}));mesh.position.copy(from);G.world.add(mesh);G.bolts.push({pos:from,vel:dir.multiplyScalar(30),mesh,dmg,life:range/30,aoe:type==='fireShot',knock:push,source:'player'});}
 G.uiNext=0;updateCombatUI();return true;}
meleeAttack=function(){return castAbility(0);};rangedAttack=function(){return castAbility(1);};
function updateEnemyPhysics(e,dt){const ground=heightAt(e.pos.x,e.pos.z);if(!e.impulse&&e.pos.y<=ground+.08&&!(e.vy>0))return false;e.impulse=e.impulse||V3();const count=Math.max(1,Math.ceil(e.impulse.length()*dt/.15));for(let k=0;k<count;k++){const x=e.pos.x+e.impulse.x*dt/count,z=e.pos.z+e.impulse.z*dt/count,h=heightAt(x,z);if(h<=e.pos.y+.2&&!blockedAt(x,z,e.pos.y,e.d.size,e.d.size*2,e)){e.pos.x=x;e.pos.z=z;}else{e.impulse.x*=-.15;e.impulse.z*=-.15;}}const previousY=e.pos.y;e.vy=(e.vy||0)-24*dt;e.pos.y+=e.vy*dt;const floor=supportHeight(e.pos,previousY);if(e.pos.y<=floor){if(e.vy<-11)damage(e,(-e.vy-11)*3);e.pos.y=floor;e.vy=0;e.impulse.multiplyScalar(Math.exp(-dt*8));}else e.impulse.multiplyScalar(Math.exp(-dt*.8));e.cell=worldToCell(e.pos);e.next=null;e.mesh.position.copy(e.pos);if(e.impulse.length()<.2&&e.pos.y<=floor+.01){e.impulse=null;e.rejoin=null;return false;}return true;}
function projectileObstacle(a,b,ignoreMesh=null){const dir=b.clone().sub(a),len=dir.length();if(!len)return null;const ray=new THREE.Raycaster(a,dir.normalize(),0,len);const skip=new Set([ignoreMesh,G.playerMesh,G.cursor,G.rangeRing,G.wallOutline,G.targetRing,G.aoePreview,G.capturePreview,G.coreGhost,...G.enemies.map(e=>e.mesh),...G.bolts.map(o=>o.mesh),...(G.effects||[]).map(e=>e.mesh),...(G.moveAnimations||[]).map(e=>e.mesh),...(G.skills||[]).map(e=>e.mesh)]);G.world.updateMatrixWorld(true);const hits=ray.intersectObjects(G.world.children.filter(o=>!skip.has(o)),true);return hits.find(h=>h.object.isMesh)?.point||null;}
updateBolts=function(dt){for(let i=G.bolts.length-1;i>=0;i--){const b=G.bolts[i];b.life-=dt;const from=b.pos.clone(),end=from.clone().addScaledVector(b.vel,dt),wall=projectileObstacle(from,end),ray=new THREE.Ray(from,b.vel.clone().normalize()),len=from.distanceTo(end);let hit=null,hitDist=wall?from.distanceTo(wall):len+.001;for(const e of G.enemies){if(e.dead||b.hitSet?.has(e))continue;const p=ray.intersectSphere(new THREE.Sphere(e.pos.clone().add(V3(0,e.d.size,0)),e.d.size+.15),V3());const d=p?.distanceTo(from);if(p&&d<=len&&d<hitDist){hit=e;hitDist=d;}}b.pos.copy(from).addScaledVector(ray.direction,Math.min(len,hitDist));b.mesh.position.copy(b.pos);if(hit){if(b.aoe){for(const e of G.enemies)if(!e.dead&&e.pos.distanceTo(hit.pos)<2.5){hitEnemy(e,b.dmg,b.pos,b.knock||4);e.burn=4;e.burnT=2;}effectRing(hit.pos,2.5,0xff793a);}else hitEnemy(hit,b.dmg,from,b.knock||2);if(b.pierce){b.hitSet=b.hitSet||new Set();b.hitSet.add(hit);}else b.life=0;}if(wall&&!hit){if(b.aoe){effectRing(wall,2.5,0xff793a);for(const e of G.enemies)if(!e.dead&&e.pos.distanceTo(wall)<2.5)hitEnemy(e,b.dmg,wall,b.knock||4);}b.life=0;}if(b.life<=0){G.world.remove(b.mesh);b.mesh.geometry.dispose();b.mesh.material.dispose();G.bolts.splice(i,1);}}
 for(let i=G.tracers.length-1;i>=0;i--){const t=G.tracers[i];t.ttl-=dt;t.l.material.opacity=Math.max(0,t.ttl/.12);if(t.ttl<=0){G.world.remove(t.l);t.l.geometry.dispose();t.l.material.dispose();G.tracers.splice(i,1);}}};
const motionUpdate=updatePlayer;
updatePlayer=function(dt){if(G.admin?.god)G.player.hp=G.player.maxHp;const oldFeet=G.player.pos.y;motionUpdate(dt);const support=supportHeight(G.player.pos,oldFeet);if(G.player.pos.y<support&&oldFeet>=support-.05){G.player.pos.y=support;G.player.vy=0;G.playerMesh.position.copy(G.player.pos);}G.abilityCds=(G.abilityCds||[]).map(t=>Math.max(0,t-dt));for(const effect of G.effects||[]){effect.ttl-=dt;effect.mesh.material.opacity=Math.max(0,effect.ttl*1.6);if(effect.ttl<=0){G.world.remove(effect.mesh);effect.mesh.geometry.dispose();effect.mesh.material.dispose();}}G.effects=(G.effects||[]).filter(e=>e.ttl>0);updateCombatUI();};
function setCombatMode(mode){G.uiNext=0;G.combatMode=mode;G.armedArea=null;keys={};if(mode!=='free')document.exitPointerLock?.();updateCombatUI();}
function selectTarget(){G.uiNext=0;selectedEnemy=sceneAim(true).enemy;updateCombatUI();}
function cycleTarget(){const enemies=G.enemies.filter(e=>!e.dead&&e.pos.distanceTo(G.player.pos)<45).sort((a,b)=>a.pos.distanceToSquared(G.player.pos)-b.pos.distanceToSquared(G.player.pos));selectedEnemy=enemies[(enemies.indexOf(selectedEnemy)+1)%enemies.length]||null;updateCombatUI();}
function portrait(kind){const color=kind==='knight'?'#acbacc':kind==='ranger'?'#81b67a':kind==='pyromancer'?'#f5a159':'#'+(ENEMIES[kind]?.color||0xb27766).toString(16).padStart(6,'0');return '<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="30" fill="#111821"/><path d="M8 60 Q9 40 32 40 Q55 40 56 60" fill="'+color+'"/><path d="M16 28 L20 11 L44 11 L49 28 L44 43 L20 43Z" fill="'+color+'"/><path d="M21 27H43V33H21Z" fill="#20242b"/><path d="M24 28h5m6 0h5" stroke="#fff3bc" stroke-width="2"/><path d="M29 38h7" stroke="#252b30" stroke-width="3"/></svg>';}
function updateCombatUI(){if(!combatUIReady||!G)return;if(G.uiNext>G.time)return;G.uiNext=G.time+.07;const building=!!G.buildMode;document.body.classList.toggle('building-mode',building);document.body.classList.toggle('in-run',true);const enemy=livingTarget()||(!building&&combatMode()==='free'?sceneAim().enemy:null);$('playerPortrait').innerHTML=portrait(G.classId);$('playerUnitName').textContent=CLASSES[G.classId].name;$('playerUnitHP').textContent=Math.ceil(G.player.hp)+' / '+G.player.maxHp;$('playerUnitFill').style.width=100*G.player.hp/G.player.maxHp+'%';$('targetFrame').style.display=enemy?'flex':'none';if(enemy){$('targetPortrait').innerHTML=portrait(enemy.type);$('targetName').textContent=names[enemy.type];$('targetHP').textContent=Math.ceil(Math.max(0,enemy.hp))+' / '+Math.ceil(enemy.maxHp);$('targetFill').style.width=Math.max(0,100*enemy.hp/enemy.maxHp)+'%';}for(const [i,a]of ABILITIES[G.classId].entries()){const el=$('ability'+i);el.querySelector('.ability-icon').textContent=a[1];el.querySelector('.ability-name').textContent=a[0];const cd=G.abilityCds?.[i]||0;el.querySelector('.ability-cd').textContent=cd>.05?cd.toFixed(1)+'s':'';el.disabled=cd>.05||building;el.title=a[0]+' · '+a[3]+'s cooldown · '+a[4]+'m range';}for(const mode of ['free','target','auto'])$('mode-'+mode).classList.toggle('active',combatMode()===mode);$('combatHint').textContent=combatMode()==='free'?'Free aim · LMB 1 / RMB 2 · 1–6 abilities · T cycle target':combatMode()==='target'?'Click an enemy · 1–6 abilities · T cycle target':'Auto attack nearest enemy · 1–6 abilities · movement remains manual';const cross=$('cross');cross.classList.toggle('hidden',building);cross.style.left=G.view==='top'||combatMode()==='target'?((mouse.x+1)*50)+'%':'50%';cross.style.top=G.view==='top'||combatMode()==='target'?((1-mouse.y)*50)+'%':'50%';cross.style.borderColor=(!building&&enemy)?'#ef9779':'#f1e6c3';if(enemy){if(!G.targetRing){G.targetRing=new THREE.Mesh(new THREE.RingGeometry(.8,1,32),new THREE.MeshBasicMaterial({color:0xecc579,side:THREE.DoubleSide}));G.targetRing.rotation.x=-Math.PI/2;G.world.add(G.targetRing);}G.targetRing.visible=true;G.targetRing.position.copy(enemy.pos).add(V3(0,.05,0));G.targetRing.scale.setScalar(enemy.d.size+1);}else if(G.targetRing)G.targetRing.visible=false;}
function installCombat(){const unit=document.createElement('div');unit.id='unitFrames';unit.innerHTML='<div class="unit-frame"><div class="portrait" id="playerPortrait"></div><div class="unit-info"><b id="playerUnitName"></b><div class="unit-health"><i id="playerUnitFill"></i><span id="playerUnitHP"></span></div><small>PLAYER</small></div></div><div class="unit-frame" id="targetFrame"><div class="portrait" id="targetPortrait"></div><div class="unit-info"><b id="targetName"></b><div class="unit-health hostile"><i id="targetFill"></i><span id="targetHP"></span></div><small>TARGET · T TO CYCLE</small></div></div>';document.body.appendChild(unit);const bar=document.createElement('div');bar.id='combatBar';bar.innerHTML='<div id="combatModes"><button id="mode-free">Free aim</button><button id="mode-target">Select target</button><button id="mode-auto">Auto attack</button></div><div id="abilities">'+Array.from({length:6},(_,i)=>'<button class="ability" id="ability'+i+'"><kbd>'+(i+1)+'</kbd><span class="ability-icon"></span><span class="ability-name"></span><span class="ability-cd"></span></button>').join('')+'</div><div id="combatHint"></div>';document.body.appendChild(bar);for(let i=0;i<6;i++)$('ability'+i).onclick=()=>activateAbility(i);for(const mode of ['free','target','auto'])$('mode-'+mode).onclick=()=>setCombatMode(mode);const admin=document.createElement('button');admin.id='adminToggle';admin.textContent='Testing / cheats (F2)';admin.onclick=toggleAdmin;document.body.appendChild(admin);combatUIReady=true;installAdmin();}
function toggleAdmin(){if(!G)return;const open=$('adminPanel').classList.contains('hidden');$('adminPanel').classList.toggle('hidden',!open);menuPaused=open;keys={};if(open){document.exitPointerLock?.();$('adminGold').value=G.gold;$('adminHealth').value=G.player.maxHp;$('adminGod').checked=!!G.admin?.god;$('adminCooldown').checked=!!G.admin?.noCooldown;}}
function installAdmin(){const panel=document.createElement('div');panel.id='adminPanel';panel.className='hidden';panel.innerHTML='<section><h2>Testing & cheats</h2><p>Simulation paused. Changes apply to this run and its saves.</p><label>Gold <input id="adminGold" type="number" min="0" max="1000000"></label><label>Maximum health <input id="adminHealth" type="number" min="1" max="100000"></label><label><input id="adminGod" type="checkbox"> Invulnerable</label><label><input id="adminCooldown" type="checkbox"> No ability cooldowns</label><button id="adminApply">Apply values & heal</button><label>Upgrade <select id="adminUpgrade">'+UPGRADES.map(u=>'<option value="'+u.id+'">'+u.name+'</option>').join('')+'</select></label><button id="adminUpgradeAdd">Grant upgrade</button><label>Relic <select id="adminRelic">'+RELICS.map(r=>'<option value="'+r.id+'">'+r.name+'</option>').join('')+'</select></label><button id="adminRelicAdd">Grant relic</button><label>Enemy <select id="adminEnemy">'+Object.keys(ENEMIES).map(id=>'<option value="'+id+'">'+names[id]+'</option>').join('')+'</select></label><button id="adminSpawn">Spawn enemy nearby</button><button id="adminClear">Clear enemies</button><button id="adminCore">Repair core</button><button id="adminReset">Reset ability cooldowns</button><button id="adminClose">Return to game</button><p id="adminStatus" role="status"></p></section>';document.body.appendChild(panel);
 $('adminApply').onclick=()=>{G.gold=clamp(Number($('adminGold').value)||0,0,1e6);G.player.maxHp=clamp(Number($('adminHealth').value)||100,1,1e5);G.player.hp=G.player.maxHp;G.admin={god:$('adminGod').checked,noCooldown:$('adminCooldown').checked};$('adminStatus').textContent='Values applied';updateHud();};$('adminUpgradeAdd').onclick=()=>{UPGRADES.find(u=>u.id===$('adminUpgrade').value)?.apply(G);$('adminStatus').textContent='Upgrade granted';};$('adminRelicAdd').onclick=()=>{const r=RELICS.find(r=>r.id===$('adminRelic').value);if(r&&!G.taken[r.id]){G.taken[r.id]=true;G.relics.push(r);if(r.id==='glass'){G.player.maxHp=Math.max(1,G.player.maxHp-30);G.player.hp=Math.min(G.player.hp,G.player.maxHp);}if(r.id==='ironcore'&&G.site){G.site.coreMax+=15;G.site.coreHp+=15;}renderRelics();$('adminStatus').textContent='Relic granted';}};$('adminSpawn').onclick=()=>{const e=spawnEnemy($('adminEnemy').value,null,1);e.mode='roam';const p=G.player.pos.clone().add(facing().multiplyScalar(8));for(let i=0;i<32&&blockedAt(p.x,p.z,heightAt(p.x,p.z),e.d.size);i++){p.x+=Math.cos(i)*1.3;p.z+=Math.sin(i)*1.3;}p.y=heightAt(p.x,p.z);e.pos.copy(p);e.home=p.clone();e.wanderDir=V3();e.wanderT=1;selectedEnemy=e;e.mesh.position.copy(p);$('adminStatus').textContent='Enemy spawned';};$('adminClear').onclick=()=>{for(const e of G.enemies){e.dead=true;G.world.remove(e.mesh);}G.enemies=[];G.spawnQueue=[];selectedEnemy=null;$('adminStatus').textContent='Enemies cleared';};$('adminCore').onclick=()=>{if(G.site)G.site.coreHp=G.site.coreMax;};$('adminReset').onclick=()=>{G.abilityCds=[];};$('adminClose').onclick=toggleAdmin;}
