/* One action selection model, independent automatic casts and explicit targeting. */
let automaticTarget=null,interactionChoice=null;
const SELF_MOVES=new Set(['heal','guard','focus','roll','blink']);
combatMode=function(){return livingTarget()?'target':'free';};
function abilityOutOfRange(i,target=livingTarget()){const a=ABILITIES[G.classId]?.[i];return !!(a&&target&&!SELF_MOVES.has(a[2])&&G.player.pos.distanceTo(target.pos)>a[4]+target.d.size);}
abilityAim=function(){const target=automaticTarget||livingTarget();return G.groundCast?{point:G.groundCast.clone(),enemy:null}:target?{point:target.pos.clone().add(V3(0,target.d.size,0)),enemy:target}:sceneAim(G.view!=='first');};
const unifiedCast=castAbility;
castAbility=function(i){if(abilityOutOfRange(i,automaticTarget||livingTarget()))return false;return unifiedCast(i);};
activateAbility=function(i){if(!G||G.buildMode||!ABILITIES[G.classId][i])return;if(G.activeAbility===i)castAbility(i);else{G.activeAbility=i;G.armedArea=null;}G.uiNext=0;updateCombatUI();};
function toggleAutomatic(i){if(!G)return;G.autoEnabled??=Array(6).fill(false);G.autoEnabled[i]=!G.autoEnabled[i];G.uiNext=0;updateCombatUI();}
updateAutomaticAbilities=function(){if(!G||G.buildMode)return;for(let i=0;i<6;i++){if(!G.autoEnabled?.[i])continue;const a=ABILITIES[G.classId][i],target=livingTarget()||nearestEnemy(a[4]||8);if(a[2]==='heal'){if(G.player.hp>G.player.maxHp*.7)continue;}else if(!target)continue;if(abilityOutOfRange(i,target))continue;automaticTarget=target;try{castAbility(i);}finally{automaticTarget=null;}}};
function chooseTarget(enemy){if(G.targetLocked&&livingTarget()&&livingTarget()!==enemy)return false;selectedEnemy=enemy;G.uiNext=0;updateCombatUI();return true;}
function clearTarget(){selectedEnemy=null;G.targetLocked=false;G.armedArea=null;G.uiNext=0;updateCombatUI();}
cycleTarget=function(){if(G.targetLocked&&livingTarget())return;const enemies=G.enemies.filter(e=>!e.dead&&e.pos.distanceTo(G.player.pos)<60).sort((a,b)=>a.pos.distanceToSquared(G.player.pos)-b.pos.distanceToSquared(G.player.pos));chooseTarget(enemies[(enemies.indexOf(livingTarget())+1)%enemies.length]||null);};
selectTarget=function(){if(G.view!=='first')chooseTarget(sceneAim(true).enemy);};
clickWorld=function(){if(G.workerOrder){const w=economy().workers.find(w=>w.id===G.workerOrder),p=aimPoint();if(w&&p)commandWorker(w,'move',p);G.workerOrder=null;return;}if(G.buildMode){const p=aimPoint();if(p)place(BUILDS[G.selected],...worldToCell(p),BUILDS[G.selected].wall?undefined:p);return;}if(G.view!=='first'){const hit=sceneAim(true).enemy;if(hit&&hit!==livingTarget()&&!G.targetLocked){chooseTarget(hit);return;}}if(G.activeAbility>=0)castAbility(G.activeAbility);};
function uiOpen(){return !!G.uiCursor||!$('settlementPanel').classList.contains('hidden');}
function captureFirstPerson(){if(!G||G.view!=='first'||G.buildMode||menuPaused||uiOpen()||G.cursorReleased)return;const c=$('c');if(document.pointerLockElement!==c){try{c.requestPointerLock?.()?.catch?.(()=>{});}catch{}}}
const unifiedMotion=updatePlayer;
const thirdMouse={left:false,right:false,dragged:false,travel:0};
updatePlayer=function(dt){const a=keys.KeyA,d=keys.KeyD,w=keys.KeyW;if(G.view==='third'){if(!thirdMouse.right){const turn=((a?1:0)-(d?1:0))*dt*2.4;G.player.yaw+=turn;G.player.baseYaw=G.player.yaw;G.cameraYaw=(G.cameraYaw??G.player.yaw)+turn;keys.KeyA=keys.KeyD=false;}else{G.player.yaw=G.cameraYaw??G.player.yaw;G.player.baseYaw=G.player.yaw;}if(thirdMouse.left&&thirdMouse.right)keys.KeyW=true;}unifiedMotion(dt);keys.KeyA=a;keys.KeyD=d;keys.KeyW=w;};
bindInput=function(){const c=$('c'),ready=()=>G&&!menuPaused&&G.phase!=='over'&&$('draft').classList.contains('hidden');
 addEventListener('keydown',e=>{if(e.target?.closest?.('input,select,textarea')&&!['Escape','KeyE'].includes(e.code))return;if(e.code==='F2'){e.preventDefault();toggleAdmin();return;}if(!ready())return;keys[e.code]=true;if(e.code==='AltLeft'||e.code==='AltRight'){G.cursorReleased=true;document.exitPointerLock?.();return;}if(e.repeat)return;
 if(e.code==='Escape'){e.preventDefault();if(G.buildMode)toggleBuildMode();clearTarget();G.workerOrder=null;closeInteraction();return;}if(e.code==='Space'){e.preventDefault();jumpPlayer();}if(e.code==='Tab'){e.preventDefault();cycleTarget();}if(e.code==='KeyB'){toggleBuildMode();G.uiCursor=false;if(!G.buildMode)captureFirstPerson();}if(e.code==='KeyV'){setView(G.view==='top'?'third':G.view==='third'?'first':'top');if(G.view==='first')captureFirstPerson();else document.exitPointerLock?.();}if(e.code==='KeyE'){e.preventDefault();if(uiOpen())closeInteraction();else openInteraction();}
 const number=/^(?:Digit|Numpad)([0-9])$/.exec(e.code);if(number){const n=Number(number[1]);if(G.buildMode){G.selected=n===0?BUILDS.findIndex(b=>b.core):n-1;updateHud();}else if(n>=1&&n<=6)activateAbility(n-1);}});
 addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='AltLeft'||e.code==='AltRight'){G.cursorReleased=false;captureFirstPerson();}});
 c.addEventListener('pointerdown',e=>{if((e.button===0||e.button===2)&&ready()&&G.view==='third')c.setPointerCapture?.(e.pointerId);});c.addEventListener('lostpointercapture',()=>{thirdMouse.left=thirdMouse.right=false;keys.MouseL=keys.MouseR=false;});
 addEventListener('mousemove',e=>{if(!G)return;mouseOverHud=!!e.target?.closest?.('button,input,select,#combatBar,#unitFrames,#microMenu,#settlementPanel,#adminPanel,#hotbar,#interactionMenu,#constructionPanel');const look=G.view==='first'&&!G.buildMode&&!G.cursorReleased&&!uiOpen()&&!mouseOverHud,thirdLook=G.view==='third'&&(thirdMouse.left||thirdMouse.right)&&!mouseOverHud,topLook=G.view==='top'&&thirdMouse.right&&!mouseOverHud;if(ready()&&(look||thirdLook||topLook)){if(thirdLook){thirdMouse.travel+=Math.hypot(e.movementX,e.movementY);if(thirdMouse.travel>4)thirdMouse.dragged=true;}G.cameraYaw=(G.cameraYaw??G.player.yaw)-e.movementX*.003;if(G.view!=='top')G.cameraPitch=clamp((G.cameraPitch??-.18)-e.movementY*.003,-1.35,1.35);if(G.view==='third'&&thirdMouse.right){G.player.yaw=G.cameraYaw;G.player.baseYaw=G.player.yaw;}}if(document.pointerLockElement!==c){mouse.x=e.clientX/innerWidth*2-1;mouse.y=1-e.clientY/innerHeight*2;}else mouse.x=mouse.y=0;});
 c.addEventListener('mousedown',e=>{if(!ready())return;if(uiOpen())closeInteraction();if(G.view==='third'&&(e.button===0||e.button===2)){if(e.button===0){thirdMouse.left=true;keys.MouseL=true;thirdMouse.dragged=false;thirdMouse.travel=0;}else{thirdMouse.right=true;keys.MouseR=true;G.player.yaw=G.cameraYaw??G.player.yaw;G.player.baseYaw=G.player.yaw;}if(thirdMouse.left&&thirdMouse.right)thirdMouse.dragged=true;e.preventDefault();return;}if(e.button===2){thirdMouse.right=true;keys.MouseR=true;e.preventDefault();return;}if(e.button===0){G.cursorReleased=false;captureFirstPerson();clickWorld();}});
 addEventListener('mouseup',e=>{if(e.button===0){const click=G?.view==='third'&&thirdMouse.left&&!thirdMouse.dragged&&!thirdMouse.right&&ready();thirdMouse.left=false;keys.MouseL=false;if(click)clickWorld();}if(e.button===2){thirdMouse.right=false;keys.MouseR=false;}});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('blur',()=>{keys={};thirdMouse.left=thirdMouse.right=false;});document.addEventListener('pointerlockchange',()=>{keys.MouseL=false;});
 $('helpToggle').onclick=()=>{$('help').classList.toggle('min');};$('rerollBtn').onclick=()=>{if(G.gold>=15){G.gold-=15;openDraft();}};$('skipBtn').onclick=closeDraft;$('againBtn').onclick=()=>bridge.menu();$('sameSeedBtn').onclick=()=>{$('end').classList.add('hidden');newRun(G.classId,G.seed);};};
function closeInteraction(){const menu=document.getElementById('interactionMenu');if(menu)menu.classList.add('hidden');if(G)G.uiCursor=false;$('settlementPanel').classList.add('hidden');captureFirstPerson();}
function showInteraction(title,description,actions){const menu=$('interactionMenu');G.uiCursor=true;keys.MouseR=false;document.exitPointerLock?.();menu.innerHTML='';const heading=document.createElement('h3');heading.textContent=title;menu.appendChild(heading);const info=document.createElement('p');info.textContent=description;menu.appendChild(info);for(const action of actions){const button=document.createElement('button');button.textContent=action.label;button.disabled=!!action.disabled;button.onclick=()=>{action.run();};menu.appendChild(button);}const close=document.createElement('button');close.textContent='Close · E';close.onclick=closeInteraction;menu.appendChild(close);menu.classList.remove('hidden');}
function portraitMenu(){const enemy=livingTarget();if(!enemy)return;showInteraction(names[enemy.type],Math.ceil(enemy.hp)+' / '+Math.ceil(enemy.maxHp)+' health',[{label:G.targetLocked?'Unlock target':'Lock target',run:()=>{G.targetLocked=!G.targetLocked;G.uiNext=0;updateCombatUI();closeInteraction();}},{label:'Clear target',run:()=>{clearTarget();closeInteraction();}}]);}
const unifiedUI=updateCombatUI;
updateCombatUI=function(){unifiedUI();if(!G||!combatUIReady)return;for(let i=0;i<6;i++){const el=$('ability'+i),out=abilityOutOfRange(i);el.classList.toggle('active',G.activeAbility===i);el.classList.toggle('out-of-range',out);el.classList.toggle('auto-enabled',!!G.autoEnabled?.[i]);el.disabled=!!G.buildMode;el.setAttribute?.('aria-disabled',String(out||G.buildMode));el.title=out?'Target is out of range':'';}
 $('combatHint').textContent=G.workerOrder?'LMB: order worker to this spot · Esc: cancel':'1–6 / click: select, repeat to cast · RMB move: automatic · Tab: target · Esc: clear · E: interact'+(G.view==='first'?' · Hold Alt for cursor':'');if(livingTarget())$('targetName').textContent=names[livingTarget().type]+(G.targetLocked?'  🔒':'');$('combatModes').style.display='none';$('cross').style.left=G.view==='first'?'50%':((mouse.x+1)*50)+'%';$('cross').style.top=G.view==='first'?'50%':((1-mouse.y)*50)+'%';};
showMoveTooltip=function(i){if(!G)return;const a=ABILITIES[G.classId][i],el=$('moveTooltip');el.innerHTML='<strong>'+a[0]+'</strong><div class="tooltip-meta">'+(a[4]?a[4]+'m range · ':'')+a[3]+'s cooldown</div><p>'+MOVE_INFO[G.classId][i]+'</p><small>Click / '+(i+1)+': select; repeat: cast. Right-click: '+(G.autoEnabled?.[i]?'disable':'enable')+' automatic use.'+(abilityOutOfRange(i)?' Target out of range.':'')+'</small>';el.classList.remove('hidden');const rect=$('ability'+i).getBoundingClientRect();el.style.left=Math.max(8,Math.min(innerWidth-300,rect.left))+'px';el.style.bottom=(innerHeight-rect.top+12)+'px';};
const unifiedInstall=installIntegration;
installIntegration=function(){unifiedInstall();const menu=document.createElement('div');menu.id='interactionMenu';menu.className='hidden';document.body.appendChild(menu);for(let i=0;i<6;i++)$('ability'+i).oncontextmenu=e=>{e.preventDefault();toggleAutomatic(i);showMoveTooltip(i);};$('targetFrame').oncontextmenu=e=>{e.preventDefault();portraitMenu();};$('targetFrame').querySelector('small').textContent='TARGET · TAB TO CYCLE · RMB TO LOCK';const pause=document.createElement('button');pause.textContent='Pause';pause.onclick=()=>{pauseGame(true);bridge.menu();};$('microMenu').appendChild(pause);};
const unifiedNew=newRun;
newRun=function(...args){unifiedNew(...args);G.activeAbility=-1;G.autoEnabled=Array(6).fill(false);G.targetLocked=false;G.uiCursor=false;};

function commandWorker(w,command,point){w.command=command;w.commandGoal=point?.clone()||null;w.path=[];w.commandRetry=0;w.state=command==='work'?(w.cargo?'returning':'seeking'):command;if(command==='work')w.command=null;}
const employedWorkers=updateWorkers;
updateWorkers=function(dt){const eco=economy(),all=eco.workers;eco.workers=all.filter(w=>!w.command);try{employedWorkers(dt);}finally{eco.workers=all;}for(const w of all){if(!w.command)continue;if(w.command==='stay')continue;const goal=w.command==='follow'?G.player.pos:w.commandGoal;if(!goal)continue;const stop=w.command==='follow'?2:.35;if(w.pos.distanceTo(goal)<stop){w.path=[];if(w.command==='move')commandWorker(w,'stay');continue;}w.commandRetry=(w.commandRetry||0)-dt;if(w.commandRetry<=0){w.path=commandPath(w.pos,goal,.27);w.commandRetry=2;}while(w.path?.length&&w.pos.distanceTo(w.path[0])<.2)w.path.shift();if(w.path?.length){const delta=w.path[0].clone().sub(w.pos);delta.y=0;const q=w.pos.clone().add(delta.normalize().multiplyScalar(Math.min(dt*3.5,w.pos.distanceTo(w.path[0]))));q.y=heightAt(q.x,q.z);if(walkSegment(w.pos,q,.27,'nav'))w.pos.copy(q);else w.commandRetry=0;}w.mesh?.position.copy(w.pos);}}
function sellStructure(t){if(!G.towers.includes(t))return false;G.gold+=Math.round((t.paid??buildCost(t.b))*.6);for(const [k,n]of Object.entries(t.materials||{}))economy()[k]+=Math.floor(n*.6);G.towers.splice(G.towers.indexOf(t),1);G.placedCount[t.b.id]--;G.world.remove(t.mesh);G.cells[t.cx][t.cz].tower=G.towers.find(o=>!o.edge&&o.cx===t.cx&&o.cz===t.cz)||null;invalidateWalls();rebuildCollision();refreshRoutes();updateHud();return true;}
function harvestNode(n){if(n.remaining<=0||G.time<(G.handHarvestAt||0))return;G.handHarvestAt=G.time+1;const amount=Math.min(2,n.remaining);n.remaining-=amount;economy()[n.kind||'fragments']+=amount;if(!n.remaining&&n.mesh){G.world.remove(n.mesh);n.mesh=null;}applyHarvestedNodes();updateHud();}
function interactables(){const result=[],add=(kind,o,title)=>{if(o.pos&&o.pos.distanceTo(G.player.pos)<8)result.push({kind,o,title});};for(const w of economy().workers)add('worker',w,'Worker '+w.id+' · '+w.job);for(const t of G.towers)add('tower',t,t.b.name);for(const site of G.sites)add('portal',{...site,pos:site.corePos,original:site},'Portal gate '+site.id);for(const site of G.sites)if(site.status!=='secured')for(const pos of site.gatePos||[])add('hostileGate',{pos,site},'Enemy portal gate');for(const n of [...economy().nodes,...economy().ruins])if(n.remaining>0)add('resource',n,n.kind||'Enemy portal ruins');for(const b of G.generatedBodies||[]){if(b.depleted||!['tree','rock'].includes(b.source))continue;const pos=V3(b.x,b.y,b.z),id=Math.round(b.x*100)+','+Math.round(b.z*100);if(pos.distanceTo(G.player.pos)>=8||economy().nodes.some(n=>n.id===id))continue;const n={id,pos,kind:b.source==='tree'?'logs':hashStr(id)%3===0?'ore':'stone',remaining:b.source==='tree'?24:32,radius:b.r,siteId:claimAt(pos)?.id||0};economy().nodes.push(n);add('resource',n,n.kind);}for(const ch of G.chests)if(!ch.taken)add('chest',ch,'Treasure chest');for(const sh of G.shrines)if(!sh.used)add('shrine',sh,'Relic shrine');for(const e of G.enemies)if(!e.dead)add('enemy',e,names[e.type]);for(const camp of G.lairs||[])add('camp',camp,'Enemy camp');return result.sort((a,b)=>a.o.pos.distanceToSquared(G.player.pos)-b.o.pos.distanceToSquared(G.player.pos));}
function interactWith(item){const {kind,o,title}=item,actions=[],action=(label,run)=>actions.push({label,run:()=>{if(o.pos.distanceTo(G.player.pos)>8){log('Move closer to interact');closeInteraction();return;}run();}});let info='Distance '+o.pos.distanceTo(G.player.pos).toFixed(1)+'m';
 if(kind==='worker'){info+=' · '+o.state+' · '+o.cargo+' carried';for(const [command,label]of [['follow','Follow me'],['stay','Stay here'],['work','Resume harvesting']])action(label,()=>{commandWorker(o,command);closeInteraction();});action('Move to a spot…',()=>{G.workerOrder=o.id;closeInteraction();});for(const job of ['logs','stone','ore','salvage'])action('Assign: '+job,()=>{if(o.cargo)o.nextJob=job;else o.job=job;commandWorker(o,'work');closeInteraction();});}
 if(kind==='tower'){info+=' · Refund: '+Math.round((o.paid??buildCost(o.b))*.6)+' gold and 60% materials';action('Sell '+title,()=>{sellStructure(o);closeInteraction();});}
 if(kind==='resource'){info+=' · '+o.remaining+' remaining · hand harvest: 2 per second';action('Harvest '+(o.kind||'fragments'),()=>{harvestNode(o);interactWith(item);});}
 if(kind==='chest')action('Open · '+o.gold+' gold',()=>{if(!o.taken){o.taken=true;G.gold+=o.gold;G.world.remove(o.mesh);rebuildCollision();updateHud();}closeInteraction();});
 if(kind==='shrine')action('Choose a relic',()=>{if(!o.used){o.used=true;o.mesh.material.emissiveIntensity=0;closeInteraction();openDraft('shrine');}});
 if(kind==='portal'){info+=' · '+o.status+' · '+o.coreHp+'/'+o.coreMax+' health';action('Manage settlement / summon workers',()=>{closeInteraction();G.uiCursor=true;document.exitPointerLock?.();$('settlementPanel').classList.remove('hidden');updateEconomyUI();});if(o.original===G.site)action('Start next defense wave',()=>{startWave();closeInteraction();});action('Repair gate · 10 stone',()=>{if(o.original.coreHp<o.coreMax&&pay({stone:10}))o.original.coreHp=Math.min(o.coreMax,o.original.coreHp+20);closeInteraction();});}
 if(kind==='enemy'){info+=' · '+Math.ceil(o.hp)+'/'+Math.ceil(o.maxHp)+' health';if(G.view!=='first')action('Select target',()=>{chooseTarget(o);closeInteraction();});if(o===livingTarget())action('Lock target',()=>{G.targetLocked=true;closeInteraction();});}
 if(kind==='hostileGate'){info+=' · Defend your portal through five waves to turn this gate into salvageable ruins';action('Build defenses',()=>{closeInteraction();if(!G.buildMode)toggleBuildMode();});}if(kind==='camp')info+=' · Clear its enemies to explore safely';
 actions.push({label:'Other nearby objects',run:openInteraction});showInteraction(title,info,actions);}
function openInteraction(){const nearby=interactables();showInteraction('Interact · E','Objects within 8m. Choose an object to see its actions.',[...nearby.map(item=>({label:item.title+' · '+item.o.pos.distanceTo(G.player.pos).toFixed(1)+'m',run:()=>interactWith(item)})),{label:'Build here',run:()=>{closeInteraction();if(!G.buildMode)toggleBuildMode();}}]);}
const unifiedPreview=updateAimPreview;
updateAimPreview=function(){const mode=combatMode;combatMode=()=> 'free';try{unifiedPreview();}finally{combatMode=mode;}};
const controlRestore=restoreSave;
restoreSave=function(...args){controlRestore(...args);G.uiCursor=false;G.cursorReleased=false;G.targetLocked=false;G.workerOrder=null;};window.bastion.restoreSave=restoreSave;
const nearbyWorkerRoute=workerRoute;
workerRoute=function(w,to,radius=.6){const local=nearbyWorkerRoute(w,to,radius);if(local.length)return local;for(let i=0;i<12;i++){const p=to.clone().add(V3(Math.cos(i*Math.PI/6)*radius,0,Math.sin(i*Math.PI/6)*radius));p.y=heightAt(p.x,p.z);if(blockedAt(p.x,p.z,p.y,.27,1.6,'nav'))continue;const path=commandPath(w.pos,p,.27);if(path.length&&path.at(-1).distanceTo(p)<.4)return path;}return [];};
const claimedResources=createClaimNodes;
createClaimNodes=function(site){claimedResources(site);for(const n of economy().nodes)if(!n.siteId&&n.pos.distanceTo(site.corePos)<=site.r*CELL)n.siteId=site.id;};

const unifiedView=setView;
setView=function(view){unifiedView(view);if(view==='first')captureFirstPerson();else document.exitPointerLock?.();};
