/* Seeded landmarks live in the save, while their render meshes are reconstructed. */
function biomeAt(x,z){const n=(Math.sin(x/180+hashStr(G.seed)%11)+Math.cos(z/210))/2;return n>.5?'frost':n<-.5?'desert':Math.sin(x/130-z/150)>.55?'wetland':'meadow';}
const biomeTerrain=buildTerrainMesh;
buildTerrainMesh=function(){const result=biomeTerrain(),mesh=result?.isMesh?result:G.terrain,positions=mesh.geometry.attributes.position,colors=mesh.geometry.attributes.color,normals=mesh.geometry.attributes.normal;for(let i=0;i<positions.count;i++){if(normals.getY(i)<.6)continue;const kind=biomeAt(positions.getX(i),positions.getZ(i)),color=new THREE.Color(({frost:0xb7cbc7,desert:0xb4a171,wetland:0x536d59,meadow:0x718357})[kind]);const grain=.9+Math.sin(positions.getX(i)*.12+positions.getZ(i)*.16)*.07;colors.setXYZ(i,color.r*grain,color.g*grain,color.b*grain);}colors.needsUpdate=true;return result;};
function landmarkBox(group,x,y,z,w,h,d,color=0x8b8c80){const material=new THREE.MeshStandardMaterial({color,roughness:1,map:terrainTexture('rock')}),mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);return mesh;}
function landmarkVisual(site){const group=new THREE.Group();group.position.copy(site.pos);site.mesh=group;site.bodies=[];const box=(x,y,z,w,h,d,c)=>{const mesh=landmarkBox(group,x,y,z,w,h,d,c);site.bodies.push({x:site.pos.x+x,z:site.pos.z+z,y:site.pos.y+y-h/2,h,hx:w/2,hz:d/2,r:0,source:site,landmark:true});return mesh;};
 if(site.kind==='water'){const water=new THREE.Mesh(new THREE.CircleGeometry(Math.min(9,CELL*.35),32),new THREE.MeshStandardMaterial({color:biomeAt(site.pos.x,site.pos.z)==='frost'?0x92c9db:0x4a969c,transparent:true,opacity:.72,metalness:.28,roughness:.22,side:THREE.DoubleSide}));water.rotation.x=-Math.PI/2;water.position.y=.04;water.name='water';group.add(water);for(let i=0;i<10;i++){const a=i*.628;landmarkBox(group,Math.cos(a)*8,.2,Math.sin(a)*8,.6,.4,.6,0x748173);}}
 else if(site.kind==='village'){for(const [x,z,c]of [[-5,-4,0x927a59],[5,-4,0x9a8870],[0,6,0x82735e]]){box(x,1.2,z,4,2.4,3,c);for(let step=0;step<4;step++)landmarkBox(group,x,2.5+step*.24,z,4.5-step*.75,.3,3.6,0x596b60);}landmarkBox(group,0,.6,0,2,1.2,1,0xb59a65);}
 else if(site.kind==='dungeon'){box(-10,2,0,1,4,20,0x626871);box(10,2,0,1,4,20,0x626871);box(0,2,-10,20,4,1,0x626871);for(const x of [-6,6])box(x,2,10,8,4,1,0x626871);for(const z of [-3,3])for(const x of [-6,6])box(x,1.8,z,8,3.6,.6,0x73787b);for(const z of [-3,3,10])box(0,3.8,z,4,1,.8,0x79796e);landmarkBox(group,0,.55,-7,1.6,1.1,1,0xb59c56);}
 else{for(let i=0;i<6;i++){const a=i*Math.PI/3;box(Math.cos(a)*5,1.3,Math.sin(a)*5,1,2.6,1,0x989a85);}box(-3,.6,-2,4,1.2,.7);box(3,.4,2,3,.8,.8);landmarkBox(group,0,.5,0,1.2,1,1.2,0xaba27c);}
 G.world.add(group);}
function createExpeditionLandmarks(){const c=colony();if(c.landmarks)return;c.landmarks=[];const kinds=['village','dungeon','water','ruins','water','ruins','dungeon','village','water','ruins','water','ruins'];for(let i=0;i<kinds.length;i++){let pos;for(let trial=0;trial<40&&!pos;trial++){const q=randomWildPoint(false);if(!q)continue;const [x,z]=worldToCell(q),cell=cellAt(x,z),center=tilePoint(x,z);if(cell.ramp||center.distanceTo(G.sites[0].corePos)<CELL*5||c.landmarks.some(l=>l.pos.distanceTo(center)<CELL*2))continue;if(blockedAt(center.x,center.z,center.y,1))continue;pos=center;}if(!pos)continue;const site={id:'landmark-'+i,kind:kinds[i],pos,stage:0,claimed:false,name:kinds[i]==='village'?'Wayfarer settlement':kinds[i]==='dungeon'?'Ashvault dungeon':kinds[i]==='water'?'Springwater pool':'Old-world ruins'};c.landmarks.push(site);landmarkVisual(site);if(site.kind==='village'){const merchant={id:'settler-'+i,pos:pos.clone().add(V3(0,0,2)),hp:250,maxHp:250,role:'laborer',settled:true,stock:{logs:100,stone:80,ore:40,gateKits:2},escorts:[]};for(let j=0;j<2;j++)merchant.escorts.push({id:'village-guard-'+i+'-'+j,pos:pos.clone().add(V3(j?3:-3,0,1)),hp:160,maxHp:160,role:'knight'});c.caravans??=[];c.caravans.push(merchant);}}restoreCaravans();rebuildCollision();}
function dungeonWave(site){const stage=site.stage||0;if(stage>=3)return;site.active=true;site.stage=stage+1;for(let i=0;i<3+stage;i++){const p=site.pos.clone().add(V3((i%3-1)*2,0,-6+Math.floor(i/3)*2));const e=frontierSpawnAt(p,stage===2&&i===0?'boss':monsterKinds[(i+stage*2)%monsterKinds.length],{dungeonId:site.id,scale:stage===2?1.2:1});if(e){e.home=site.pos.clone();e.aggroId='player';e.aggroUntil=G.time+30;}}settlementNotice('Ashvault chamber '+site.stage+' / 3');}
const landmarkInteractions=interactables;
interactables=function(){const items=landmarkInteractions();for(const l of colony().landmarks||[])if(l.pos.distanceTo(G.player.pos)<13)items.push({kind:'landmark',o:l,title:l.name});return items;};
const exploreInteraction=interactWith;
interactWith=function(item){if(item.kind!=='landmark')return exploreInteraction(item);const l=item.o;if(l.kind==='water'){showInteraction(l.name,'A shallow pool. Wading slows movement.',[{label:'Rest and drink',run:()=>{if((l.restAt||0)>G.time||G.enemies.some(e=>!e.dead&&e.pos.distanceTo(G.player.pos)<12)){log('Rest requires safety and 30 seconds between drinks.');return;}l.restAt=G.time+30;G.player.hp=Math.min(G.player.maxHp,G.player.hp+25);closeInteraction();}}]);return;}if(l.kind==='village'){showInteraction(l.name,'An independent settlement. Speak to its trader at the market or hire a local ranger.',[{label:'Hire ranger · 100 gold',run:()=>{const s=gateNear(G.player.pos,10000);if(s&&G.gold>=100&&residents(s.id).length<housing(s.id)&&addResident(s,'ranger')){G.gold-=100;log('A ranger joins your home settlement');}else log('Need 100 gold and an available bed');closeInteraction();}}]);return;}if(l.kind==='dungeon'){const living=G.enemies.some(e=>!e.dead&&e.dungeonId===l.id);showInteraction(l.name,living?'Defeat the chamber guardians.':l.stage>=3?'The vault is clear.':'Three chambers guard an ancient cache.',[{label:living?'Guardians remain':l.stage>=3?(l.claimed?'Cache recovered':'Recover vault cache'):'Enter next chamber',disabled:living||l.claimed,run:()=>{if(l.stage>=3){l.claimed=true;G.gold+=200;economy().ore+=30;gainExperience(120);}else{G.player.pos.copy(l.pos).add(V3(0,0,7));dungeonWave(l);}closeInteraction();}}]);return;}showInteraction(l.name,l.claimed?'This ruin has been explored.':'An old monument holds salvage and a forgotten blessing.',[{label:'Explore the ruins',disabled:l.claimed,run:()=>{l.claimed=true;G.gold+=45;economy().stone+=15;gainExperience(40);closeInteraction();openDraft('shrine');}}]);};
const landmarkCollision=rebuildCollision;
rebuildCollision=function(){if(G?.generatedBodies){G.generatedBodies=G.generatedBodies.filter(b=>!b.landmark);for(const l of G.economy?.settlement?.landmarks||[])G.generatedBodies.push(...(l.bodies||[]));}landmarkCollision();};
function installExpeditionSky(){for(const light of scene.children)if(light.isHemisphereLight){light.color.setHex(0xb5d7e8);light.groundColor.setHex(0x827861);light.intensity=1.35;}if(G.skyDome)G.world.remove(G.skyDome);const material=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{time:{value:0}},vertexShader:'varying vec3 direction; void main(){direction=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 direction;uniform float time;void main(){vec3 d=normalize(direction);float h=max(0.,d.y);vec3 c=mix(vec3(.69,.79,.81),vec3(.22,.43,.64),pow(h,.6));float bands=sin(d.x*28.+time*.015)+sin(d.z*35.-time*.008)+sin((d.x+d.z)*61.);float cloud=smoothstep(1.15,2.35,bands)*smoothstep(.08,.28,d.y)*(1.-smoothstep(.65,.9,d.y));c=mix(c,vec3(.93,.94,.91),cloud*.6);float sunGlow=pow(max(0.,dot(d,normalize(vec3(.3,.65,.4)))),170.);gl_FragColor=vec4(c+vec3(.3,.23,.12)*sunGlow,1.);}' });G.skyDome=new THREE.Mesh(new THREE.SphereGeometry(1,32,16),material);G.skyDome.frustumCulled=false;G.skyDome.renderOrder=-10;G.world.add(G.skyDome);scene.background=new THREE.Color(0xaec7d1);scene.fog=new THREE.Fog(0xaec7d1,100,Math.max(300,CELL*30));}
const expeditionWeather=animateWilderness;
animateWilderness=function(dt){expeditionWeather(dt);if(G.birds){G.world.remove(G.birds);G.birds.visible=false;}if(!G.skyDome)installExpeditionSky();G.skyDome.position.copy(G.player.pos);G.skyDome.scale.setScalar(Math.max(200,camera.far*.8));G.skyDome.material.uniforms.time.value=G.time;sun.intensity=1.35+Math.sin(colony().day/150)*.15;for(const l of colony().landmarks||[]){const water=l.mesh?.getObjectByName('water');if(water)water.material.opacity=.68+Math.sin(G.time*.7+l.pos.x)*.04;}};
const expeditionMotion=updatePlayer;
updatePlayer=function(dt){const old=G.player.speed;if((colony().landmarks||[]).some(l=>l.kind==='water'&&G.player.pos.distanceTo(l.pos)<8))G.player.speed*=.65;try{expeditionMotion(dt);}finally{G.player.speed=old;}};
const expeditionNew=newRun;
newRun=function(...args){expeditionNew(...args);createExpeditionLandmarks();installExpeditionSky();};
const expeditionRestore=restoreSave;
restoreSave=function(save){expeditionRestore(save);for(const l of colony().landmarks||[])landmarkVisual(l);installExpeditionSky();rebuildCollision();};window.bastion.restoreSave=restoreSave;
const landmarkMini=drawMinimap;
drawMinimap=function(){landmarkMini();const ctx=$('mini').getContext('2d'),scale=160/WORLD;for(const l of colony().landmarks||[]){const [x,z]=worldToCell(l.pos);ctx.fillStyle=l.kind==='village'?'#f0d384':l.kind==='dungeon'?'#d987ca':l.kind==='water'?'#65bdd0':'#b5bcaa';ctx.fillRect(x*scale-2,z*scale-2,4,4);}};
const sharedTextureSource=terrainTexture,expeditionTextures=new Map();terrainTexture=function(kind){if(!expeditionTextures.has(kind))expeditionTextures.set(kind,sharedTextureSource(kind));return expeditionTextures.get(kind);};
