/* Reachability failures are bounded, and attacks create persistent threat. */
const expeditionResidentTask=residentTask;
residentTask=function(w,site){const savedNodes=economy().nodes,savedTowers=G.towers;w.unreachable??={};economy().nodes=savedNodes.filter(n=>(w.unreachable['node:'+n.id]||0)<=G.time);G.towers=savedTowers.filter(t=>(w.unreachable['build:'+t.uid]||0)<=G.time);try{return expeditionResidentTask(w,site);}finally{economy().nodes=savedNodes;G.towers=savedTowers;}};
const recoveringResident=walkResident;
walkResident=function(w,to,r,dt){if(w.skipGoalUntil>G.time&&w.skipGoal?.distanceTo(to)<1)return false;const before=w.pos.clone(),arrived=recoveringResident(w,to,r,dt);if(!arrived){if(w.state?.startsWith('collecting '))w.state='walking to '+w.state.slice(11);if(w.lastGoal?.distanceTo(to)<1&&before.distanceTo(w.pos)<.005)w.stalled=(w.stalled||0)+dt;else w.stalled=0;w.lastGoal=to.clone();if(w.stalled>3){w.stalled=0;w.path=[];w.pathTarget=null;w.retry=0;w.skipGoal=to.clone();w.skipGoalUntil=G.time+15;w.unreachable??={};for(const n of economy().nodes)if(n.pos.distanceTo(to)<1)w.unreachable['node:'+n.id]=G.time+40;for(const t of G.towers)if(edgeStructurePoint(t).distanceTo(to)<1)w.unreachable['build:'+t.uid]=G.time+20;if(w.command==='patrol')w.patrolIndex=((w.patrolIndex||0)+1)%8;w.state='choosing a reachable destination';}}else w.stalled=0;return arrived;};
// Use the whole-world route, including stairs, for each work approach.
workerRoute=function(w,to,radius=.6){const candidates=[];for(let i=0;i<12;i++){const a=i*Math.PI/6,p=to.clone().add(V3(Math.cos(a)*radius,0,Math.sin(a)*radius));p.y=heightAt(p.x,p.z);if(blockedAt(p.x,p.z,p.y,.27,1.6,'nav'))continue;if(walkSegment(w.pos,p,.27,'nav'))return [p];candidates.push(p);}candidates.sort((a,b)=>a.distanceToSquared(w.pos)-b.distanceToSquared(w.pos));for(const p of candidates.slice(0,2)){const route=commandPath(w.pos,p,.27);if(route.length)return route;}return [];};
const attackingThreat=hitEnemy;
hitEnemy=function(e,amount,origin,push=0){if(e&&!e.dead&&!e.rift){const friend=[G.player,...economy().workers].filter(w=>w.hp>0).sort((a,b)=>a.pos.distanceToSquared(origin)-b.pos.distanceToSquared(origin))[0];if(friend){e.aggroId=friend===G.player?'player':friend.id;e.aggroUntil=G.time+12;e.sightUntil=0;}}return attackingThreat(e,amount,origin,push);};
const woundedThreat=damage;
damage=function(e,amount){const hp=e.hp;woundedThreat(e,amount);if(!e.dead&&!e.rift&&e.hp<hp&&!e.aggroId&&G.player.pos.distanceTo(e.pos)<45){e.aggroId='player';e.aggroUntil=G.time+10;e.sightUntil=0;}};
const roamingTarget=hostileTarget;
hostileTarget=function(e){const forced=e.aggroId==='player'?G.player:economy().workers.find(w=>w.id===e.aggroId);if(forced&&forced.hp>0&&e.aggroUntil>G.time&&forced.pos.distanceTo(e.pos)<55&&(!e.home||e.pos.distanceTo(e.home)<75))return forced;e.aggroId=null;const target=roamingTarget(e);if(target&&!target.corePos){e.aggroId=target===G.player?'player':target.id;e.aggroUntil=G.time+8;}return target;};
const MANNED_DEFENSES={arrow:'ranger',ballista:'ranger',brazier:'pyromancer',frost:'pyromancer',gale:'pyromancer'};
for(const b of BUILDS)if(MANNED_DEFENSES[b.id])b.description=(b.description||b.name)+'. Requires a stationed '+MANNED_DEFENSES[b.id]+'.';
function assignedGunner(t){return economy().workers.find(w=>w.hp>0&&w.manning===t.uid&&w.role===MANNED_DEFENSES[t.b.id]);}
function staffDefense(t,id){if(t.construction||!MANNED_DEFENSES[t.b.id])return false;const w=economy().workers.find(w=>w.id===id&&w.hp>0&&w.role===MANNED_DEFENSES[t.b.id]);if(!w)return false;commandWorker(w,'guard',t.pos);w.manning=t.uid;w.guardObject={kind:'tower',id:t.uid};w.leash=3;return true;}
function resetTrap(t,worker=null,dt=1){if(!t.needsReset||t.construction)return false;const p=worker?.pos||G.player.pos;if(p.distanceTo(t.pos)>4)return false;t.resetWork=(t.resetWork||0)+dt;if(t.resetWork>=3){t.needsReset=false;t.resetWork=0;log(t.b.name+' reset');}return true;}
const garrisonCommand=commandWorker;
commandWorker=function(w,...args){w.manning=null;w.resettingTrap=null;return garrisonCommand(w,...args);};
const garrisonResidents=updateWorkers;
updateWorkers=function(dt){const all=economy().workers,repairs=G.towers.filter(t=>t.needsReset&&!t.construction);for(const t of repairs){if(all.some(w=>w.resettingTrap===t.uid))continue;const w=all.find(w=>w.hp>0&&w.role==='laborer'&&!w.command&&!w.training&&!w.staffId&&!w.resettingTrap&&residentPriorities(w).building&&w.pos.distanceTo(t.pos)<60);if(w)w.resettingTrap=t.uid;}const stationed=all.filter(w=>w.hp>0&&w.manning&&G.towers.some(t=>t.uid===w.manning&&!t.construction)),repairers=all.filter(w=>w.hp>0&&w.resettingTrap);economy().workers=all.filter(w=>!stationed.includes(w)&&!repairers.includes(w));try{garrisonResidents(dt);}finally{economy().workers=[...economy().workers,...stationed,...repairers].sort((a,b)=>a.id-b.id);}for(const w of stationed){const t=G.towers.find(t=>t.uid===w.manning);w.state=walkResident(w,t.pos,buildRadius(t.b)+.65,dt)?'manning '+t.b.name:'walking to '+t.b.name;w.mesh.position.copy(w.pos);worldHealthBar(w,w.mesh,2);updateBar(w,w.hp,w.maxHp);}for(const w of repairers){const t=G.towers.find(t=>t.uid===w.resettingTrap);if(!t?.needsReset||w.command||!residentPriorities(w).building){w.resettingTrap=null;continue;}w.state='resetting '+t.b.name;if(walkResident(w,t.pos,1.3,dt))resetTrap(t,w,dt);if(!t.needsReset)w.resettingTrap=null;w.mesh.position.copy(w.pos);}};

const operatedTowers=updateTowers;
updateTowers=function(dt){const all=G.towers;G.towers=all.filter(t=>!['spike','tar'].includes(t.b.id)&&(!MANNED_DEFENSES[t.b.id]||assignedGunner(t)?.pos.distanceTo(t.pos)<buildRadius(t.b)+1.2));try{operatedTowers(dt);}finally{G.towers=all;}for(const t of all){if(t.construction||t.needsReset||!['spike','tar'].includes(t.b.id))continue;const enemies=G.enemies.filter(e=>!e.dead&&!e.rift&&e.pos.distanceTo(t.pos)<2.3);if(!enemies.length)continue;for(const e of enemies){if(t.b.id==='spike')damage(e,t.b.dmg||24);else{e.slow=.75;e.slowT=6;}}t.needsReset=true;t.resetWork=0;effectRing(t.pos,2.3,t.b.id==='spike'?0xd6b58a:0x605174);}};
const operatedInteraction=interactWith;
interactWith=function(item){operatedInteraction(item);if(item.kind!=='tower')return;const t=item.o;if(MANNED_DEFENSES[t.b.id]){const current=assignedGunner(t);uiButton($('interactionMenu'),current?'Release '+current.role+' '+current.id:'Assign '+MANNED_DEFENSES[t.b.id]+'…',()=>{if(current){commandWorker(current,'work');interactWith(item);return;}showInteraction('Station a defender','Only the correct class can operate this defense.',economy().workers.filter(w=>w.hp>0&&w.role===MANNED_DEFENSES[t.b.id]&&!w.manning).map(w=>({label:w.role+' '+w.id,run:()=>{staffDefense(t,w.id);closeInteraction();}})));});}if(['spike','tar'].includes(t.b.id))uiButton($('interactionMenu'),t.needsReset?'Reset trap · tap 3 times':'Trap armed',()=>{resetTrap(t);interactWith(item);});};
function clearCourtyardResources(){const s=G.sites[0];if(!s)return;const ids=new Set();for(const b of G.generatedBodies||[])if(['tree','rock'].includes(b.source)&&Math.abs(b.x-s.corePos.x)<CELL*3.5&&Math.abs(b.z-s.corePos.z)<CELL*3.5){ids.add(Math.round(b.x*100)+','+Math.round(b.z*100));b.depleted=true;for(const part of b.draw||[]){const matrix=new THREE.Matrix4().makeScale(0,0,0);part.mesh.setMatrixAt(part.index,matrix);part.mesh.instanceMatrix.needsUpdate=true;}}economy().nodes=economy().nodes.filter(n=>!ids.has(n.id));rebuildCollision();}
const garrisonNew=newRun;
newRun=function(...args){garrisonNew(...args);clearCourtyardResources();const s=G.sites[0],towers=G.towers.filter(t=>t.b.id==='arrow');for(let i=0;i<towers.length;i++){const t=towers[i];t.pos.copy(s.corePos).add(V3(i?9:-9,0,9));t.pos.y=heightAt(t.pos.x,t.pos.z);[t.cx,t.cz]=worldToCell(t.pos);t.mesh.position.copy(t.pos);let w=economy().workers.find(w=>w.role==='ranger'&&!w.manning);if(!w)w=addResident(s,'ranger');if(w)staffDefense(t,w.id);}const house=G.towers.find(t=>t.b.id==='house');if(house){house.pos.copy(s.corePos).add(V3(-8,0,-8));house.pos.y=heightAt(house.pos.x,house.pos.z);[house.cx,house.cz]=worldToCell(house.pos);house.mesh.position.copy(house.pos);}rebuildCollision();};
const spacedResident=addResident;addResident=function(site,role='laborer'){const w=spacedResident(site,role);if(!w)return w;for(let i=0;i<32;i++){const a=i*Math.PI/8,p=site.corePos.clone().add(V3(Math.cos(a)*(2.6+Math.floor(i/16)),0,Math.sin(a)*(2.6+Math.floor(i/16))));p.y=heightAt(p.x,p.z);if(blockedAt(p.x,p.z,p.y,.3)||economy().workers.some(o=>o!==w&&o.pos.distanceTo(p)<.9)||G.player.pos.distanceTo(p)<.9)continue;w.pos.copy(p);w.mesh.position.copy(p);break;}return w;};
function restoreBaseApproach(){if(RUN_SETTINGS.terrainMode==='rolling')return;const s=G.sites[0];if(!s)return;const [x,z]=s.core,cleared=new Set();let level=cellAt(x,z).lvl;for(let step=3;step<20&&inGrid(x,z+step+1);step++){const c=cellAt(x,z+step),n=cellAt(x,z+step+1),delta=n.lvl-level;c.obst=null;cleared.add(key(x,z+step));if(delta>0){c.lvl=level;c.ramp=[0,1];level++;}else if(delta<0){c.lvl=level-1;c.ramp=[0,-1];level--;}else{c.lvl=level;c.ramp=null;}if(level===n.lvl&&!n.ramp)break;}for(const body of G.generatedBodies||[]){if(!['tree','rock'].includes(body.source)||!cleared.has(key(...worldToCell(V3(body.x,body.y,body.z)))))continue;body.depleted=true;for(const part of body.draw||[]){part.mesh.setMatrixAt(part.index,new THREE.Matrix4().makeScale(0,0,0));part.mesh.instanceMatrix.needsUpdate=true;}}economy().nodes=economy().nodes.filter(n=>!cleared.has(key(...worldToCell(n.pos))));s.approachRoad=true;redrawTerrain();}
const approachableBase=newRun;newRun=function(...args){approachableBase(...args);restoreBaseApproach();};
