/* Compact construction, resident orders, and branching character progression. */
function uiButton(parent,label,run){const b=document.createElement('button');b.textContent=label;b.onclick=run;parent.appendChild(b);return b;}
renderBuildCatalog=function(){if(!G||!document.getElementById('buildCatalog'))return;const category=colony().category||'Defenses',signature=[category,G.selected,G.gold,economy().logs,economy().stone,economy().ore,colony().wireLayer,colony().rampRotation].join('/');if($('buildCatalog').dataset.signature===signature)return;$('buildCatalog').dataset.signature=signature;$('buildCategories').innerHTML='';for(const name of ['Structure','Defenses','Housing','Training','Production','Portals']){const b=uiButton($('buildCategories'),name,()=>{colony().category=name;renderBuildCatalog();});b.className=name===category?'selected':'';}$('buildCatalog').innerHTML='';BUILDS.forEach((b,i)=>{if(b.retired||buildCategory(b)!==category)return;const button=uiButton($('buildCatalog'),'',()=>{G.selected=i;renderBuildCatalog();});button.className='build-card'+(G.selected===i?' selected':'');button.title=b.description||b.name;const name=document.createElement('strong'),cost=document.createElement('span');name.textContent=b.name;cost.textContent=b.core?'1 portal kit':buildCost(b)+'g · '+recipeText(DEFENSE_RECIPES[b.id]||{});button.append(name,cost);});const options=$('buildOptions');options.innerHTML='';const b=BUILDS[G.selected];if(b?.id==='wire')for(const [value,label]of [['ground','Ground'],['top','On wall'],['front','In front']]){const btn=uiButton(options,label,()=>{colony().wireLayer=value;renderBuildCatalog();});btn.className=(colony().wireLayer||'ground')===value?'selected':'';}if(b?.id==='ramp')uiButton(options,'Rotate ramp · R · '+rampDirection(),()=>{colony().rampRotation=((colony().rampRotation||0)+1)%4;renderBuildCatalog();});};
inspectBlueprint=function(){const b=BUILDS[G.selected],hit=aimPoint();if(!hit)return {b,reason:'Point at terrain.'};const cell=worldToCell(hit),p=b.core||b.wall||b.id==='ramp'?tilePoint(...cell):buildPoint(...cell,hit),side=b.wall?wallSide(...cell,hit):undefined;let reason=b.core?coreReason(p):b.wall?edgeBuildReason(b,...cell,side):placementReason(b,p);if(!reason&&!b.core&&G.gold<buildCost(b))reason='Need '+buildCost(b)+' gold.';if(!reason&&!b.core&&!canPay(DEFENSE_RECIPES[b.id]||{}))reason='Need '+recipeText(DEFENSE_RECIPES[b.id]||{})+'.';return {b,p,cell,side,reason};};
renderPlacementStatus=function(){if(!G?.buildMode)return;const plan=inspectBlueprint();$('buildStatus').textContent=G.time<(G.buildFeedbackUntil||0)?G.buildFeedback:plan.reason||'LMB / F: place · Esc: cancel';$('buildStatus').classList.toggle('blocked',!!plan.reason);$('tip').textContent=plan.reason||plan.b.name+' · LMB / F to place';};
const compactPreview=previewWall;
previewWall=function(){compactPreview();if(!G?.buildMode)return;const plan=inspectBlueprint();if(plan.b.wall&&plan.p){const [dx,dz]=WALL_SIDES[plan.side],p=edgeStructurePoint({b:plan.b,pos:plan.p,edge:plan.side,wireLayer:colony().wireLayer});G.cursor.visible=true;G.cursor.scale.set(dx?.035:1,plan.b.id==='wire'?2:7,dz?.035:1);G.cursor.position.copy(p).add(V3(0,.6,0));G.cursor.material.color.setHex(plan.reason?0xd86455:0x6bd5a8);G.rangeRing.visible=false;}renderPlacementStatus();};
function aimedConstruction(){if(G.view==='first'){const direction=camera.getWorldDirection(V3()),ray=new THREE.Ray(camera.position,direction);return G.towers.filter(t=>t.construction&&edgeStructurePoint(t).distanceTo(G.player.pos)<4).find(t=>ray.intersectsSphere(new THREE.Sphere(edgeStructurePoint(t).add(V3(0,.7,0)),t.edge?CELL*.5:buildRadius(t.b)+.3)));}raycaster.setFromCamera(mouse,camera);const p=groundHit();return p&&G.towers.filter(t=>t.construction&&edgeStructurePoint(t).distanceTo(G.player.pos)<4).sort((a,b)=>edgeStructurePoint(a).distanceToSquared(p)-edgeStructurePoint(b).distanceToSquared(p)).find(t=>edgeStructurePoint(t).distanceTo(p)<(t.edge?CELL*.55:buildRadius(t.b)+.6));}
const frontierClick=clickWorld;
clickWorld=function(){if(G.workerOrder){const w=economy().workers.find(w=>w.id===G.workerOrder);raycaster.setFromCamera(G.view==='first'?{x:0,y:0}:mouse,camera);const p=groundHit();if(w&&p){commandWorker(w,'guard',p);const t=G.towers.find(t=>edgeStructurePoint(t).distanceTo(p)<2);w.guardObject=t?{kind:'tower',id:t.uid}:null;}G.workerOrder=null;return;}const t=aimedConstruction();if(t){helpBuild(t);return;}frontierClick();};
const frontierConfirm=confirmBlueprint;
confirmBlueprint=function(){const t=aimedConstruction();if(t)return helpBuild(t);return frontierConfirm();};
const frontierInteractables=interactables;
interactables=function(){const list=frontierInteractables();for(const out of colony().outposts||[])if(!out.captured&&out.pos.distanceTo(G.player.pos)<8)list.push({kind:'outpost',o:out,title:'Monster settlement'});for(const c of colony().caravans||[])if(c.hp>0&&c.pos.distanceTo(G.player.pos)<8)list.push({kind:'merchant',o:c,title:'Traveling merchant'});return list;};
const frontierInteraction=interactWith;
interactWith=function(item){const {kind,o}=item;if(kind==='worker'){const actions=[['Follow me',()=>commandWorker(o,'follow')],['Patrol home portal',()=>commandWorker(o,'patrol')],['Guard here',()=>commandWorker(o,'guard',o.pos)],['Guard a position / object…',()=>{G.workerOrder=o.id;}],['Work using priorities',()=>commandWorker(o,'work')]].map(([label,run])=>({label,run:()=>{run();closeInteraction();}}));showInteraction((o.role||'Laborer')+' '+o.id,Math.ceil(o.hp)+' / '+o.maxHp+' HP · '+o.state,actions);const grid=document.createElement('div');grid.className='duty-grid';for(const [key,label]of [['building','Building'],['mining','Mining'],['wood','Wood collecting'],['combat','Combat']]){const row=document.createElement('label'),check=document.createElement('input'),select=document.createElement('select'),text=document.createElement('span');check.type='checkbox';check.checked=!!residentPriorities(o)[key];text.textContent=label;for(const [value,title]of [[1,'High'],[2,'Normal'],[3,'Low']]){const option=document.createElement('option');option.value=value;option.textContent=title;select.appendChild(option);}select.value=o.priorities[key]||2;check.onchange=()=>o.priorities[key]=check.checked?Number(select.value):0;select.onchange=()=>{if(check.checked)o.priorities[key]=Number(select.value);};row.append(check,text,select);grid.appendChild(row);}const leash=document.createElement('select');for(const n of [6,12,20,30]){const option=document.createElement('option');option.value=n;option.textContent='Pursuit radius: '+n+'m';leash.appendChild(option);}leash.value=o.leash||12;leash.onchange=()=>o.leash=Number(leash.value);grid.appendChild(leash);$('interactionMenu').appendChild(grid);return;}
 if(kind==='portal'){frontierInteraction(item);const s=o.original;for(const target of G.sites.filter(t=>t!==s&&t.coreHp>0))uiButton($('interactionMenu'),'Teleport to gate '+target.id,()=>{teleportPlayer(target);closeInteraction();});return;}
 if(kind==='tower'){frontierInteraction(item);if(o.construction)uiButton($('interactionMenu'),'Work on construction · tap repeatedly',()=>{helpBuild(o);interactWith(item);});if(o.b.train&&!o.construction){uiButton($('interactionMenu'),'Choose laborer to train…',()=>showInteraction(o.b.name,'35 gold + 5 ore · 30 seconds. Busy laborers can be reassigned.',eligibleLaborers(o).map(w=>({label:'Laborer '+w.id+' · '+w.state,run:()=>{trainResident(o,w.id);closeInteraction();}}))));}return;}
 if(kind==='outpost'){showInteraction('Monster settlement','Destroy its portal and defenders, then capture its surviving buildings.',[{label:'Claim surviving settlement',run:()=>{captureOutpost(o);closeInteraction();}}]);return;}
 if(kind==='merchant'){const actions=[];for(const key of ['logs','stone','ore','gateKits']){const price={logs:2,stone:3,ore:6,gateKits:180}[key];actions.push({label:'Buy '+key+' · '+price+'g · stock '+o.stock[key],run:()=>{if(!tradeMerchant(o,key,true))log('Not enough gold or stock');interactWith(item);}},{label:'Sell '+key+' · '+Math.floor(price/2)+'g',run:()=>{if(!tradeMerchant(o,key,false))log('You have none to sell');interactWith(item);}});}showInteraction('Traveling merchant','Gold '+G.gold+' · Escorted caravans rest near friendly portals.',actions);return;}frontierInteraction(item);};
showSettlementLedger=function(){$('interactionMenu').classList.add('hidden');G.uiCursor=true;document.exitPointerLock?.();const panel=$('settlementPanel');panel.classList.remove('hidden');panel.innerHTML='<header><h2>Portal settlements</h2><button id="ledgerClose">Close</button></header><select id="ledgerGate"></select><nav id="ledgerTabs"></nav><div id="ledgerContent"></div>';for(const s of G.sites){const option=document.createElement('option');option.value=s.id;option.textContent='Gate '+s.id+' · '+s.status;$('ledgerGate').appendChild(option);}$('ledgerGate').value=colony().ledgerGate||G.sites[0]?.id;$('ledgerGate').onchange=()=>{colony().ledgerGate=Number($('ledgerGate').value);renderLedger();};for(const tab of ['Residents','Buildings'])uiButton($('ledgerTabs'),tab,()=>{colony().ledgerTab=tab;renderLedger();});$('ledgerClose').onclick=()=>{panel.classList.add('hidden');G.uiCursor=false;captureFirstPerson();};renderLedger();};
renderLedger=function(){if(!document.getElementById('ledgerGate')||$('settlementPanel').classList.contains('hidden'))return;const id=Number($('ledgerGate').value),content=$('ledgerContent');content.innerHTML='';const row=(title,description,o,kind)=>{const article=document.createElement('article'),strong=document.createElement('strong'),small=document.createElement('p');strong.textContent=title;small.textContent=description;article.append(strong,small);const b=uiButton(article,'Interact',()=>{if((o.pos||o.corePos).distanceTo(G.player.pos)>8){log('Move within 8m to issue orders.');return;}interactWith({kind,o,title});});b.title='Available within 8m';content.appendChild(article);};if((colony().ledgerTab||'Residents')==='Residents')for(const w of economy().workers.filter(w=>w.siteId===id))row(w.role+' '+w.id,w.state+' · '+Math.ceil(w.hp)+' HP · '+Math.round(w.pos.distanceTo(G.player.pos))+'m',w,'worker');else for(const t of G.towers.filter(t=>t.siteId===id))row(t.b.name,t.construction?Math.floor(t.construction.done/t.construction.total*100)+'% built':Math.ceil(t.hp||180)+' HP',t,'tower');};
const TALENT_BRANCHES={knight:['Vanguard','Battle captain'],ranger:['Sharpshooter','Pathfinder'],pyromancer:['Inferno','Spellweaver']};
function talentNodes(){const branches=TALENT_BRANCHES[G.classId],skills=[[1,3,4],[2,5,null]];return skills.flatMap((list,b)=>list.map((ability,tier)=>({id:b+'-'+tier,branch:branches[b],ability,level:2+tier*2,requires:tier?b+'-'+(tier-1):null,name:ability===null?G.classId==='knight'?'Unyielding: +30 health':G.classId==='ranger'?'Quickdraw: 20% faster recovery':'Kindled: +20% spell damage':ABILITIES[G.classId][ability][0]})));}
function talentPoints(){return Math.max(0,(G.player.level||1)-1-(G.player.talents||[]).length);}
function learnTalent(id){const node=talentNodes().find(n=>n.id===id),p=G.player;p.talents??=[];if(!node||p.talents.includes(id)||!talentPoints()||p.level<node.level||node.requires&&!p.talents.includes(node.requires))return false;p.talents.push(id);if(node.ability===null&&G.classId==='knight'){p.maxHp+=30;p.hp+=30;}updateCombatUI();return true;}
abilityUnlocked=function(i){return i===0||talentNodes().some(n=>n.ability===i&&G.player.talents?.includes(n.id));};
gainExperience=function(amount){const p=G.player;p.level??=1;p.xp=(p.xp||0)+amount;while(p.xp>=p.level*35){p.xp-=p.level*35;p.level++;p.maxHp+=5;p.hp=Math.min(p.maxHp,p.hp+20);settlementNotice('Level '+p.level+' · Talent point earned. Open Talents to choose a branch.');}G.uiNext=0;};
function showTalents(){showInteraction('Talents · '+talentPoints()+' points','Spend one point per choice. Follow a branch downward or combine both branches.',[]);const menu=$('interactionMenu');menu.classList.add('talent-menu');const close=menu.lastElementChild;close.remove();const tree=document.createElement('div');tree.className='talent-tree';for(const branch of TALENT_BRANCHES[G.classId]){const column=document.createElement('section'),heading=document.createElement('h4');heading.textContent=branch;column.appendChild(heading);for(const n of talentNodes().filter(n=>n.branch===branch)){const learned=G.player.talents?.includes(n.id),b=uiButton(column,branch+' → '+n.name+' · Lv '+n.level+(learned?' · learned':''),()=>{learnTalent(n.id);showTalents();});b.disabled=learned||G.player.level<n.level||!talentPoints()||!!n.requires&&!G.player.talents?.includes(n.requires);b.className=learned?'learned':'';b.title=n.ability===null?n.name:MOVE_INFO[G.classId][n.ability];}tree.appendChild(column);}menu.append(tree,close);}

const talentCast=castAbility;
castAbility=function(i){const p=G.player,boost=G.classId==='pyromancer'&&p.talents?.includes('1-2'),old=p.ranged;if(boost)p.ranged*=1.2;let result;try{result=talentCast(i);}finally{p.ranged=old;}if(result&&G.classId==='ranger'&&p.talents?.includes('1-2'))G.abilityCds[i]*=.8;return result;};
const frontierTooltip=showMoveTooltip;
showMoveTooltip=function(i){frontierTooltip(i);if(!abilityUnlocked(i))$('moveTooltip').innerHTML='<strong>'+ABILITIES[G.classId][i][0]+'</strong><p>Learn this move in the Talents menu.</p><p>'+MOVE_INFO[G.classId][i]+'</p>';};
const frontierInput=bindInput;
bindInput=function(){frontierInput();addEventListener('keydown',e=>{if(e.target?.closest?.('input,select,textarea')||!G||menuPaused)return;if(e.code==='KeyR'&&G.buildMode&&BUILDS[G.selected].id==='ramp'&&!e.repeat){colony().rampRotation=((colony().rampRotation||0)+1)%4;renderBuildCatalog();}if(e.code==='KeyF'&&!G.buildMode&&!e.repeat){const t=aimedConstruction();if(t)helpBuild(t);}if(e.code==='KeyN'&&!e.repeat)showTalents();});};
const campaignInstall=installIntegration;
installIntegration=function(){campaignInstall();const options=document.createElement('div');options.id='buildOptions';$('constructionPanel').appendChild(options);$('constructionPanel').querySelector('h2').textContent='Build';$('help').innerHTML='<b>Controls</b><div>B build · LMB / F place or help build · Esc cancel</div><div>E interact · N talents · R rotate ramp</div><div>Use E at a new portal to start each defense wave</div><div>1–6 select / repeat to cast · RMB ability: automatic</div><div>Tab target · V camera · Space jump</div>';const button=document.createElement('button');button.id='talentToggle';button.textContent='Talents';button.onclick=showTalents;const parent=$('settlementToggle').parentElement||document.body;parent.appendChild(button);$('missionPrimary').style.display='none';};

const campaignCombatUI=updateCombatUI;updateCombatUI=function(){campaignCombatUI();if(G&&combatUIReady)for(let i=1;i<6;i++)if(!abilityUnlocked(i))$('ability'+i).querySelector('.ability-cd').textContent='Talent';};

const campaignInteractionMenu=showInteraction;showInteraction=function(...args){$('interactionMenu').classList.remove('talent-menu');$('settlementPanel').classList.add('hidden');return campaignInteractionMenu(...args);};

const centeredObstructionCamera=updateCamera;updateCamera=function(){centeredObstructionCamera();if(G?.view==='third')camera.lookAt(G.player.pos.clone().add(V3(0,1.5,0)));};
