/* Resident orders use stable world positions; priorities are independent of current work. */
function residentPriorities(w){w.priorities??={building:1,mining:2,wood:2,combat:w.role==='laborer'?3:1};return w.priorities;}
function npcAnchor(w){if(w.guardObject){if(w.guardObject.kind==='tower'){const t=G.towers.find(t=>t.uid===w.guardObject.id);if(t)return edgeStructurePoint(t);}else{const s=G.sites.find(s=>s.id===w.guardObject.id);if(s)return s.corePos;}}return w.guardAnchor||w.commandGoal||G.sites.find(s=>s.id===w.siteId)?.corePos||w.pos;}
commandWorker=function(w,command,point){if(w.training){const remaining=clamp(1-(w.training.done||0)/30,0,1);G.gold+=Math.floor(35*remaining);economy().ore+=Math.floor(5*remaining);}w.guardObject=null;w.command=command==='work'?null:command;w.commandGoal=point?.clone()||null;if(command==='guard'){w.guardAnchor=(point||w.pos).clone();w.leash??=12;}w.staffId=null;w.training=null;clearResidentTask(w);w.state=command==='work'?'idle':command;w.retry=0;};
walkResident=function(w,destination,radius,dt){dt=Math.min(dt,.1);if(!destination||![w.pos.x,w.pos.y,w.pos.z].every(Number.isFinite))return false;const goal=destination.clone();goal.y=heightAt(goal.x,goal.z);if(w.pos.distanceTo(goal)<=radius+.2){w.path=[];return true;}w.retry=(w.retry||0)-dt;if(!w.pathTarget||w.pathTarget.distanceTo(goal)>2||(!w.path?.length&&w.retry<=0)){if(colony().pathBudget<=0)return false;colony().pathBudget--;const direction=w.pos.clone().sub(goal);direction.y=0;if(direction.lengthSq()<.01)direction.set(1,0,0);const end=goal.clone().add(direction.normalize().multiplyScalar(radius));end.y=heightAt(end.x,end.z);w.path=walkSegment(w.pos,end,.27,'nav')?[end]:workerRoute(w,goal,radius);w.pathTarget=goal.clone();w.retry=2;}while(w.path?.length&&w.pos.distanceTo(w.path[0])<.22)w.path.shift();if(w.path?.length){const delta=w.path[0].clone().sub(w.pos);delta.y=0;const distance=delta.length();if(distance>.01){delta.normalize();const q=w.pos.clone().addScaledVector(delta,Math.min(distance,dt*(w.retreating?4.3:3.2)));q.y=heightAt(q.x,q.z);if(walkSegment(w.pos,q,.27,'nav')){w.pos.copy(q);w.yaw=Math.atan2(delta.x,delta.z);}else{w.path=[];w.retry=.5;}}}if(w.mesh){w.mesh.position.copy(w.pos);w.mesh.rotation.set(0,w.yaw||0,0);}return w.pos.distanceTo(goal)<=radius+.35;};
function eligibleLaborers(t){return economy().workers.filter(w=>w.role==='laborer'&&w.hp>0&&!w.training&&(w.siteId===t.siteId||w.pos.distanceTo(t.pos)<25)).sort((a,b)=>a.pos.distanceToSquared(t.pos)-b.pos.distanceToSquared(t.pos));}
availableLaborer=function(siteId){return economy().workers.find(w=>w.role==='laborer'&&w.hp>0&&w.siteId===siteId&&!w.training);};
trainResident=function(t,npcId){if(t.construction||!t.b.train)return false;const w=eligibleLaborers(t).find(w=>npcId===undefined||w.id===npcId);if(!w){log('No living, untrained laborer belongs to this area. Recruit one through a house.');return false;}if(G.gold<35||!canPay({ore:5})){log('Training costs 35 gold and 5 ore');return false;}G.gold-=35;pay({ore:5});w.command=null;w.staffId=null;clearResidentTask(w);w.training={building:t.uid,role:t.b.train,done:0};w.state=w.cargo?'delivering before training':'traveling to training';settlementNotice('Laborer '+w.id+' assigned to '+t.b.name);return true;};
function residentTask(w,site){const priorities=residentPriorities(w),tasks=[];if(priorities.building)for(const t of G.towers)if(t.construction&&t.pos.distanceTo(w.pos)<90)tasks.push({type:'build',object:t,priority:priorities.building,d:w.pos.distanceTo(t.pos)});for(const n of economy().nodes){const priority=n.kind==='logs'?priorities.wood:priorities.mining;if(priority&&n.siteId===site.id&&n.remaining>0)tasks.push({type:'harvest',object:n,priority,d:w.pos.distanceTo(n.pos)});}if(priorities.combat){const enemy=G.enemies.filter(e=>!e.dead&&e.pos.distanceTo(w.pos)<12).sort((a,b)=>a.pos.distanceToSquared(w.pos)-b.pos.distanceToSquared(w.pos))[0];if(enemy)tasks.push({type:'combat',object:enemy,priority:priorities.combat,d:w.pos.distanceTo(enemy.pos)});}tasks.sort((a,b)=>a.priority-b.priority||a.d-b.d);return tasks[0];}
function safeCourtyard(w){return G.sites.filter(s=>s.coreHp>0&&(s.innerFort||G.towers.filter(t=>t.siteId===s.id&&t.edge&&t.b.id!=='wire'&&!t.construction).length>=4)).sort((a,b)=>a.corePos.distanceToSquared(w.pos)-b.corePos.distanceToSquared(w.pos))[0];}
function strikeResident(w,target,dt){if(!target||target.dead)return;const range=w.role==='ranger'?13:w.role==='pyromancer'?10:2.3,d=w.pos.distanceTo(target.pos);if(d>range){walkResident(w,target.pos,range*.75,dt);return;}w.attackCd=(w.attackCd||0)-dt;if(w.attackCd>0)return;const origin=w.pos.clone().add(V3(0,1,0));const hit=projectileObstacle(origin,target.pos.clone().add(V3(0,target.d.size,0)),w.mesh);if(hit&&hit.distanceTo(origin)<d-1)return;w.attackCd=w.role==='laborer'?1.1:.9;w.workSwing=G.time+.25;if(range>3)tracer(origin,target.pos.clone().add(V3(0,1,0)),w.role==='ranger'?0xd8e6ac:0xff9855);if(w.role==='pyromancer'){for(const e of G.enemies)if(!e.dead&&e.pos.distanceTo(target.pos)<2.4)hitEnemy(e,11,w.pos,2);}else hitEnemy(target,w.role==='laborer'?4:w.role==='knight'?17:12,w.pos,w.role==='knight'?4:1);}
function worldHealthBar(owner,group,height,color=0x81c986){if(owner.hb?.parent)return;const back=new THREE.Mesh(new THREE.PlaneGeometry(1.5,.13),new THREE.MeshBasicMaterial({color:0x263137,depthTest:false})),fill=new THREE.Mesh(new THREE.PlaneGeometry(1.44,.09),new THREE.MeshBasicMaterial({color,depthTest:false}));const bar=new THREE.Group();bar.position.y=height;back.renderOrder=fill.renderOrder=10;fill.position.z=.002;bar.add(back,fill);group.add(bar);owner.hb=bar;bar.userData.fill=fill;}
function updateBar(owner,hp,max){if(!owner.hb)return;owner.hb.lookAt(camera.position);const fraction=clamp(hp/max,0,1);owner.hb.userData.fill.scale.x=Math.max(.001,fraction);owner.hb.userData.fill.position.x=-(1-fraction)*.72;}
updateWorkers=function(dt){const eco=economy();colony().pathBudget=3;for(const w of eco.workers){w.role??='laborer';w.hp??=60;w.maxHp??=60;w.job='laborer';residentPriorities(w);const site=G.sites.find(s=>s.id===w.siteId&&s.coreHp>0)||G.sites.find(s=>s.coreHp>0);if(!site)continue;w.siteId=site.id;const threats=G.enemies.filter(e=>!e.dead&&!e.rift&&e.pos.distanceTo(w.pos)<7);if(w.hp<w.maxHp*.35&&threats.length&&w.role==='laborer')w.retreating=true;if(w.retreating&&w.hp>w.maxHp*.8)w.retreating=false;
 if(w.retreating){const safe=safeCourtyard(w)||site;w.state='retreating to courtyard';walkResident(w,safe.corePos,2.5,dt);}
 else if(w.cargo&&(!w.command||w.training)){w.state=w.training?'delivering before training':'delivering';if(walkResident(w,site.corePos,2.5,dt)){eco[w.cargoKind||'logs']+=w.cargo;w.cargo=0;clearResidentTask(w);}}
 else if(w.training){const t=G.towers.find(t=>t.uid===w.training.building);if(!t){w.training=null;continue;}w.state='training '+Math.floor(w.training.done)+'/30s';if(walkResident(w,t.pos,buildRadius(t.b)+.8,dt)){w.training.done+=dt;if(w.training.done>=30){w.role=w.training.role;w.maxHp=w.role==='knight'?120:85;w.hp=w.maxHp;w.training=null;w.command='patrol';w.mesh.children[0].material.color.setHex(w.role==='knight'?0x809fb4:w.role==='ranger'?0x729e70:0xc87c54);settlementNotice('Resident '+w.id+' completed training');}}}
 else if(w.command==='follow'){w.state='following';walkResident(w,G.player.pos,2+(w.id%3)*.45,dt);}
 else if(w.command==='move'){w.state='moving';if(w.commandGoal&&walkResident(w,w.commandGoal,.3,dt)){w.command='guard';w.guardAnchor=w.pos.clone();w.leash=8;}}
 else if(['guard','patrol','stay'].includes(w.command)){const anchor=w.command==='patrol'?site.corePos:npcAnchor(w),leash=w.command==='patrol'?site.r*CELL:(w.leash||10);const target=G.enemies.filter(e=>!e.dead&&e.pos.distanceTo(anchor)<leash&&e.pos.distanceTo(w.pos)<18).sort((a,b)=>a.pos.distanceToSquared(w.pos)-b.pos.distanceToSquared(w.pos))[0];if(target&&residentPriorities(w).combat){w.state='defending';strikeResident(w,target,dt);}else if(w.command==='patrol'){w.state='patrolling';w.patrolIndex??=w.id%8;const angle=w.patrolIndex*Math.PI/4,p=site.corePos.clone().add(V3(Math.cos(angle)*Math.min(site.r*CELL*.55,22),0,Math.sin(angle)*Math.min(site.r*CELL*.55,22)));p.y=heightAt(p.x,p.z);if(walkResident(w,p,1.5,dt))w.patrolIndex=(w.patrolIndex+1)%8;}else{w.state='guarding position';walkResident(w,anchor,1,dt);}}
 else if(w.role!=='laborer'){w.command='patrol';}
 else if(w.staffId){const t=G.towers.find(t=>t.uid===w.staffId&&!t.construction);if(!t){w.staffId=null;continue;}const enabled=t.b.produce==='logs'?w.priorities.wood:w.priorities.mining;w.state=enabled?'staffed production':'production disabled';if(enabled&&walkResident(w,t.pos,buildRadius(t.b)+.7,dt)){w.work=(w.work||0)+dt*(1+eco.harvestLevel*.3);if(w.work>=10){w.work-=10;eco[t.b.produce]+=t.b.produce==='logs'?3:1;if(t.b.id==='mine')eco.stone+=2;}}}
 else{const task=residentTask(w,site);if(!task){w.state='idle';}else if(task.type==='combat'){w.state='defending';strikeResident(w,task.object,dt);}else if(task.type==='build'){const t=task.object;w.state='building '+t.b.name;if(walkResident(w,edgeStructurePoint(t),t.edge?1.2:buildRadius(t.b)+.8,dt)){t.construction.done+=dt;const fraction=Math.min(1,t.construction.done/t.construction.total);t.mesh.scale.y=.25+fraction*.75;if(t.construction.done>=t.construction.total)finishConstruction(t);}}else{const n=task.object;w.state='collecting '+n.kind;if(walkResident(w,n.pos,(n.radius||1)+.6,dt)){w.work=(w.work||0)+dt*(1+eco.harvestLevel*.3);if(w.work>=3){w.work=0;const amount=Math.min(4,n.remaining);n.remaining-=amount;w.cargo=amount;w.cargoKind=n.kind;w.path=[];}}}}
 if(w.pos.distanceTo(site.corePos)<6&&!threats.length)w.hp=Math.min(w.maxHp,w.hp+dt*4);if(w.mesh){w.mesh.visible=w.hp>0;w.mesh.position.copy(w.pos);w.mesh.rotation.set(0,w.yaw||0,0);const tool=w.mesh.getObjectByName('workTool');if(tool)tool.rotation.x=/building|collecting/.test(w.state)||w.workSwing>G.time?Math.sin(G.time*8)*.8:0;worldHealthBar(w,w.mesh,1.65);updateBar(w,w.hp,w.maxHp);}}
 for(const w of eco.workers)if(w.hp<=0){G.world.remove(w.mesh);settlementNotice('Resident '+w.id+' was lost');}eco.workers=eco.workers.filter(w=>w.hp>0);
 for(const t of G.towers){if(t.construction||t.b.id!=='house'||t.recruitPaused)continue;t.recruitTime=(t.recruitTime||0)+dt;const s=G.sites.find(s=>s.id===t.siteId&&s.status==='secured'&&s.coreHp>0);if(t.recruitTime>=90&&s&&residents(s.id).length<housing(s.id)&&G.gold>=15&&addResident(s)){G.gold-=15;t.recruitTime=0;}}
 for(const s of G.sites){if(s.coreHp<=0)continue;s.magicCd=(s.magicCd||0)-dt;if(s.magicCd<=0){const enemy=G.enemies.filter(e=>!e.dead&&e.pos.distanceTo(s.corePos)<14).sort((a,b)=>a.pos.distanceToSquared(s.corePos)-b.pos.distanceToSquared(s.corePos))[0];if(enemy){const from=s.corePos.clone().add(V3(0,2,0));if(!projectileObstacle(from,enemy.pos.clone().add(V3(0,1,0)),s.coreMesh)){tracer(from,enemy.pos.clone().add(V3(0,1,0)),0x82f4e7);hitEnemy(enemy,18,s.corePos,3);s.magicCd=1;}}}}updateStructures(dt);
};
function teleportPlayer(site){const source=gateNear(G.player.pos,8);if(!source||source.coreHp<=0||site.coreHp<=0||site.id===source.id)return false;const p=gateArrival(site);if(!p){log('Clear room beside the destination gate');return false;}G.player.pos.copy(p);G.player.vy=0;G.playerMesh.position.copy(p);keys={};effectRing(p,2,0x80e5dd);updateCamera();settlementNotice('Travelled to portal '+site.id);return true;}

workerRoute=function(w,to,radius=.6){const candidates=[];for(let i=0;i<8;i++){const p=to.clone().add(V3(Math.cos(i*Math.PI/4)*radius,0,Math.sin(i*Math.PI/4)*radius));p.y=heightAt(p.x,p.z);if(blockedAt(p.x,p.z,p.y,.27,1.6,'nav'))continue;if(walkSegment(w.pos,p,.27,'nav'))return [p];candidates.push(p);}candidates.sort((a,b)=>a.distanceToSquared(w.pos)-b.distanceToSquared(w.pos));for(const p of candidates.slice(0,2)){const plan=gridPlan(w.pos,p,.27);if(plan?.path?.length)return plan.path;}return [];};

staffBuilding=function(t){if(t.construction||!t.b.produce)return false;if(economy().workers.some(w=>w.staffId===t.uid)){log('Already staffed');return false;}const w=eligibleLaborers(t).find(w=>!w.staffId);if(!w){log('No available laborer: release one from another production building.');return false;}commandWorker(w,'work');w.staffId=t.uid;w.state='assigned';return true;};
