/* Persistent hostile gates share the combat entity system: every weapon can hurt them. */
Object.assign(ENEMIES,{stalker:{hp:40,spd:4.1,gold:6,dmg:9,size:.38,color:0x65538d},spitter:{hp:50,spd:2,gold:8,dmg:7,size:.48,color:0x83aa45},bulwark:{hp:210,spd:1.2,gold:18,dmg:16,size:.8,color:0x697781},bomber:{hp:28,spd:3.4,gold:7,dmg:24,size:.45,color:0xe78932},frostling:{hp:60,spd:2.5,gold:9,dmg:6,size:.5,color:0x7edce5},rift:{hp:450,spd:0,gold:60,dmg:0,size:1.2,color:0xf26b66},watchtower:{hp:180,spd:0,gold:25,dmg:12,size:.8,color:0x95534e}});
Object.assign(names,{stalker:'Dusk Stalker',spitter:'Venom Spitter',bulwark:'Ironhide Bulwark',bomber:'Cinder Bomber',frostling:'Rime Wraith',rift:'Monster Portal Gate',watchtower:'Settlement Watchtower'});
const frontierSpawn=spawnEnemy;
spawnEnemy=function(type,gate,scale){const e=frontierSpawn(type,gate,scale);if(!e)return e;if(type==='rift'){e.rift=true;e.mesh.remove(e.body);const model=gateMesh(true);e.mesh.add(model);e.body=model.children[0];e.hb.position.y=3.4;}if(type==='watchtower'){e.mesh.remove(e.body);const model=towerMesh(BUILDS.find(b=>b.id==='arrow'));e.mesh.add(model);e.body=model.children.find(o=>o.isMesh&&o.material?.emissive)||e.body;}return e;};
const monsterKinds=['grunt','runner','stalker','spitter','bulwark','bomber','frostling','shaman'];
function frontierSpawnAt(p,type,extra={}){if(!p||G.enemies.filter(e=>!e.dead).length>=280)return null;p=p.clone();p.y=heightAt(p.x,p.z);if(type!=='rift'&&type!=='watchtower'&&blockedAt(p.x,p.z,p.y,ENEMIES[type].size,1.6,'nav')){let free;for(let i=0;i<16&&!free;i++){const q=p.clone().add(V3(Math.cos(i*Math.PI/4)*(1+Math.floor(i/8)*2),0,Math.sin(i*Math.PI/4)*(1+Math.floor(i/8)*2)));q.y=heightAt(q.x,q.z);if(!blockedAt(q.x,q.z,q.y,ENEMIES[type].size,1.6,'nav')&&!noSpawnAt(q))free=q;}if(!free)return null;p=free;}const e=spawnEnemy(type,null,extra.scale||1);Object.assign(e,{mode:'wild',home:p.clone(),cell:worldToCell(p),wanderT:0,wanderDir:V3(),...extra});e.pos.copy(p);e.mesh.position.copy(p);return e;}
wildernessSpawn=function(p,type='grunt',scale=1){if(noSpawnAt(p)||blockedAt(p.x,p.z,p.y,.65,1.6,'nav'))return null;return frontierSpawnAt(p,type,{scale});};
function drawRiftRoute(e){if(!e.portalSiteId)return;for(const line of e.routeLines||[])G.world.remove(line);const site=G.sites.find(s=>s.id===e.portalSiteId);if(!site)return;let path;for(let i=0;i<8&&!path;i++){const start=e.pos.clone().add(V3(Math.cos(i*Math.PI/4)*2,0,Math.sin(i*Math.PI/4)*2));start.y=heightAt(start.x,start.z);if(!blockedAt(start.x,start.z,start.y,.35,1.6,'nav'))path=gridPlan(start,site.corePos,.35)?.path;}if(!path?.length)return;const points=[e.pos,...path].map(p=>p.clone().add(V3(0,.12,0))),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xde5149,transparent:true,opacity:.75}));G.world.add(line);e.routeLines=[line];}
function spawnRift(p,extra={}){const e=frontierSpawnAt(p,'rift',extra);if(e){e.portalClock=2;drawRiftRoute(e);rebuildCollision();}return e;}
const frontierDamage=damage;
damage=function(e,n){if(e.type==='bulwark')n*=.6;if(e.rift||e.type==='watchtower'){e.vy=0;e.knockback=V3();}const alive=!e.dead;frontierDamage(e,n);if(alive&&e.dead){for(const l of e.routeLines||[])G.world.remove(l);if(e.rift||e.type==='watchtower')rebuildCollision();if(e.rift)settlementNotice('Monster gate destroyed. Its reinforcements have stopped.');}};
function hurtGate(s,n){if(s.coreHp<=0)return;s.coreHp=Math.max(0,s.coreHp-n);if(!s.coreHp){s.status='destroyed';s.coreMesh.visible=false;if(s.wardMesh)s.wardMesh.visible=false;s.edge.material.color.setHex(0x615b5a);if(G.site===s){G.site=G.sites.find(o=>o.status==='pending'&&o.coreHp>0)||null;G.spawnQueue=[];G.phase=G.site?'build':'explore';if(G.site)G.site.status='active';}settlementNotice('Portal gate '+s.id+' has fallen. Its protection is gone.');rebuildCollision();if(!G.sites.some(o=>o.coreHp>0))endRun(false);}}
function hurtFriendly(target,n){if(target===G.player)playerHit(n);else if(target.corePos)hurtGate(target,n);else target.hp=Math.max(0,target.hp-n);}
function enemyAdvance(e,goal,dt,budget){e.pathRetry=(e.pathRetry||0)-dt;let next=goal;if(!walkSegment(e.pos,goal,e.d.size,'nav')){if(e.pathRetry<=0&&budget.count>0){budget.count--;e.wildPath=commandPath(e.pos,goal,e.d.size);e.pathRetry=2+G.rng();}while(e.wildPath?.length&&e.pos.distanceTo(e.wildPath[0])<.4)e.wildPath.shift();next=e.wildPath?.[0];}if(!next)return false;const delta=next.clone().sub(e.pos);delta.y=0;if(delta.lengthSq()<.01)return true;delta.normalize();let speed=e.d.spd*(1-Math.min(.75,e.slow||0))*(e.type==='stalker'&&e.pos.distanceTo(goal)<8?1.7:1);if(typeof steerForgedEnemy==='function')speed*=steerForgedEnemy(e,delta,dt,speed);const q=e.pos.clone().addScaledVector(delta,speed*dt);const gate=closedGateAt(q,e.d.size);if(gate){e.bash=gate;return false;}const before=e.pos.clone();tryMove(e.pos,delta.x*speed*dt,delta.z*speed*dt);e.mesh.rotation.y=Math.atan2(delta.x,delta.z);return e.pos.distanceToSquared(before)>.000001||!!e.forgePivoting;}
startWave=function(){const s=G.site;if(!s||G.phase!=='build')return false;if(G.player.pos.distanceTo(s.corePos)>8){log('Use E at the new portal gate to begin its defense.');return false;}G.phase='fight';G.spawnQueue=[];G.spawnT=0;const wave=s.wave||0;for(let i=0;i<32+wave*10;i++){const a=(i%8)*Math.PI/4,r=s.r*CELL+6+(i%3)*2,p=s.corePos.clone().add(V3(Math.cos(a)*r,0,Math.sin(a)*r));p.y=heightAt(p.x,p.z);if(inGrid(...worldToCell(p)))G.spawnQueue.push({t:i*.45,type:monsterKinds[(i+wave)%monsterKinds.length],pos:p,portalSiteId:s.id,assault:true});}let point;for(let i=0;i<60&&!point;i++){const a=G.rng()*Math.PI*2,r=8+G.rng()*Math.max(1,s.r*CELL-10),p=s.corePos.clone().add(V3(Math.cos(a)*r,0,Math.sin(a)*r));p.y=heightAt(p.x,p.z);if(inGrid(...worldToCell(p))&&!noSpawnAt(p)&&!blockedAt(p.x,p.z,p.y,1.2,2,'nav')&&gridPlan(p,s.corePos,.35)?.path?.length)point=p;}if(!point){G.phase='build';G.spawnQueue=[];log('Clear space inside the claim for a reachable hostile gate.');return false;}spawnRift(point,{portalSiteId:s.id});setMsg('Defense '+(wave+1)+' / '+WAVES_PER_SITE,'Destroy the monster gates to stop their reinforcements.',4);return true;};
function canFinishAssault(){const s=G.site;if(!s||G.phase!=='fight'||G.spawnQueue.length)return false;if(G.enemies.some(e=>!e.dead&&e.assault&&e.portalSiteId===s.id))return false;if(s.wave>=WAVES_PER_SITE-1&&G.enemies.some(e=>!e.dead&&e.portalSiteId===s.id))return false;return true;}
function enemySees(e,o){const a=e.pos.clone().add(V3(0,1,0)),b=o.pos.clone().add(V3(0,1,0)),hit=projectileObstacle(a,b,e.mesh);return !hit||hit.distanceTo(a)>=a.distanceTo(b)-1.2;}
function hostileTarget(e){if(e.sightUntil>G.time){const t=e.seenTarget;if(t&&(t.hp>0||t.coreHp>0)&&e.pos.distanceTo(t.pos||t.corePos)<25)return t;return null;}e.sightUntil=G.time+.6;const residents=[G.player,...economy().workers,...(colony().caravans||[]).flatMap(c=>[c,...c.escorts])].filter(o=>o.hp>0);const seen=residents.filter(o=>o.pos.distanceTo(e.pos)<(e.type==='spitter'?18:14)&&enemySees(e,o)).sort((a,b)=>a.pos.distanceToSquared(e.pos)-b.pos.distanceToSquared(e.pos));const gate=G.sites.find(s=>s.coreHp>0&&e.pos.distanceTo(s.corePos)<s.r*CELL);return e.seenTarget=seen.find(o=>o.pos.distanceTo(e.pos)<5)||gate||seen[0]||null;}
updateEnemies=function(dt){dt=Math.min(dt,.1);const budget={count:G.time>=(G.enemyPlanAt||0)?1:0};if(budget.count)G.enemyPlanAt=G.time+.12;if(G.phase==='fight'){G.spawnT+=dt;while(G.spawnQueue.length&&G.spawnQueue[0].t<=G.spawnT){const q=G.spawnQueue.shift();if(q.pos&&!noSpawnAt(q.pos))frontierSpawnAt(q.pos,q.type,{portalSiteId:q.portalSiteId,assault:true});}}
 for(const e of G.enemies.slice()){if(e.dead)continue;if(e.forgeAnimationReady){e.forgePivoting=false;delete e.forgeAim;}if(!e.rift&&!e.portalSiteId&&e.pos.distanceTo(G.player.pos)>65&&!economy().workers.some(w=>w.pos.distanceTo(e.pos)<25))continue;if(e.rift){e.portalClock=(e.portalClock||0)-dt;if(e.portalClock<=0){e.portalClock=e.outpostId?12:8;for(let i=0;i<4;i++){const a=G.rng()*6.28,p=e.pos.clone().add(V3(Math.cos(a)*2,0,Math.sin(a)*2));p.y=heightAt(p.x,p.z);if(!noSpawnAt(p))frontierSpawnAt(p,monsterKinds[Math.floor(G.rng()*monsterKinds.length)],{portalSiteId:e.portalSiteId,outpostId:e.outpostId,scale:e.outpostId?1.8:1.15});}}}else{
 if(e.type!=='watchtower'&&updateEnemyPhysics(e,dt))continue;const target=hostileTarget(e),goal=target?.corePos||target?.pos;const range=e.type==='spitter'||e.type==='frostling'||e.type==='watchtower'?11:e.d.size+(target?.corePos?2.1:1.2);e.attackCd=(e.attackCd||0)-dt;e.bash=null;
 if(goal){const distance=e.pos.distanceTo(goal);if((distance>range||range>4&&!enemySees(e,{pos:goal}))&&e.d.spd){if(!enemyAdvance(e,goal,dt,budget)){e.bash??=G.towers.filter(t=>!t.construction&&t.b.blocks&&edgeStructurePoint(t).distanceTo(e.pos)<CELL+1).sort((a,b)=>edgeStructurePoint(a).distanceToSquared(e.pos)-edgeStructurePoint(b).distanceToSquared(e.pos))[0];}}if(e.bash&&e.attackCd<=0){e.attackCd=1;if(typeof forgedEnemyAttack!=='function'||!forgedEnemyAttack(e,e.bash)){e.bash.hp=(e.bash.hp??180)-e.d.dmg;if(e.bash.hp<=0)destroyStructure(e.bash);}}else if(distance<=range&&e.attackCd<=0&&Math.abs(goal.y-e.pos.y)<5&&(range<4||enemySees(e,{pos:goal}))){e.attackCd=e.type==='spitter'?1.8:1;if(typeof forgedEnemyAttack!=='function'||!forgedEnemyAttack(e,target))hurtFriendly(target,e.d.dmg);if(range>4)tracer(e.pos.clone().add(V3(0,1,0)),goal.clone().add(V3(0,1,0)),e.type==='spitter'?0x9ac754:0x80dce9);if(e.type==='frostling'&&target===G.player)G.player.chillUntil=G.time+2;if(e.type==='spitter')target.poisonUntil=G.time+3;if(e.type==='bomber'){for(const o of [G.player,...economy().workers])if(o.pos.distanceTo(e.pos)<4)hurtFriendly(o,15);effectRing(e.pos,4,0xffaa44);damage(e,e.hp+1);}}}
 else if(e.d.spd){e.wanderT=(e.wanderT||0)-dt;if(e.wanderT<=0){e.wanderT=4+G.rng()*4;const a=G.rng()*6.28;e.wanderGoal=e.pos.clone().add(V3(Math.cos(a)*7,0,Math.sin(a)*7));e.wanderGoal.y=heightAt(e.wanderGoal.x,e.wanderGoal.z);}enemyAdvance(e,e.wanderGoal,dt*.4,budget);}
 if(e.d.heal)for(const ally of G.enemies)if(!ally.dead&&!ally.rift&&ally.pos.distanceTo(e.pos)<5)ally.hp=Math.min(ally.maxHp,ally.hp+e.d.heal*dt);
 }e.slowT=(e.slowT||0)-dt;if(e.slowT<=0)e.slow=0;if(e.burnT>0){e.burnT-=dt;damage(e,e.burn*dt);}e.mesh.position.copy(e.pos);e.hb.scale.x=Math.max(.001,e.hp/e.maxHp);e.hb.lookAt(camera.position);e.hitT=(e.hitT||0)-dt;e.body.material?.emissive?.setHex(e.hitT>0?0xffffff:0);e.prog=-e.pos.distanceTo(G.player.pos);}
 G.enemies=G.enemies.filter(e=>!e.dead);for(const s of G.sites){worldHealthBar(s,s.coreMesh,3.6);updateBar(s,s.coreHp,s.coreMax);}for(const o of [G.player,...economy().workers])if(o.poisonUntil>G.time)hurtFriendly(o,dt*2);
 const c=colony();c.spawnClock-=dt;if(c.spawnClock<=0){c.spawnClock=.5;for(let i=0;i<3&&G.enemies.length<220;i++){const p=randomWildPoint(G.rng()<.75);if(p)wildernessSpawn(p,monsterKinds[Math.floor(G.rng()*monsterKinds.length)]);}}if(canFinishAssault())waveCleared();updateCaravans(dt);
};
function createOutposts(){const c=colony();c.outposts??=[];if(c.outposts.length)return;for(let i=0;i<3;i++){const p=randomWildPoint(false);if(!p)continue;const out={id:i+1,pos:p.clone(),captured:false};c.outposts.push(out);spawnRift(p,{outpostId:out.id,scale:2});for(let j=0;j<3;j++){const q=p.clone().add(V3(Math.cos(j*2.1)*6,0,Math.sin(j*2.1)*6));q.y=heightAt(q.x,q.z);frontierSpawnAt(q,'watchtower',{outpostId:out.id,structureBuild:j===0?'house':'arrow'});}for(let j=0;j<5;j++)frontierSpawnAt(p.clone().add(V3(j+2,0,3)),'bulwark',{outpostId:out.id,scale:1.5});}}
function captureOutpost(out){if(out.captured||G.player.pos.distanceTo(out.pos)>8)return false;if(G.enemies.some(e=>!e.dead&&e.outpostId===out.id&&e.type!=='watchtower')){log('Destroy this settlement’s portal and its defenders first.');return false;}const [cx,cz]=worldToCell(out.pos),s={id:Math.max(0,...G.sites.map(o=>o.id))+1,r:SITE_R,core:[cx,cz],corePos:out.pos.clone(),coreHp:400,coreMax:400,gates:[],cells:[],status:'secured',wave:WAVES_PER_SITE,group:new THREE.Group(),routes:[],circular:true,wobble:{}};for(let x=Math.max(0,cx-s.r);x<=Math.min(WORLD-1,cx+s.r);x++)for(let z=Math.max(0,cz-s.r);z<=Math.min(WORLD-1,cz+s.r);z++)if(Math.hypot(x-cx,z-cz)<=s.r){s.cells.push([x,z]);if(!cellAt(x,z).site)cellAt(x,z).site=s.id;}G.sites.push(s);portalVisuals(s);out.captured=true;for(const e of G.enemies.filter(e=>!e.dead&&e.outpostId===out.id&&e.type==='watchtower')){const b=BUILDS.find(b=>b.id===e.structureBuild),[cx,cz]=worldToCell(e.pos),t={uid:colony().nextBuilding++,siteId:s.id,b,cx,cz,pos:e.pos.clone(),hp:e.hp,maxHp:e.maxHp,cd:0};t.mesh=towerMesh(b);t.mesh.position.copy(t.pos);G.world.add(t.mesh);G.towers.push(t);G.placedCount[b.id]=(G.placedCount[b.id]||0)+1;cellAt(cx,cz).tower=t;e.dead=true;G.world.remove(e.mesh);}rebuildCollision();createClaimNodes(s);settlementNotice('Settlement captured. Surviving buildings now belong to gate '+s.id);return true;}
function createCaravan(){const p=randomWildPoint(false);if(!p)return;const c={id:Math.floor(G.time)+1,pos:p,hp:180,maxHp:180,role:'ranger',stock:{logs:80,stone:60,ore:35,gateKits:2},escorts:[]};for(let i=0;i<3;i++)c.escorts.push({id:'merc'+i,pos:p.clone().add(V3(i-1,0,2)),hp:160,maxHp:160,role:i===0?'ranger':'knight'});colony().caravans=[...(colony().caravans||[]).filter(o=>o.settled),c];restoreCaravans();settlementNotice('A merchant caravan is traveling between settlements. Look for its gold banner.');}
function restoreCaravans(){for(const c of colony().caravans||[])for(const o of [c,...c.escorts]){if(o.mesh?.parent)continue;o.mesh=workerMesh(o.role);if(o===c){const banner=new THREE.Mesh(new THREE.BoxGeometry(.8,1,.06),new THREE.MeshStandardMaterial({color:0xe2bd65}));banner.position.set(0,2.5,0);o.mesh.add(banner);}o.mesh.position.copy(o.pos);G.world.add(o.mesh);}}
function updateCaravans(dt){const state=colony();state.merchantClock=(state.merchantClock??70)-dt;if(state.merchantClock<=0){state.merchantClock=300;if(!(state.caravans||[]).some(c=>c.hp>0&&!c.settled))createCaravan();}for(const c of state.caravans||[]){if(c.hp<=0){G.world.remove(c.mesh);for(const escort of c.escorts)G.world.remove(escort.mesh);continue;}const destinations=G.sites.filter(s=>s.coreHp>0);c.stop=(c.stop||0)-dt;const s=destinations[(c.destination||0)%Math.max(1,destinations.length)];if(s&&!c.settled&&c.stop<=0&&walkResident(c,s.corePos,7,dt)){c.stop=35;c.destination=(c.destination||0)+1;}for(const guard of c.escorts){if(guard.hp<=0){G.world.remove(guard.mesh);continue;}const e=G.enemies.find(e=>!e.dead&&!e.rift&&e.pos.distanceTo(c.pos)<14);if(e)strikeResident(guard,e,dt);else walkResident(guard,c.pos,2.5,dt);worldHealthBar(guard,guard.mesh,2.2);updateBar(guard,guard.hp,guard.maxHp);}worldHealthBar(c,c.mesh,3.2,0xe9c775);updateBar(c,c.hp,c.maxHp);}}
function tradeMerchant(c,kind,buy){if(c.hp<=0||c.pos.distanceTo(G.player.pos)>8)return false;const price={logs:2,stone:3,ore:6,gateKits:180}[kind];if(!price)return false;const eco=economy();if(buy){if(!c.stock[kind]||G.gold<price)return false;G.gold-=price;c.stock[kind]--;eco[kind]=(eco[kind]||0)+1;}else{if(!eco[kind])return false;eco[kind]--;G.gold+=Math.max(1,Math.floor(price*.5));c.stock[kind]=(c.stock[kind]||0)+1;}return true;}
const frontierNewRun=newRun;
newRun=function(...args){frontierNewRun(...args);const s=G.sites[0];if(s&&!s.innerFort)innerFort(s);for(const s of G.sites){s.coreMax=400;s.coreHp=400;}createOutposts();for(let i=0;i<65;i++){const p=randomWildPoint(false);if(p)wildernessSpawn(p,monsterKinds[i%monsterKinds.length]);}G.player.talents=[];G.site=null;G.phase='explore';};
const campaignRestore=restoreSave;
restoreSave=function(save){campaignRestore(save);for(const t of G.towers){t.hp??=180;t.maxHp??=180;if(t.b.id==='ramp'&&!t.construction)t.mesh.visible=false;if(t.edge&&t.b.id!=='barricade')t.mesh.position.copy(edgeStructurePoint(t));}for(const e of G.enemies)if(e.rift)drawRiftRoute(e);restoreCaravans();rebuildCollision();};window.bastion.restoreSave=restoreSave;

const campaignFound=foundSite;foundSite=function(){const count=G.sites.length;campaignFound();if(G.sites.length>count){const s=G.sites.at(-1);s.coreMax=s.coreHp=400;for(const line of s.routeLines||[])s.group.remove(line);s.routeLines=[];log('Portal ward active. Use E beside this gate to start its defense.');}};

const anchoredPush=pushEnemy;pushEnemy=function(e,from,power){if(e.rift||e.type==='watchtower')return;return anchoredPush(e,from,power);};
const campaignCollision=rebuildCollision;rebuildCollision=function(){if(G?.generatedBodies){G.generatedBodies=G.generatedBodies.filter(b=>!b.hostileStructure);for(const e of G.enemies||[])if(!e.dead&&(e.rift||e.type==='watchtower'))G.generatedBodies.push({x:e.pos.x,z:e.pos.z,y:e.pos.y,r:e.rift?1.15:.85,h:e.rift?3:2.8,source:e,hostileStructure:true});}campaignCollision();};
const chilledMovement=updatePlayer;updatePlayer=function(dt){const p=G.player,speed=p.speed;if(p.chillUntil>G.time)p.speed*=.65;try{chilledMovement(dt);}finally{p.speed=speed;}};

const campaignRoutes=refreshRoutes;refreshRoutes=function(){campaignRoutes();for(const s of G.sites){for(const line of s.routeLines||[])s.group.remove(line);s.routeLines=[];}for(const e of G.enemies)if(e.rift&&!e.dead)drawRiftRoute(e);};

const campaignValidation=validateSave;validateSave=function(s){campaignValidation(s);const p=s.state.player,c=s.state.economy?.settlement,vector=v=>Array.isArray(v?.$v)&&v.$v.length===3&&v.$v.every(Number.isFinite);if(p.talents&&(!Array.isArray(p.talents)||p.talents.length>6||new Set(p.talents).size!==p.talents.length||p.talents.some(id=>!['0-0','0-1','0-2','1-0','1-1','1-2'].includes(id))))throw Error('Invalid learned talents');if(c?.outposts&&(!Array.isArray(c.outposts)||c.outposts.length>200||c.outposts.some(o=>!vector(o.pos))))throw Error('Invalid monster settlements');if(c?.caravans&&(!Array.isArray(c.caravans)||c.caravans.length>(['rolling','plateaus'].includes(s.config.terrainMode)?2000:10)||c.caravans.some(o=>!vector(o.pos)||!Number.isFinite(o.hp)||!Array.isArray(o.escorts)||o.escorts.length>10||o.escorts.some(w=>!vector(w.pos)||!Number.isFinite(w.hp)))))throw Error('Invalid merchant caravan');for(const w of s.state.economy?.workers||[])if(w.priorities&&Object.values(w.priorities).some(n=>!Number.isInteger(n)||n<0||n>3))throw Error('Invalid labor priorities');};
