/* Portal frontier: weighted roads, obstruction-aware camera, and persistent settlers. */
class NavHeap {
 constructor(){this.items=[];} get length(){return this.items.length;}
 push(i,d){const a=this.items;let n=a.length;a.push([i,d]);while(n){const p=(n-1)>>1;if(a[p][1]<=d)break;a[n]=a[p];n=p;}a[n]=[i,d];}
 pop(){const a=this.items,first=a[0],last=a.pop();if(a.length){let n=0;while(n*2+1<a.length){let c=n*2+1;if(c+1<a.length&&a[c+1][1]<a[c][1])c++;if(a[c][1]>=last[1])break;a[n]=a[c];n=c;}a[n]=last;}return first;}
}
const orbitCamera=updateCamera;
updateCamera=function(){orbitCamera();if(!G||G.view==='top')return;camera.near=.06;const head=G.player.pos.clone().add(V3(0,1.55,0)),desired=camera.position.clone(),direction=desired.clone().sub(head),length=direction.length();
 if(length>.05){let safe=length;const steps=Math.ceil(length/.1),unit=direction.clone().normalize();for(let i=1;i<=steps;i++){const distance=Math.min(length,i*.1),p=head.clone().addScaledVector(unit,distance);let hit=p.y<heightAt(p.x,p.z)+.2;for(const body of nearbyBodies(p.x,p.z,1.4)){if(body.depleted||body.walkable||body.source?.taken)continue;const crown=body.source==='tree'&&p.y>body.y+1.2;const shape=crown?{...body,r:1.1}:body;if(p.y+.2>body.y&&p.y-.2<body.y+body.h&&overlapsBody(shape,p.x,p.z,.2)){hit=true;break;}}if(hit){safe=Math.max(.03,distance-.25);break;}}camera.position.copy(head).addScaledVector(unit,safe);}

 // Push the near plane out of solid footprints, including when the eye starts inside a prop.
 for(let n=0;n<3;n++)for(const raw of nearbyBodies(camera.position.x,camera.position.z,1.4)){const b=raw.source==='tree'&&camera.position.y>raw.y+1.2?{...raw,r:1.1}:raw;if(b.depleted||b.walkable||b.source?.taken)continue;if(camera.position.y<=b.y||camera.position.y>=b.y+b.h)continue;if(!overlapsBody(b,camera.position.x,camera.position.z,.18))continue;const d=V3(camera.position.x-b.x,0,camera.position.z-b.z);if(d.lengthSq()<.001)d.copy(cameraForward()).negate();d.normalize();if(b.hx!==undefined){const ex=b.hx+.2-Math.abs(camera.position.x-b.x),ez=b.hz+.2-Math.abs(camera.position.z-b.z);if(ex<ez)camera.position.x=b.x+Math.sign(d.x||1)*(b.hx+.2);else camera.position.z=b.z+Math.sign(d.z||1)*(b.hz+.2);}else{camera.position.x=b.x+d.x*(b.r+.2);camera.position.z=b.z+d.z*(b.r+.2);}}
 camera.position.y=Math.max(camera.position.y,heightAt(camera.position.x,camera.position.z)+.16);camera.updateProjectionMatrix();};
// Seeded terrain weights recover the original varied route character. Keep only turn points.
greedyRoute=function(from){const nav=G.navLarge;if(!nav)return [];let i=nav.nearest(cellToWorld(...from));const points=[];for(let count=0;i>=0&&count<4000;count++){const p=nav.point(i);p.y+=.08;points.push(p);if(nav.next[i]<0)break;i=nav.next[i];}return points.filter((p,i)=>{if(!i||i===points.length-1)return true;const a=p.clone().sub(points[i-1]).normalize(),b=points[i+1].clone().sub(p).normalize();return a.dot(b)<.999;});};
const routeSpawn=spawnEnemy;
spawnEnemy=function(type,gate,hp){const e=routeSpawn(type,gate,hp);e.routeId=gate??0;e.routeCursor=0;return e;};
pickNext=function(e){if(!G.site)return;const routes=G.site.routes||[],route=routes[(e.routeId||0)%Math.max(1,routes.length)];if(!route?.length){flowPick(e);return;}e.routeCursor=clamp(e.routeCursor||0,0,route.length-1);
 while(e.routeCursor<route.length-1&&e.pos.distanceTo(route[e.routeCursor])<.65)e.routeCursor++;
 let target=route[e.routeCursor].clone();target.y=heightAt(target.x,target.z);
 if(walkSegment(e.pos,target,e.d.size,'nav')){e.rejoin=null;e.target=target;e.next=worldToCell(target);return;}
 if(!e.rejoin||e.rejoinUntil<G.time){e.rejoin=[];const candidates=route.map((p,i)=>({p,i,d:p.distanceToSquared(e.pos)})).filter(v=>v.i>=Math.max(0,e.routeCursor-1)).sort((a,b)=>a.d-b.d);for(const v of candidates.slice(0,5)){const path=localRoute(e.pos,v.p,e.d.size);if(path.length&&path.at(-1).distanceTo(v.p)<e.d.size+1){e.rejoin=path;e.routeCursor=v.i;break;}}e.rejoinUntil=G.time+3;}
 while(e.rejoin?.length&&e.rejoin[0].distanceTo(e.pos)<.45)e.rejoin.shift();if(e.rejoin?.length){e.target=e.rejoin[0].clone();e.next=worldToCell(e.target);return;}
 const nav=e.d.size>.5?G.navLarge:(G.nav||(G.nav=makeFlow(.45))),at=nav?.nearest(e.pos),next=at>=0?nav.next[at]:-1;if(next>=0){e.target=nav.point(next);e.next=worldToCell(e.target);}else e.next=null;};
const roadRefresh=refreshRoutes;
refreshRoutes=function(){if(!G.site){G.dist={};return;}roadRefresh();for(const e of G.enemies){if(e.mode!=='siege')continue;e.next=null;e.rejoin=null;const route=G.site.routes[(e.routeId||0)%G.site.routes.length];if(route?.length){let near=0;for(let i=1;i<route.length;i++)if(route[i].distanceToSquared(e.pos)<route[near].distanceToSquared(e.pos))near=i;e.routeCursor=near;}}};
const routeUpdate=updateEnemies;
updateEnemies=function(dt){routeUpdate(dt);for(const e of G.enemies){if(e.dead)continue;if(e.lastRoadPos&&e.pos.distanceToSquared(e.lastRoadPos)<.001)e.stallTime=(e.stallTime||0)+dt;else{e.stallTime=0;e.lastRoadPos=e.pos.clone();}if(e.stallTime>1){e.next=null;e.rejoin=null;e.rejoinUntil=0;e.stallTime=0;} // Replan from the actual position, never teleport.
 // Soft separation allows crowds through gates without deadlocking one another.
 let sx=0,sz=0;for(const o of G.enemies){if(o===e||o.dead||Math.abs(o.pos.y-e.pos.y)>1)continue;const dx=e.pos.x-o.pos.x,dz=e.pos.z-o.pos.z,d=Math.hypot(dx,dz),r=(e.d.size+o.d.size)*.75;if(d>.001&&d<r){sx+=dx/d*(r-d);sz+=dz/d*(r-d);}}if(sx||sz)tryMove(e.pos,sx*dt,sz*dt);}};
const MOVE_INFO={
 knight:['Sweep enemies in front of you. A quick melee attack that pushes them back.','Brace for 3 seconds, reducing incoming damage by 80%. Use before a pack reaches you.','A wide shield strike with heavy knockback. Push enemies off ledges or away from your gate.','Strike every enemy within 4.5m, knocking the pack outward.','Restore 35 health, up to your maximum.','Charge up to 8m over 0.4 seconds. Hit and shove every enemy crossed; solid terrain stops you.'],
 ranger:['An arrow that pierces multiple enemies. Line up enemies along their route.','Fire five arrows in a fan. Best against a group at medium range.','A forceful arrow with heavy knockback. Aim across a ledge.','Place a 4.5m snare field for 7 seconds. Enemies inside move 70% slower.','For 6 seconds, piercing arrows and split shots deal 75% more damage.','Roll 6m with a brief evade window. Does not pass through solid terrain.'],
 pyromancer:['Launch an explosive fireball. Its impact burns nearby enemies.','Channel a cone of flames for 2 seconds. Repeated hits ignite the pack.','An outward blast with extreme knockback. Works well near high ledges.','Mark a 4.5m area. A meteor lands after 1.1 seconds, then leaves burning ground for 4 seconds.','Detonate the remaining burn on all burning enemies within 16m. Build up fire first.','Blink up to 7m to clear terrain, leaving a burning patch behind.']};
activateAbility=function(i){if(!G||G.buildMode||!ABILITIES[G.classId][i])return;if(combatMode()==='auto'){G.autoEnabled??=[true,false,false,false,false,false];G.autoEnabled[i]=!G.autoEnabled[i];G.uiNext=0;updateCombatUI();return;}G.activeAbility=i;if(combatMode()==='target'){if(ABILITIES[G.classId][i][2]==='area')G.armedArea=i;else castAbility(i);}else G.armedArea=null;G.uiNext=0;updateCombatUI();};
function updateAutomaticAbilities(){if(combatMode()!=='auto'||G.buildMode)return;G.autoEnabled??=[true,false,false,false,false,false];const enemy=nearestEnemy(40);for(let i=0;i<6;i++){if(!G.autoEnabled[i])continue;const a=ABILITIES[G.classId][i];if(a[2]==='heal'&&G.player.hp>=G.player.maxHp*.7)continue;if(a[2]!=='heal'&&(!enemy||enemy.pos.distanceTo(G.player.pos)>(a[4]||8)+enemy.d.size))continue;selectedEnemy=enemy;castAbility(i);}}
const DEFENSE_RECIPES={arrow:{logs:8,stone:2},brazier:{stone:8,ore:2},frost:{stone:8,ore:3},ballista:{logs:14,ore:4},guard:{logs:4,ore:3},spike:{logs:6},tar:{stone:5},barricade:{logs:4,stone:1},gale:{stone:10,ore:5}};
function economy(){if(!G.economy)G.economy={logs:100,stone:70,ore:30,fragments:0,gateKits:1,workers:[],nodes:[],ruins:[],harvestLevel:0,defenseLevel:0,choices:[],version:1};return G.economy;}
function canPay(recipe){const e=economy();return Object.entries(recipe).every(([k,n])=>(e[k]||0)>=n);}
function pay(recipe){if(!canPay(recipe))return false;const e=economy();for(const [k,n]of Object.entries(recipe))e[k]-=n;return true;}
function recipeText(recipe){return Object.entries(recipe).map(([k,n])=>n+' '+k).join(' · ');}
function gateMesh(hostile=false,ruined=false){const g=new THREE.Group(),color=ruined?0x74636c:hostile?0xec664e:0x62d9d3;const ring=new THREE.Mesh(new THREE.TorusGeometry(1.1,.21,8,32),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:ruined?.08:.5}));ring.position.y=1.6;g.add(ring);const base=new THREE.Mesh(new THREE.CylinderGeometry(1.35,1.5,.35,8),new THREE.MeshStandardMaterial({color:0x555967}));base.position.y=.17;g.add(base);if(!ruined){const veil=new THREE.Mesh(new THREE.CircleGeometry(.98,32),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:true,opacity:.4,depthWrite:false}));veil.position.y=1.6;g.add(veil);}g.traverse(o=>{if(o.isMesh)o.castShadow=true;});return g;}
function portalVisuals(site){G.world.add(site.group);site.coreMesh=gateMesh();site.coreMesh.position.copy(site.corePos);site.group.add(site.coreMesh);site.edge=new THREE.LineLoop(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:site.status==='secured'?0x65c8b4:0xd9b86b,transparent:true,opacity:.75}));site.group.add(site.edge);drawCaptureEdge(site);site.gatePos=site.gates.map(([x,z])=>{const p=cellToWorld(x,z);p.y=heightAt(p.x,p.z);return p;});if(site.status!=='secured')for(const p of site.gatePos){const gate=gateMesh(true);gate.position.copy(p);gate.lookAt(site.corePos.x,p.y,site.corePos.z);site.group.add(gate);}}
restoreSiteVisuals=portalVisuals;
coreReason=function(p){const [x,z]=worldToCell(p);if(!inGrid(x,z))return 'Choose generated terrain';if(G.sites.some(s=>s.corePos.distanceTo(p)<2.5))return 'A portal already occupies this position';if(economy().gateKits<1)return 'Craft a portal gate in the Settlement panel';return '';};
foundSite=function(){const p=G.player.pos.clone(),reason=coreReason(p);if(reason){log(reason);return;}const [cx,cz]=worldToCell(p),r=SITE_R+(has('surveyor')?2:0),oldSite=G.site,oldNav=G.navLarge,oldDist=G.dist,id=G.sites.length+1;
 const site={id,r,core:[cx,cz],corePos:cellToWorld(cx,cz),coreMax:40+(has('ironcore')?15:0),coreHp:40+(has('ironcore')?15:0),gates:[],cells:[],status:oldSite?'pending':'active',wave:0,group:new THREE.Group(),wobble:{},routes:[],circular:true};site.corePos.y=heightAt(site.corePos.x,site.corePos.z);
 for(let x=Math.max(0,cx-r);x<=Math.min(WORLD-1,cx+r);x++)for(let z=Math.max(0,cz-r);z<=Math.min(WORLD-1,cz+r);z++)if(Math.hypot(x-cx,z-cz)<=r)site.cells.push([x,z]);
 G.site=site;const dist=computeDist(),nav=G.navLarge;const rim=site.cells.filter(([x,z])=>Math.hypot(x-cx,z-cz)>=Math.min(r-1,Math.max(3,r*.65))&&dist[key(x,z)]!==undefined).filter(([x,z])=>{const q=cellToWorld(x,z);q.y=heightAt(q.x,q.z);const i=nav?.nearest(q);return i>=0&&walkSegment(q,nav.point(i),1.26,'nav');});
 const count=Math.min(4,2+Math.floor((id-1)/2)),base=(hashStr(G.seed+id)%628)/100;for(let i=0;i<count;i++){const angle=base+i*Math.PI*2/count;const options=rim.filter(q=>site.gates.every(g=>Math.hypot(g[0]-q[0],g[1]-q[1])>3)).sort((a,b)=>{const score=q=>Math.abs(Math.atan2(Math.sin(Math.atan2(q[1]-cz,q[0]-cx)-angle),Math.cos(Math.atan2(q[1]-cz,q[0]-cx)-angle)))+Math.abs(Math.hypot(q[0]-cx,q[1]-cz)-r)*.04;return score(a)-score(b);});if(options[0])site.gates.push(options[0]);}
 if(site.gates.length<2){G.site=oldSite;G.navLarge=oldNav;G.dist=oldDist;log('No two enemy approaches can reach this portal. Try nearby terrain.');return;}
 economy().gateKits--;G.sites.push(site);for(const [x,z]of site.cells)if(!G.cells[x][z].site)G.cells[x][z].site=id;G.cells[cx][cz].type='core';portalVisuals(site);if(oldSite){G.site=oldSite;G.dist=oldDist;}else{G.site=site;G.phase='build';}rebuildCollision();refreshRoutes();updateHud();log(oldSite?'Portal placed. Its defense is queued after the current claim.':'Portal opened: enemy gates are forming. Prepare, then press Enter.');};
secureSite=function(){const site=G.site;if(!site)return;site.status='secured';site.edge.material.color.setHex(0x65c8b4);for(const line of site.routeLines||[])site.group.remove(line);site.routeLines=[];for(const p of site.gatePos){const ruin={id:'gate-'+site.id+'-'+economy().ruins.length,siteId:site.id,pos:p.clone(),remaining:8};economy().ruins.push(ruin);}site.group.traverse(o=>{if(o.material?.color?.getHex()===0xec664e)o.material.color.setHex(0x74636c);});G.gold+=80+(has('salvage')?G.towers.filter(t=>cellAt(t.cx,t.cz)?.site===site.id).reduce((n,t)=>n+(t.paid??buildCost(t.b)),0):0);economy().logs+=20;economy().stone+=15;createClaimNodes(site);G.site=G.sites.find(s=>s.status==='pending')||null;if(G.site){G.site.status='active';G.phase='build';refreshRoutes();}else{G.phase='explore';G.dist={};}restoreEconomicMeshes();log('Claim secured. Summon workers; salvage enemy gates to craft your next portal.');updateHud();};
function claimAt(p){return G.sites.find(s=>s.status==='secured'&&Math.hypot(p.x-s.corePos.x,p.z-s.corePos.z)<=s.r*CELL);}
function createClaimNodes(site){const e=economy();if(e.nodes.some(n=>n.siteId===site.id))return;for(const b of G.generatedBodies||[]){if(!['tree','rock'].includes(b.source)||Math.hypot(b.x-site.corePos.x,b.z-site.corePos.z)>site.r*CELL-1)continue;const id=Math.round(b.x*100)+','+Math.round(b.z*100);if(e.nodes.some(n=>n.id===id))continue;e.nodes.push({id,siteId:site.id,kind:b.source==='tree'?'logs':hashStr(id)%3===0?'ore':'stone',pos:V3(b.x,b.y,b.z),remaining:b.source==='tree'?24:32,radius:b.r});}
 // Every claim has a small accessible supply deposit so an unlucky barren seed cannot stall progression.
 for(const kind of ['logs','stone','ore']){let made=0;for(let ring=3;ring<12&&!made;ring++)for(let i=0;i<16&&!made;i++){const p=site.corePos.clone().add(V3(Math.cos(i*Math.PI/8)*ring,0,Math.sin(i*Math.PI/8)*ring));p.y=heightAt(p.x,p.z);if(!e.nodes.some(n=>n.pos.distanceTo(p)<1)&&!blockedAt(p.x,p.z,p.y,.6)&&Math.abs(p.y-site.corePos.y)<.25){const last=localRoute(site.corePos.clone().add(V3(1.6,0,0)),p,.25);if(last.length){e.nodes.push({id:'cache-'+site.id+'-'+kind,siteId:site.id,kind,pos:p,remaining:40,radius:.5,cache:true});made++;}}}}
}
function workerMesh(job){const g=new THREE.Group(),color=job==='salvage'?0xb5a1df:job==='logs'?0x9fb779:job==='ore'?0xa5b5d8:0xb5a18a;const body=new THREE.Mesh(new THREE.CylinderGeometry(.23,.3,.9,6),new THREE.MeshStandardMaterial({color}));body.position.y=.6;const head=new THREE.Mesh(new THREE.SphereGeometry(.22,8,6),new THREE.MeshStandardMaterial({color:0xe3c7a0}));head.position.y=1.2;g.add(body,head);return g;}
function restoreEconomicMeshes(){const e=economy();for(const w of e.workers){if(!w.mesh){w.mesh=workerMesh(w.job);G.world.add(w.mesh);}w.mesh.position.copy(w.pos);}for(const n of [...e.nodes.filter(n=>n.cache),...e.ruins]){if(n.remaining<=0)continue;if(!n.mesh){n.mesh=n.kind?new THREE.Mesh(new THREE.DodecahedronGeometry(.45),new THREE.MeshStandardMaterial({color:n.kind==='logs'?0x9d7649:n.kind==='ore'?0x8f9ebe:0x8a8c8b})):gateMesh(true,true);n.mesh.position.copy(n.pos);G.world.add(n.mesh);}}}
function summonWorker(job,siteId){const e=economy(),site=G.sites.find(s=>s.id===Number(siteId)&&s.status==='secured');if(!site){log('Secure a portal claim before summoning workers');return false;}if(e.workers.filter(w=>w.siteId===site.id).length>=8){log('This claim supports eight workers');return false;}if(G.gold<20||!pay({logs:5})){log('A worker costs 20 gold and 5 logs');return false;}G.gold-=20;let p=null;for(let r=1.8;r<5&&!p;r+=.4)for(let i=0;i<16&&!p;i++){const q=site.corePos.clone().add(V3(Math.cos(i*Math.PI/8)*r,0,Math.sin(i*Math.PI/8)*r));q.y=heightAt(q.x,q.z);if(!blockedAt(q.x,q.z,q.y,.3)&&Math.abs(q.y-site.corePos.y)<.3)p=q;}if(!p){G.gold+=20;e.logs+=5;log('Make room beside the portal for a worker');return false;}e.workers.push({id:e.workers.length+1,siteId:site.id,job,pos:p,state:'seeking',cargo:0,targetId:null,work:0,path:[],retry:0});restoreEconomicMeshes();updateHud();return true;}
function workerRoute(w,to,radius=.6){let best=[];for(let i=0;i<12;i++){const a=i*Math.PI/6,p=to.clone().add(V3(Math.cos(a)*radius,0,Math.sin(a)*radius));p.y=heightAt(p.x,p.z);if(blockedAt(p.x,p.z,p.y,.27))continue;if(walkSegment(w.pos,p,.27,'nav'))return [p];const route=localRoute(w.pos,p,.27);if(route.length&&route.at(-1).distanceTo(p)<1&&(!best.length||route.length<best.length))best=route;}return best;}
function updateWorkers(dt){const eco=economy();for(const w of eco.workers){const site=G.sites.find(s=>s.id===w.siteId&&s.status==='secured');if(!site)continue;w.retry=(w.retry||0)-dt;
 if(w.path?.length){const p=w.path[0],delta=p.clone().sub(w.pos);delta.y=0;if(delta.length()<.2)w.path.shift();else{const step=Math.min(delta.length(),dt*3.5);delta.normalize().multiplyScalar(step);const q=w.pos.clone().add(delta);q.y=heightAt(q.x,q.z);if(walkSegment(w.pos,q,.25,'nav'))w.pos.copy(q);else{w.path=[];w.state=w.cargo?'returning':'seeking';w.retry=1;}}}
 else if(w.state==='returning'){if(w.pos.distanceTo(site.corePos)<3){eco[w.job==='salvage'?'fragments':w.job]+=w.cargo;w.cargo=0;if(w.nextJob){w.job=w.nextJob;w.nextJob=null;}w.state='seeking';w.retry=.5;}else if(w.retry<=0){w.path=workerRoute(w,site.corePos,2);w.retry=3;}}
 else if(w.state==='working'){const node=(w.job==='salvage'?eco.ruins:eco.nodes).find(n=>n.id===w.targetId);if(!node||node.remaining<=0){w.state=w.cargo?'returning':'seeking';continue;}w.work+=dt*(1+eco.harvestLevel*.3);if(w.work>=2){w.work=0;node.remaining--;w.cargo++;if(node.remaining===0&&node.mesh){G.world.remove(node.mesh);node.mesh=null;}if(w.cargo>=4||node.remaining<=0){w.state='returning';w.path=workerRoute(w,site.corePos,2);w.retry=2;}}}
 else if(w.state==='travel'){w.state='working';w.work=0;}
 else if(w.retry<=0){const options=(w.job==='salvage'?eco.ruins:eco.nodes).filter(n=>n.siteId===w.siteId&&n.remaining>0&&(w.job==='salvage'||n.kind===w.job)).sort((a,b)=>a.pos.distanceToSquared(w.pos)-b.pos.distanceToSquared(w.pos));w.retry=4;for(const n of options.slice(0,6)){const path=workerRoute(w,n.pos,(n.radius||1.3)+.6);if(path.length){w.path=path;w.targetId=n.id;w.state='travel';break;}}}
 if(w.mesh){w.mesh.position.copy(w.pos);if(w.path?.length)w.mesh.lookAt(w.path[0].x,w.pos.y,w.path[0].z);w.mesh.rotation.z=w.state==='working'?Math.sin(G.time*7)*.12:0;}}
}
const PORTAL_RECIPE={logs:20,stone:15,ore:5,fragments:8};
function craftPortal(){if(!pay(PORTAL_RECIPE)){log('Portal gate: '+recipeText(PORTAL_RECIPE));return false;}economy().gateKits++;updateHud();return true;}
function upgradeEconomy(kind){const e=economy(),level=e[kind]||0,recipe=kind==='harvestLevel'?{logs:20+level*10,stone:15+level*10}:{stone:25+level*15,ore:10+level*5};if(!pay(recipe)){log('Upgrade: '+recipeText(recipe));return false;}e[kind]++;updateHud();return true;}
const craftedPlace=place;
place=function(b,...args){if(b.core)return craftedPlace(b,...args);const recipe=DEFENSE_RECIPES[b.id]||{},before=G.towers.length;if(!canPay(recipe)){log(b.name+': '+recipeText(recipe));return;}craftedPlace(b,...args);if(G.towers.length>before){pay(recipe);G.towers.at(-1).materials={...recipe};}updateHud();};
const craftDmg=towerDmg;
towerDmg=function(t){return craftDmg(t)*(1+economy().defenseLevel*.15);};
const frontierUpdate=updatePlayer;
updatePlayer=function(dt){frontierUpdate(dt);updateAutomaticAbilities();updateWorkers(dt);if(G.time>(G.economyUiAt||0)){G.economyUiAt=G.time+.5;updateEconomyUI();}};
const frontierNew=newRun;
newRun=function(...args){frontierNew(...args);economy();G.autoEnabled=[true,false,false,false,false,false];updateEconomyUI();};
const frontierRestore=restoreSave;
restoreSave=function(...args){frontierRestore(...args);if(args[0]?.state?.economy?.version){for(let i=0;i<G.enemies.length;i++){const saved=args[0].enemies[i];if(saved)for(const k of ['next','target','routeCursor','rejoin','rejoinUntil'])if(saved[k]!==undefined)G.enemies[i][k]=unpack(saved[k]);else delete G.enemies[i][k];}}economy();for(const s of G.sites)if(s.status==='secured')createClaimNodes(s);restoreEconomicMeshes();applyHarvestedNodes();updateEconomyUI();};
window.bastion.restoreSave=restoreSave;
function applyHarvestedNodes(){let changed=false;const index=new Map((G.generatedBodies||[]).map(b=>[Math.round(b.x*100)+','+Math.round(b.z*100),b]));for(const n of economy().nodes){if(n.remaining>0||n.cache)continue;const body=index.get(n.id);if(!body||body.depleted)continue;body.depleted=true;changed=true;for(const part of body.draw||[]){part.mesh.setMatrixAt(part.index,new THREE.Matrix4().makeScale(0,0,0));part.mesh.instanceMatrix.needsUpdate=true;}}if(changed){rebuildCollision();if(G.site)refreshRoutes();}}
function updateEconomyUI(){if(!G||!document.getElementById('resourceStrip'))return;const e=economy();$('resourceStrip').textContent='Wood '+e.logs+'   Stone '+e.stone+'   Ore '+e.ore+'   Fragments '+e.fragments+'   Portal kits '+e.gateKits;
 const claims=G.sites.filter(s=>s.status==='secured'),select=$('workerClaim'),previous=select.value;if(select.dataset.ids!==claims.map(s=>s.id).join(',')){select.innerHTML=claims.length?claims.map(s=>'<option value="'+s.id+'">Claim '+s.id+'</option>').join(''):'<option value="">No secured claims yet</option>';select.dataset.ids=claims.map(s=>s.id).join(',');if(claims.some(s=>String(s.id)===previous))select.value=previous;}
 for(const job of ['logs','stone','ore','salvage'])$('summon-'+job).disabled=!claims.length||G.gold<20||e.logs<5;$('settlementSummary').textContent=claims.length?claims.length+' secured claims · '+e.workers.length+' workers · next defense '+G.wave:'Place portal 0 in build mode, then survive five waves to secure your first claim.';
 $('workerStatus').textContent=e.workers.length?e.workers.map(w=>'#'+w.id+' '+w.job+' — '+w.state+(w.cargo?' ('+w.cargo+' carried)':'')).join('\n'):'No workers summoned yet.';
 $('craftGate').textContent='Craft portal kit · '+recipeText(PORTAL_RECIPE);$('craftGate').disabled=!canPay(PORTAL_RECIPE);$('harvestUpgrade').textContent='Tools '+e.harvestLevel+' → '+(e.harvestLevel+1)+' · '+recipeText({logs:20+e.harvestLevel*10,stone:15+e.harvestLevel*10});$('defenseUpgrade').textContent='Fortifications '+e.defenseLevel+' → '+(e.defenseLevel+1)+' · '+recipeText({stone:25+e.defenseLevel*15,ore:10+e.defenseLevel*5});
 const rows=$('workerAssignments');if(rows.dataset.count!==String(e.workers.length)){rows.innerHTML=e.workers.map(w=>'<label>Worker '+w.id+' <select id="job'+w.id+'">'+['logs','stone','ore','salvage'].map(j=>'<option '+(w.job===j?'selected':'')+'>'+j+'</option>').join('')+'</select></label>').join('');rows.dataset.count=String(e.workers.length);for(const w of e.workers)$('job'+w.id).onchange=()=>{if(w.cargo){w.nextJob=$('job'+w.id).value;w.state='returning';w.path=[];}else{w.job=$('job'+w.id).value;w.path=[];w.state='seeking';}w.retry=0;};}
 applyHarvestedNodes();}
function showMoveTooltip(i){if(!G)return;const a=ABILITIES[G.classId][i],el=$('moveTooltip');el.innerHTML='<strong>'+a[0]+'</strong><div class="tooltip-meta">'+(a[4]?a[4]+'m range · ':'')+a[3]+'s cooldown</div><p>'+MOVE_INFO[G.classId][i]+'</p><small>'+(combatMode()==='auto'?'Click to '+(G.autoEnabled?.[i]?'disable':'enable')+' automatic use.':combatMode()==='free'?'Click or press '+(i+1)+' to select. Left mouse fires.':'Click or press '+(i+1)+' to activate.')+'</small>';el.classList.remove('hidden');const rect=$('ability'+i).getBoundingClientRect();el.style.left=Math.max(8,Math.min(innerWidth-300,rect.left))+'px';el.style.bottom=(innerHeight-rect.top+12)+'px';}
const frontierInstall=installIntegration;
installIntegration=function(){frontierInstall();const tooltip=document.createElement('div');tooltip.id='moveTooltip';tooltip.className='hidden';tooltip.setAttribute('role','tooltip');document.body.appendChild(tooltip);for(let i=0;i<6;i++){const button=$('ability'+i);button.onmouseenter=()=>showMoveTooltip(i);button.onfocus=()=>showMoveTooltip(i);button.onmouseleave=button.onblur=()=>tooltip.classList.add('hidden');}
 const micro=document.createElement('div');micro.id='microMenu';document.body.appendChild(micro);for(const id of ['saveRun','menuRun','buildMode','cycleView','missionPrimary','adminToggle'])micro.appendChild($(id));$('saveRun').textContent='Save';$('menuRun').textContent='Menu';$('cycleView').textContent='View · V';$('adminToggle').textContent='Testing · F2';
 const settlers=document.createElement('button');settlers.id='settlementToggle';settlers.textContent='Settlement';micro.appendChild(settlers);const panel=document.createElement('div');panel.id='settlementPanel';panel.className='hidden';panel.innerHTML='<header><h2>Portal settlement</h2><button id="closeSettlement">×</button></header><p id="settlementSummary"></p><h3>Summon workers</h3><p>20 gold + 5 logs each. Eight workers per secured claim. Workers walk to resources and carry them back.</p><select id="workerClaim"></select><div class="worker-actions">'+['logs','stone','ore','salvage'].map(j=>'<button id="summon-'+j+'">'+({logs:'Lumberjack',stone:'Quarry worker',ore:'Ore miner',salvage:'Gate salvager'})[j]+'</button>').join('')+'</div><pre id="workerStatus"></pre><details><summary>Reassign workers</summary><div id="workerAssignments"></div></details><h3>Craft & develop</h3><button id="craftGate"></button><button id="harvestUpgrade"></button><button id="defenseUpgrade"></button><p>Tools: +30% harvesting speed per level. Fortifications: +15% defense damage per level. Enemy gate ruins each hold 8 fragments.</p><p>Every portal starts five increasingly difficult waves. Secure land, salvage gates, choose relics, and expand. Additional portal defenses queue while one is active.</p>';document.body.appendChild(panel);const strip=document.createElement('div');strip.id='resourceStrip';document.body.appendChild(strip);
 settlers.onclick=()=>{panel.classList.toggle('hidden');updateEconomyUI();};$('closeSettlement').onclick=()=>panel.classList.add('hidden');for(const job of ['logs','stone','ore','salvage'])$('summon-'+job).onclick=()=>{summonWorker(job,$('workerClaim').value);updateEconomyUI();};$('craftGate').onclick=()=>{craftPortal();updateEconomyUI();};$('harvestUpgrade').onclick=()=>{upgradeEconomy('harvestLevel');updateEconomyUI();};$('defenseUpgrade').onclick=()=>{upgradeEconomy('defenseLevel');updateEconomyUI();};
 const resources=document.createElement('button');resources.textContent='Grant 100 resources + portal kit';resources.onclick=()=>{const e=economy();for(const k of ['logs','stone','ore','fragments'])e[k]+=100;e.gateKits++;updateEconomyUI();};$('adminPanel').querySelector('section').appendChild(resources);
};
const frontierUI=updateCombatUI;
updateCombatUI=function(){frontierUI();if(!G||!combatUIReady)return;for(let i=0;i<6;i++){const b=$('ability'+i);b.disabled=!!G.buildMode;b.classList.toggle('auto-enabled',combatMode()==='auto'&&(G.autoEnabled?.[i]??i===0));b.title='';}
 $('combatHint').textContent=G.armedArea!=null?'LMB: confirm area · Esc: cancel · RMB: camera':combatMode()==='auto'?'Click / 1–6: toggle automatic moves · C: targeting · B: build · Tab: target':combatMode()==='free'?'1–6: select · LMB: fire · RMB: camera · C: targeting · B: build':'LMB: select target · 1–6: cast · RMB: camera · Tab: cycle target';
 $('buildMode').textContent=G.buildMode?'Combat · B':'Build · B';if(G.buildMode&&!BUILDS[G.selected]?.core){const recipe=DEFENSE_RECIPES[BUILDS[G.selected]?.id];if(recipe&&!$('tip').textContent.includes('Materials:'))$('tip').textContent+=' · Materials: '+recipeText(recipe);}if($('waveTxt'))$('waveTxt').textContent=G.site?'Defense '+(G.site.wave+1)+'/5 · threat '+G.wave:G.sites.filter(s=>s.status==='secured').length+' claims secured';
};

const portalPreview=previewWall;
previewWall=function(){portalPreview();if(!G?.buildMode||!BUILDS[G.selected]?.core||!G.coreGhost)return;if(!G.coreGhost.userData.portal){const old=G.coreGhost;G.world.remove(old);old.geometry?.dispose();old.material?.dispose();G.coreGhost=gateMesh();G.coreGhost.userData.portal=true;G.coreGhost.position.copy(old.position);G.coreGhost.traverse(o=>{if(o.material){o.material.transparent=true;o.material.opacity=.45;o.material.depthWrite=false;}});G.world.add(G.coreGhost);}G.coreGhost.position.y=heightAt(G.coreGhost.position.x,G.coreGhost.position.z);};
const savedValidation=validateSave;
validateSave=function(s){savedValidation(s);const e=s.state.economy;if(!e)return;for(const k of ['logs','stone','ore','fragments','gateKits','harvestLevel','defenseLevel'])if(!Number.isFinite(e[k])||e[k]<0||e[k]>1e9)throw Error('Invalid settlement resource: '+k);const vec=p=>Array.isArray(p?.$v)&&p.$v.length===3&&p.$v.every(Number.isFinite);if(e.version!==1||!Array.isArray(e.workers)||e.workers.length>1600||e.workers.some(w=>!Number.isInteger(w.id)||!['logs','stone','ore','salvage'].includes(w.job)||!vec(w.pos)||!Number.isFinite(w.cargo)||w.cargo<0))throw Error('Invalid saved workers');for(const k of ['nodes','ruins'])if(!Array.isArray(e[k])||e[k].length>200000||e[k].some(n=>!vec(n.pos)||!Number.isFinite(n.remaining)||n.remaining<0))throw Error('Invalid saved resource sites');};
const materialSell=sell;
sell=function(...args){const before=G.towers.slice();materialSell(...args);for(const t of before)if(!G.towers.includes(t)&&t.materials)for(const [kind,n]of Object.entries(t.materials))economy()[kind]+=Math.floor(n*.6);updateEconomyUI();};
