/* Input, camera, placement previews and route recovery use independent state. */
let validatingPlacement=false;
const checkedPlace=place;
place=function(...args){validatingPlacement=true;try{return checkedPlace(...args);}finally{validatingPlacement=false;}};
const cameraForward=()=>V3(Math.sin(G.cameraYaw??G.player.yaw),0,Math.cos(G.cameraYaw??G.player.yaw));
updateCamera=function(){if(!G)return;const p=G.player.pos;G.cameraYaw??=G.player.yaw;G.cameraPitch??=-.18;const f=cameraForward(),pitch=G.cameraPitch,dir=V3(f.x*Math.cos(pitch),Math.sin(pitch),f.z*Math.cos(pitch)),distance=G.cameraDistance||8;
 if(G.view==='top'){camera.position.copy(p).addScaledVector(f,-distance*1.875).add(V3(0,distance*4.25,0));camera.lookAt(p);}
 else if(G.view==='third'){const focus=p.clone().add(V3(0,1.5,0));camera.position.copy(focus).addScaledVector(dir,-distance);camera.lookAt(focus);}
 else{camera.position.copy(p).add(V3(0,1.6,0));camera.lookAt(camera.position.clone().add(dir));}
 camera.far=Math.max(500,WORLD*CELL*1.2);camera.updateProjectionMatrix();sun.position.set(p.x+25,p.y+45,p.z+20);sun.target.position.copy(p);};
const cameraMovement=updatePlayer;
updatePlayer=function(dt){const P=G.player;G.cameraYaw??=P.yaw;G.cameraPitch??=-.18;
 const saved={};for(const k of ['KeyQ','KeyE','ArrowLeft','ArrowRight']){saved[k]=keys[k];keys[k]=false;}
 const cameraYaw=G.cameraYaw;if(G.view==='third'&&!keys.MouseR)G.cameraYaw=P.yaw;cameraMovement(dt);G.cameraYaw=cameraYaw;Object.assign(keys,saved);
 // A falling capsule is pushed out of scenery, including tree crowns, rather than embedded.
 for(const b of nearbyBodies(P.pos.x,P.pos.z,3)){if(b.depleted||b.source?.taken||b.walkable)continue;const tree=b.source==='tree',radius=tree?Math.max(b.r,P.pos.y>b.y+1.2?1.15:b.r):b.r;
 if(P.pos.y>=b.y+b.h||P.pos.y+1.6<=b.y||!overlapsBody({...b,r:radius},P.pos.x,P.pos.z,.35))continue;
 const d=V3(P.pos.x-b.x,0,P.pos.z-b.z);if(d.lengthSq()<.0001)d.copy(cameraForward());d.normalize();const extent=b.hx!==undefined?Math.max(b.hx,b.hz):radius;const end=V3(b.x+d.x*(extent+.37),P.pos.y,b.z+d.z*(extent+.37));if(!blockedAt(end.x,end.z,end.y,.35,1.6,P)){P.pos.x=end.x;P.pos.z=end.z;}}
 G.playerMesh.position.copy(P.pos);
 updateAbilityEffects(dt);updateAimPreview();};
const supportBeforeTrees=supportHeight;
supportHeight=function(pos,previousY){let floor=heightAt(pos.x,pos.z);for(const b of nearbyBodies(pos.x,pos.z,.05)){if(b.depleted||b.source==='tree'||b.source?.taken)continue;const top=b.y+b.h;if(previousY>=top-.05&&top>floor&&overlapsBody(b,pos.x,pos.z,.02))floor=top;}return floor;};
function activateAbility(i){if(!G||!ABILITIES[G.classId][i]||G.buildMode)return;G.activeAbility=i;if(combatMode()==='free'){G.armedArea=null;}else if(ABILITIES[G.classId][i][2]==='area'){G.armedArea=i;}else castAbility(i);G.uiNext=0;updateCombatUI();}
function clickWorld(){if(G.buildMode){const p=aimPoint();if(p)place(BUILDS[G.selected],...worldToCell(p),BUILDS[G.selected].wall?undefined:p);return;}if(G.armedArea!=null){const i=G.armedArea;G.groundCast=sceneAim(true).point;castAbility(i);G.groundCast=null;G.armedArea=null;return;}if(combatMode()==='target')selectTarget();else if(combatMode()==='free')castAbility(G.activeAbility||0);}
const oldAbilityAim=abilityAim;
abilityAim=function(){return G.groundCast?{point:G.groundCast.clone(),enemy:null}:oldAbilityAim();};
bindInput=function(){const c=$('c');const ready=()=>G&&!menuPaused&&G.phase!=='over'&&$('draft').classList.contains('hidden');
 addEventListener('keydown',e=>{if(e.target?.closest?.('input,select,textarea'))return;if(e.code==='F2'){e.preventDefault();toggleAdmin();return;}if(!ready())return;keys[e.code]=true;if(e.repeat)return;
 if(e.code==='Space'){e.preventDefault();jumpPlayer();}if(e.code==='Tab'){e.preventDefault();cycleTarget();}if(e.code==='Enter')startWave();if(e.code==='KeyV')setView(G.view==='top'?'third':G.view==='third'?'first':'top');if(e.code==='KeyB'){e.preventDefault();toggleBuildMode();}if(e.code==='KeyC')setCombatMode(['free','target','auto'][(['free','target','auto'].indexOf(combatMode())+1)%3]);
 const number=/^(?:Digit|Numpad)([0-9])$/.exec(e.code);if(number){const n=Number(number[1]);if(G.buildMode){G.selected=n===0?BUILDS.findIndex(b=>b.core):n-1;updateHud();}else if(n>=1&&n<=6)activateAbility(n-1);}
 if(e.code==='KeyT')cycleTarget();if(e.code==='KeyZ')setCombatMode(combatMode()==='auto'?'free':'auto');if(e.code==='Escape'){G.armedArea=null;keys={};document.exitPointerLock?.();}if(e.code==='KeyF'&&G.buildMode)clickWorld();if(e.code==='KeyX'&&G.buildMode){const p=aimPoint();if(p)sell(...worldToCell(p));}});
 c.addEventListener('pointerdown',e=>{if(e.button===2&&ready())c.setPointerCapture?.(e.pointerId);});c.addEventListener('pointerup',e=>{if(c.hasPointerCapture?.(e.pointerId))c.releasePointerCapture(e.pointerId);});c.addEventListener('lostpointercapture',()=>{keys.MouseR=false;});addEventListener('keyup',e=>keys[e.code]=false);
 addEventListener('mousemove',e=>{if(!G)return;mouseOverHud=!!e.target?.closest?.('button,input,select,#combatBar,#unitFrames,#runToolbar,#missionActions,#adminPanel,#hotbar');if(keys.MouseR&&ready()){G.cameraYaw=(G.cameraYaw??G.player.yaw)-e.movementX*.003;if(G.view!=='top')G.cameraPitch=clamp((G.cameraPitch??-.18)-e.movementY*.003,-1.35,1.35);}if(!mouseOverHud&&document.pointerLockElement!==c){mouse.x=e.clientX/innerWidth*2-1;mouse.y=1-e.clientY/innerHeight*2;}});
 c.addEventListener('mousedown',e=>{if(!ready())return;if(e.button===2){keys.MouseR=true;e.preventDefault();return;}if(e.button===0){keys.MouseL=!G.buildMode&&combatMode()==='free';clickWorld();}});
 addEventListener('mouseup',e=>{if(e.button===0)keys.MouseL=false;if(e.button===2){keys.MouseR=false;document.exitPointerLock?.();}});
 document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==c)keys.MouseR=false;});document.addEventListener('pointerlockerror',()=>{});
 addEventListener('contextmenu',e=>e.preventDefault());addEventListener('blur',()=>{keys={};});
 $('helpToggle').onclick=()=>{$('help').classList.toggle('min');};$('rerollBtn').onclick=()=>{if(G.gold>=15){G.gold-=15;openDraft();}};$('skipBtn').onclick=closeDraft;$('againBtn').onclick=()=>bridge.menu();$('sameSeedBtn').onclick=()=>{$('end').classList.add('hidden');newRun(G.classId,G.seed);};};
// Render the very same navigable polylines that enemies follow.
greedyRoute=function(from){const nav=G.navLarge;if(!nav)return [];let i=nav.nearest(cellToWorld(...from));const points=[];for(let n=0;i>=0&&n<1600;n++){const p=nav.point(i);p.y+=.08;points.push(p);if(nav.dist[i]===0)break;const next=nav.adjacent(i).filter(j=>nav.dist[j]<nav.dist[i]).sort((a,b)=>nav.dist[a]-nav.dist[b])[0];if(next===undefined)break;i=next;}return points;};
const flowPick=pickNext;
pickNext=function(e){if(!G.site)return;const routes=G.site.routes||[];let best=null;for(let ri=0;ri<routes.length;ri++){const route=routes[ri];for(let i=0;i<route.length;i++){const p=route[i],d=p.distanceToSquared(e.pos);if(!best||d<best.d)best={ri,i,p,d};}}
 if(!best){flowPick(e);return;}const route=routes[best.ri];if(best.d<1.5*1.5){let i=best.i;while(i<route.length-1&&route[i].distanceTo(e.pos)<1.1)i++;const p=route[i].clone();p.y=heightAt(p.x,p.z);if(walkSegment(e.pos,p,e.d.size,'nav')){e.target=p;e.next=worldToCell(p);e.rejoin=null;return;}}
 if(!e.rejoin||e.rejoinUntil<G.time){const candidates=routes.flatMap(r=>r.filter((_,i)=>i%4===0)).sort((a,b)=>a.distanceToSquared(e.pos)-b.distanceToSquared(e.pos));e.rejoin=[];for(const p of candidates.slice(0,8)){if(walkSegment(e.pos,p,e.d.size,'nav')){e.rejoin=[p.clone()];break;}const path=localRoute(e.pos,p,e.d.size);if(path.length){e.rejoin=path;break;}}e.rejoinUntil=G.time+4;}
 while(e.rejoin?.length&&e.rejoin[0].distanceTo(e.pos)<.45)e.rejoin.shift();if(e.rejoin?.length){e.target=e.rejoin[0].clone();e.target.y=heightAt(e.target.x,e.target.z);e.next=worldToCell(e.target);}else flowPick(e);};
BUILDS.push({id:'core',name:'Portal gate',cost:0,range:SITE_R*CELL,color:0xeacb83,core:true});
function selectCore(){if(!G||menuPaused)return;G.buildMode=true;G.armedArea=null;G.uiNext=0;G.selected=BUILDS.findIndex(b=>b.core);keys={};document.exitPointerLock?.();updateHud();}
function coreReason(p){if(G.phase!=='explore')return 'Secure the current bastion before placing another';const [x,z]=worldToCell(p),c=cellAt(x,z);if(!c||x<SITE_R+2||z<SITE_R+2||x>=WORLD-SITE_R-2||z>=WORLD-SITE_R-2)return 'Move farther from the world edge';const r=SITE_R+(has('surveyor')?2:0);if(!free(x,z))return 'The core needs clear ground';if(G.sites.some(s=>Math.max(Math.abs(s.core[0]-x),Math.abs(s.core[1]-z))<s.r+r+2))return 'Another bastion already claims this ground';if(G.lairs.some(l=>Math.hypot(l.cell[0]-x,l.cell[1]-z)<r+4))return 'Too close to an enemy camp';if(c.ramp||blockedAt(p.x,p.z,p.y,1.1,2.4,null,true))return 'The core needs clear, flat ground';if(p.distanceTo(G.player.pos)<1.6)return 'Move clear of the core footprint';return '';}
const ordinaryPlacement=place,ordinaryCanPlace=canPlace;
canPlace=function(b,x,z,p){return b.core?!coreReason(cellToWorld(x,z)):ordinaryCanPlace(b,x,z,p);};
place=function(b,x,z,p){if(!b.core)return ordinaryPlacement(b,x,z,p);const point=cellToWorld(x,z);point.y=heightAt(point.x,point.z);const reason=coreReason(point);if(reason){log(reason);return;}const player=G.player.pos.clone();G.player.pos.copy(point);try{foundSite();}finally{G.player.pos.copy(player);G.playerMesh.position.copy(player);}updateHud();};
const previewStructures=previewWall;
previewWall=function(){if(G?.capturePreview)G.capturePreview.visible=false;if(G?.coreGhost)G.coreGhost.visible=false;if(G?.buildMode&&BUILDS[G.selected]?.core){G.cursor.visible=false;G.rangeRing.visible=false;if(G.wallOutline)G.wallOutline.visible=false;const p=aimPoint();if(!p)return;const q=cellToWorld(...worldToCell(p));q.y=heightAt(q.x,q.z);if(!G.capturePreview){G.capturePreview=makePreview((SITE_R+(has('surveyor')?2:0))*CELL,0xeacb83);G.world.add(G.capturePreview);}G.capturePreview.visible=true;G.capturePreview.position.copy(q).add(V3(0,.12,0));const vertices=G.capturePreview.geometry.attributes.position;for(let i=0;i<vertices.count;i++)vertices.setZ(i,heightAt(q.x+vertices.getX(i),q.z-vertices.getY(i))-q.y);vertices.needsUpdate=true;G.capturePreview.geometry.computeBoundingSphere();if(!G.coreGhost){G.coreGhost=new THREE.Mesh(new THREE.OctahedronGeometry(.9),new THREE.MeshBasicMaterial({color:0xeacb83,transparent:true,opacity:.65}));G.world.add(G.coreGhost);}G.coreGhost.visible=true;G.coreGhost.position.copy(q).add(V3(0,1.6,0));G.capturePreview.material.color.setHex(coreReason(q)?0xc25343:0xeacb83);$('tip').textContent=coreReason(q)||'Portal gate · 1 kit · claims '+Math.round(SITE_R*CELL)+'m radius · click/LMB place';return;}previewStructures();};
function makePreview(radius,color){const m=new THREE.Mesh(new THREE.RingGeometry(radius*.96,radius,80),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;return m;}
function updateAimPreview(){if(G.aoePreview)G.aoePreview.visible=false;if(G.buildMode)return;const i=G.armedArea??G.activeAbility??0,a=ABILITIES[G.classId][i];if(!a||!['area','nova','cone','melee'].includes(a[2]))return;const armed=G.armedArea!=null;if(combatMode()!=='free'&&!armed)return;const radius=a[2]==='area'?4.5:a[4];if(!G.aoePreview){G.aoePreview=makePreview(1,0x74d8eb);G.world.add(G.aoePreview);}if(G.aoePreview.userData.kind!==a[2]){G.aoePreview.geometry.dispose();const arc=['cone','melee'].includes(a[2])?Math.acos(.2)*2:Math.PI*2;G.aoePreview.geometry=new THREE.RingGeometry(.08,1,64,1,-arc/2,arc);G.aoePreview.material.opacity=.25;G.aoePreview.userData.kind=a[2];}G.aoePreview.rotation.z=['cone','melee'].includes(a[2])?Math.atan2(abilityAim().point.z-G.player.pos.z,abilityAim().point.x-G.player.pos.x)*-1:0;const p=a[2]==='area'?(armed?sceneAim(true):abilityAim()).point.clone():G.player.pos.clone();const offset=p.clone().sub(G.player.pos);if(offset.length()>a[4])p.copy(G.player.pos).add(offset.normalize().multiplyScalar(a[4]));p.y=heightAt(p.x,p.z)+.12;G.aoePreview.position.copy(p);G.aoePreview.scale.setScalar(radius);G.aoePreview.visible=true;}
const revisedUI=updateCombatUI;
updateCombatUI=function(){revisedUI();if(!combatUIReady||!G)return;for(let i=0;i<6;i++){$('ability'+i).classList.toggle('active',i===(G.activeAbility||0));if(combatMode()==='free')$('ability'+i).disabled=!!G.buildMode;}
 $('combatHint').textContent=combatMode()==='free'?'1–6 / click: select move · LMB: fire · RMB drag: camera':combatMode()==='target'?'LMB: select enemy · 1–6 / click: cast · AoE: click ground to confirm · RMB: camera':'Auto attack · 1–6: cast · RMB drag: camera';
 if(G.armedArea!=null)$('combatHint').textContent='Choose the highlighted area with LMB · Esc cancels · RMB rotates camera';};
// Each class has a different combat loop: melee guard, mobile archery, delayed fire zones.
ABILITIES.knight=[['Cleave','⚔','melee',.55,3,1,3],['Shield guard','▣','guard',8,0,0,0],['Shield bash','▰','cone',5,4,1.2,20],['Whirlwind','✺','nova',8,4.5,1.5,8],['Rally','✚','heal',18,0,35,0],['Charging strike','»','charge',7,8,1.5,18]];
ABILITIES.ranger=[['Piercing arrow','➶','piercing',.65,38,1,2],['Split shot','⋔','spread',3,30,.85,3],['Gust arrow','↝','pushShot',4,30,1.1,22],['Snare field','⌗','area',9,26,1,0],['Steady focus','◎','focus',14,0,0,0],['Evasive roll','»','roll',5,6,0,0]];
ABILITIES.pyromancer=[['Firebolt','✹','fireShot',.8,28,1,3],['Flamethrower','♨','flames',5,7,.5,1],['Blast wave','✺','nova',6,5,1.4,22],['Meteor storm','☄','area',10,28,2.8,13],['Combustion','✦','combust',12,16,2,5],['Cinder blink','»','blink',7,7,1,0]];
const basicCast=castAbility;
castAbility=function(i){if(!G||menuPaused||G.buildMode||G.player.dead>0||G.phase==='over'||!$('draft').classList.contains('hidden'))return false;const a=ABILITIES[G.classId][i];if(!a||(G.abilityCds?.[i]||0)>0)return false;const type=a[2],P=G.player,aim=abilityAim(),dir=aim.point.clone().sub(shotOrigin()).normalize();let custom=['guard','charge','piercing','spread','focus','roll','flames','combust','blink'].includes(type)||(type==='area'&&G.classId!=='knight');
 if(!custom){const ok=basicCast(i);if(ok)addMoveAnimation(type,P.pos.clone(),dir,a[4],G.classId==='pyromancer'?0xff7b25:0xc5e6ee);return ok;}
 if(combatMode()==='target'&&['piercing','spread','charge','flames'].includes(type)&&(!livingTarget()||livingTarget().pos.distanceTo(P.pos)>a[4]+livingTarget().d.size)){log('Select an enemy within range');return false;}
 G.abilityCds??=[];G.abilityCds[i]=G.admin?.noCooldown?0:a[3];G.skills??=[];const color=G.classId==='pyromancer'?0xff7828:G.classId==='ranger'?0x8fe4ab:0xabcdf5;
 if(type==='guard'){G.guardUntil=G.time+3;effectRing(P.pos,1.5,0xaacfff);}
 if(type==='focus'){G.focusUntil=G.time+6;effectRing(P.pos,1.6,0x9eecc3);}
 if(type==='charge'||type==='roll'){const d=V3(dir.x,0,dir.z).normalize();G.skills.push({type,pos:P.pos.clone(),dir:d,left:.4,speed:a[4]/.4,hit:new Set(),dmg:P.melee*a[5],push:a[6]});if(type==='roll')P.hurtT=.5;}
 if(type==='blink'){const from=P.pos.clone();let end=from.clone();for(let n=1;n<=28;n++){const p=from.clone().addScaledVector(V3(dir.x,0,dir.z).normalize(),n*.25);p.y=heightAt(p.x,p.z);if(Math.abs(p.y-from.y)<4&&!blockedAt(p.x,p.z,p.y,.35,1.65,P))end=p;}P.pos.copy(end);G.skills.push({type:'firezone',pos:from,left:3,tick:0,radius:2,dmg:P.ranged*.3});effectRing(end,2,color);}
 if(type==='piercing'||type==='spread'){for(const angle of type==='spread'?[-.22,-.11,0,.11,.22]:[0]){const d=dir.clone().applyAxisAngle(V3(0,1,0),angle),p=shotOrigin(),mesh=new THREE.Mesh(new THREE.ConeGeometry(.09,.8,5),new THREE.MeshBasicMaterial({color}));mesh.quaternion.setFromUnitVectors(V3(0,1,0),d);mesh.position.copy(p);G.world.add(mesh);G.bolts.push({pos:p,mesh,vel:d.multiplyScalar(40),dmg:P.ranged*a[5]*(G.focusUntil>G.time?1.75:1),life:a[4]/40,pierce:type==='piercing',knock:a[6]});}}
 if(type==='area'){const p=aim.point.clone(),d=p.clone().sub(P.pos);if(d.length()>a[4])p.copy(P.pos).add(d.normalize().multiplyScalar(a[4]));p.y=heightAt(p.x,p.z);G.skills.push({type:G.classId==='ranger'?'snare':'meteor',pos:p,left:G.classId==='ranger'?7:1.1,tick:0,radius:4.5,dmg:P.ranged*a[5]});effectRing(p,4.5,color);}
 if(type==='flames')G.skills.push({type:'flames',pos:P.pos.clone(),dir:V3(dir.x,0,dir.z).normalize(),left:2,tick:0,radius:7,dmg:P.ranged*.5});
 if(type==='combust'){for(const e of G.enemies)if(!e.dead&&e.burnT>0&&e.pos.distanceTo(P.pos)<16){hitEnemy(e,P.ranged*2+e.burnT*e.burn,P.pos,5);e.burnT=0;effectRing(e.pos,1.5,color);}}
 addMoveAnimation(type,P.pos.clone(),dir,a[4]||2,color);G.uiNext=0;return true;};
const guardedHit=playerHit;
playerHit=function(n){guardedHit(G.guardUntil>G.time?n*.2:n);};
function addMoveAnimation(type,pos,dir,range,color){const radius=Math.min(range||2,5),arc=['melee','cone'].includes(type)?Math.PI*.85:Math.PI*2;const m=new THREE.Mesh(new THREE.RingGeometry(radius*.7,radius,32,1,-arc/2,arc),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.75,side:THREE.DoubleSide,depthWrite:false}));m.rotation.set(-Math.PI/2,0,Math.atan2(dir.x,dir.z)-Math.PI/2);m.position.copy(pos).add(V3(0,.7,0));G.world.add(m);G.moveAnimations??=[];G.moveAnimations.push({mesh:m,left:.4,total:.4,type});}
function updateAbilityEffects(dt){for(const anim of G.moveAnimations||[]){anim.left-=dt;anim.mesh.material.opacity=Math.max(0,anim.left/anim.total*.7);anim.mesh.scale.setScalar(1+(1-anim.left/anim.total)*.3);anim.mesh.rotation.z+=dt*2;if(anim.left<=0){G.world.remove(anim.mesh);anim.mesh.geometry.dispose();anim.mesh.material.dispose();}}G.moveAnimations=(G.moveAnimations||[]).filter(a=>a.left>0);
 for(const s of G.skills||[]){s.left-=dt;s.tick=(s.tick||0)-dt;if(['charge','roll'].includes(s.type)){s.hit??=new Set();tryMove(G.player.pos,s.dir.x*s.speed*dt,s.dir.z*s.speed*dt);if(s.type==='charge')for(const e of G.enemies)if(!e.dead&&!s.hit.has(e)&&e.pos.distanceTo(G.player.pos)<2.5){s.hit.add(e);hitEnemy(e,s.dmg,G.player.pos,s.push);}G.playerMesh.rotation.x=s.type==='roll'?Math.sin((.4-s.left)/.4*Math.PI)*.9:0;}
 if(s.type==='meteor'){if(!s.mesh){s.mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(.9),new THREE.MeshBasicMaterial({color:0xff7922}));G.world.add(s.mesh);}s.mesh.position.copy(s.pos).add(V3(0,Math.max(0,s.left)*15,0));if(s.left<=0){G.world.remove(s.mesh);s.mesh.geometry.dispose();s.mesh.material.dispose();for(const e of G.enemies)if(!e.dead&&e.pos.distanceTo(s.pos)<s.radius)hitEnemy(e,s.dmg,s.pos,15);effectRing(s.pos,s.radius,0xff7e24);G.skills.push({type:'firezone',pos:s.pos.clone(),left:4,tick:0,radius:4.5,dmg:s.dmg*.12});}}
 if(['snare','firezone','flames'].includes(s.type)&&s.tick<=0){s.tick=.3;const p=s.type==='flames'?G.player.pos:s.pos;effectRing(p,s.radius,s.type==='snare'?0x88d9a5:0xf78a3b);for(const e of G.enemies){if(e.dead||e.pos.distanceTo(p)>s.radius+e.d.size)continue;if(s.type==='flames'&&e.pos.clone().sub(p).normalize().dot(s.dir)<.8)continue;if(s.type==='snare'){e.slow=.7;e.slowT=.6;}else{hitEnemy(e,s.dmg,p,0);e.burn=4;e.burnT=3;}}}}
 G.skills=(G.skills||[]).filter(s=>s.left>0);if(!G.skills.some(s=>s.type==='roll'))G.playerMesh.rotation.x=0;}
const radiusFound=foundSite;
function drawCaptureEdge(site){const pts=[];for(let i=0;i<128;i++){const a=i/128*Math.PI*2,x=site.corePos.x+Math.cos(a)*site.r*CELL,z=site.corePos.z+Math.sin(a)*site.r*CELL;pts.push(V3(x,heightAt(x,z)+.15,z));}site.edge.geometry.dispose();site.edge.geometry=new THREE.BufferGeometry().setFromPoints(pts);}
foundSite=function(...args){const before=G.sites.length;radiusFound(...args);if(G.sites.length>before){G.site.circular=true;drawCaptureEdge(G.site);clearObstructingGatePosts();}};
const radiusRestore=restoreSave;
restoreSave=function(...args){radiusRestore(...args);for(const s of G.sites)if(s.circular)drawCaptureEdge(s);clearObstructingGatePosts();};
window.bastion.restoreSave=restoreSave;

function clearObstructingGatePosts(){if(!G.site)return;const blocked=G.site.gates.filter(g=>G.dist[key(...g)]===undefined).map(g=>cellToWorld(...g));if(!blocked.length)return;G.generatedBodies=G.generatedBodies.filter(b=>{if(b.source!=='gate'||!blocked.some(p=>Math.hypot(b.x-p.x,b.z-p.z)<3))return true;b.postMesh?.parent?.remove(b.postMesh);return false;});rebuildCollision();refreshRoutes();}
