/* Settlement frontier: persistent residents, construction orders and a living wilderness. */
const SETTLEMENT_BUILDS=[
 {id:'house',name:'Homestead',category:'Housing',cost:65,materials:{logs:24,stone:10},work:24,description:'Beds for 6 residents. Recruits a laborer at its gate every 90 seconds for 15 gold.',color:0xbe9d6f},
 {id:'barracks',name:'Warrior lodge',category:'Training',cost:90,materials:{logs:25,stone:20,ore:8},work:35,train:'knight',description:'Train a laborer as a durable melee warden. 30s, 35 gold and 5 ore.',color:0xa57459},
 {id:'range',name:'Ranger school',category:'Training',cost:90,materials:{logs:35,stone:10,ore:5},work:35,train:'ranger',description:'Train a laborer as a ranged defender. 30s, 35 gold and 5 ore.',color:0x74966b},
 {id:'academy',name:'Ember academy',category:'Training',cost:120,materials:{logs:15,stone:30,ore:15},work:45,train:'pyromancer',description:'Train a laborer to hurl explosive fire. 30s, 35 gold and 5 ore.',color:0xa96b79},
 {id:'mine',name:'Mine',category:'Production',cost:85,materials:{logs:20,stone:15,ore:5},work:30,produce:'ore',description:'One assigned laborer produces 1 ore and 2 stone every 10 seconds. No natural node is consumed.',color:0x92999a},
 {id:'treefarm',name:'Tree farm',category:'Production',cost:75,materials:{logs:20,stone:8},work:28,produce:'logs',description:'One assigned laborer tends planted trees, yielding 3 wood every 10 seconds.',color:0x78956a}
];
for(const b of SETTLEMENT_BUILDS){b.blocks=true;b.settlement=true;b.range=0;BUILDS.push(b);DEFENSE_RECIPES[b.id]=b.materials;}
BUILDS.find(b=>b.id==='guard').retired=true;
const UNLOCK_LEVELS=[1,2,3,5,7,9];
let baseProvisioning=false,worldRestoreInProgress=false,settlementUiAt=0;
function colony(){const e=economy();e.settlement??={version:1,nextNpc:1,nextBuilding:1,spawnClock:0,eventClock:55,discoveries:[],notices:[],category:'Defenses',day:0};return e.settlement;}
function settlementNotice(message){const list=colony().notices;list.unshift(message);list.length=Math.min(8,list.length);log(message);}
function gateNear(p,r=10){return G.sites.filter(s=>s.coreHp>0&&s.corePos.distanceTo(p)<=r).sort((a,b)=>a.corePos.distanceToSquared(p)-b.corePos.distanceToSquared(p))[0];}
function noSpawnAt(p){return G.sites.some(s=>s.coreHp>0&&Math.hypot(p.x-s.corePos.x,p.z-s.corePos.z)<(s.status==='secured'?s.r*CELL:6));}
function gateArrival(site){for(let r=2;r<6;r+=.7)for(let i=0;i<16;i++){const p=site.corePos.clone().add(V3(Math.cos(i*Math.PI/8)*r,0,Math.sin(i*Math.PI/8)*r));p.y=heightAt(p.x,p.z);if(!blockedAt(p.x,p.z,p.y,.4,1.6,'nav')&&Math.abs(p.y-site.corePos.y)<.6&&!economy().workers.some(w=>w.pos.distanceTo(p)<.8)&&G.player.pos.distanceTo(p)>.65)return p;}return null;}
function housing(siteId){return 2+G.towers.filter(t=>t.b.id==='house'&&!t.construction&&t.siteId===siteId).length*6;}
function residents(siteId){return economy().workers.filter(w=>w.siteId===siteId);}
function addResident(site,role='laborer'){const pos=gateArrival(site);if(!pos)return null;const w={id:colony().nextNpc++,siteId:site.id,job:'laborer',role,pos,hp:role==='knight'?120:role==='laborer'?60:80,maxHp:role==='knight'?120:role==='laborer'?60:80,state:'idle',cargo:0,path:[],retry:0,work:0};w.mesh=workerMesh('logs');w.mesh.children[0].material.color.setHex(({laborer:0xbba579,knight:0x809fb4,ranger:0x729e70,pyromancer:0xc87c54})[role]);G.world.add(w.mesh);w.mesh.position.copy(pos);economy().workers.push(w);return w;}
// Recruitment comes from houses. Gate menus only transfer residents that already exist.
summonWorker=function(){log('Houses recruit laborers. Use a portal to transfer existing residents.');return false;};
function transferResident(w,destination){const origin=G.sites.find(s=>s.id===w.siteId);if(!origin||origin.id===destination.id||!gateNear(G.player.pos)||G.player.pos.distanceTo(destination.corePos)>10){log('Stand beside the destination portal');return false;}if(w.pos.distanceTo(origin.corePos)>10){log('The resident must return to their source gate first');return false;}if(residents(destination.id).length>=housing(destination.id)){log('Build more housing at the destination');return false;}const p=gateArrival(destination);if(!p)return false;commandWorker(w,'stay');w.siteId=destination.id;w.staffId=null;w.pos.copy(p);w.mesh.position.copy(p);w.command=null;w.state='idle';effectRing(p,2,0x78d9d0);settlementNotice('Resident '+w.id+' arrived through gate '+destination.id);return true;}
const largerRadius=buildRadius;
buildRadius=function(b){return b.settlement?(b.id==='house'?1.5:1.8):largerRadius(b);};
const olderTowerMesh=towerMesh;
towerMesh=function(b){if(!b.settlement)return olderTowerMesh(b);const group=new THREE.Group(),wood=new THREE.MeshStandardMaterial({color:b.color,roughness:.92}),stone=new THREE.MeshStandardMaterial({color:0x777f7d,roughness:1}),roof=new THREE.MeshStandardMaterial({color:b.train==='pyromancer'?0x684c74:0x53696c,roughness:.9});const add=(geometry,material,x,y,z)=>{const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;group.add(m);return m;};add(new THREE.BoxGeometry(2.8,.35,2.8),stone,0,.17,0);
 if(b.id==='treefarm'){for(let i=0;i<4;i++){const x=(i%2-.5)*1.6,z=(Math.floor(i/2)-.5)*1.6;add(new THREE.CylinderGeometry(.09,.13,1.2,6),wood,x,.7,z);add(new THREE.SphereGeometry(.6,8,6),new THREE.MeshStandardMaterial({color:0x688650}),x,1.7,z);}}
 else if(b.id==='mine'){add(new THREE.DodecahedronGeometry(1.5,0),stone,0,.7,0);add(new THREE.BoxGeometry(1.25,1.4,.12),new THREE.MeshStandardMaterial({color:0x202629}),0,.8,1.25);for(const x of [-.8,.8])add(new THREE.BoxGeometry(.18,1.8,.2),wood,x,.95,1.35);add(new THREE.BoxGeometry(1.8,.2,.2),wood,0,1.8,1.35);}
 else{add(new THREE.BoxGeometry(2.3,1.7,2.1),wood,0,1.2,0);const top=add(new THREE.ConeGeometry(1.95,1.3,4),roof,0,2.7,0);top.rotation.y=Math.PI/4;add(new THREE.BoxGeometry(.65,1.25,.08),new THREE.MeshStandardMaterial({color:0x45382d}),0,.9,1.08);for(const x of [-.78,.78])add(new THREE.BoxGeometry(.35,.45,.09),new THREE.MeshStandardMaterial({color:0xe7c477,emissive:0x967043,emissiveIntensity:.5}),x,1.45,1.1);if(b.train)add(new THREE.BoxGeometry(.5,1.1,.08),roof,0,3.7,0);}
 return group;};
function constructionLook(t){if(!t.mesh)return;t.mesh.traverse(o=>{if(o.isMesh&&o.material){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.3;o.material.color.lerp(new THREE.Color(0x68daca),.55);}});}
const builtPlace=place;
place=function(b,x,z,arg){if(b.retired){log('Train combat residents at a training building');return;}if(b.core){builtPlace(b,x,z,arg);return;}const previous=G.towers.length;builtPlace(b,x,z,arg);if(G.towers.length===previous)return;const t=G.towers.at(-1);t.uid=colony().nextBuilding++;t.siteId=gateNear(t.pos,1000)?.id||G.sites[0]?.id;if(!baseProvisioning){t.construction={done:0,total:b.work||(b.wall?10:18)};constructionLook(t);settlementNotice('Planned '+b.name+' — waiting for a laborer');}updateHud();};
function finishConstruction(t){t.construction=null;G.world.remove(t.mesh);t.mesh=t.edge?wallMesh(t):towerMesh(t.b);if(!t.edge)t.mesh.position.copy(t.pos);G.world.add(t.mesh);settlementNotice(t.b.name+' completed');updateHud();}
const workingTowers=updateTowers;
updateTowers=function(dt){const all=G.towers;G.towers=all.filter(t=>!t.construction&&!t.b.settlement);try{workingTowers(dt);}finally{G.towers=all;}};
createClaimNodes=function(site){const eco=economy();for(const body of G.generatedBodies||[]){if(!['tree','rock'].includes(body.source)||body.depleted||Math.hypot(body.x-site.corePos.x,body.z-site.corePos.z)>site.r*CELL)continue;const id=Math.round(body.x*100)+','+Math.round(body.z*100);const existing=eco.nodes.find(n=>n.id===id);if(existing){if(!existing.siteId)existing.siteId=site.id;continue;}eco.nodes.push({id,siteId:site.id,kind:body.source==='tree'?'logs':hashStr(id)%3===0?'ore':'stone',pos:V3(body.x,body.y,body.z),remaining:body.source==='tree'?24:32,capacity:body.source==='tree'?24:32,radius:body.r});}};
restoreSiteVisuals=function(site){G.world.add(site.group);site.coreMesh=gateMesh();site.coreMesh.position.copy(site.corePos);site.group.add(site.coreMesh);site.edge=new THREE.LineLoop(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:site.status==='secured'?0x65c8b4:0xd9b86b,transparent:true,opacity:.65}));site.group.add(site.edge);drawCaptureEdge(site);site.gatePos=(site.gates||[]).map(c=>tilePoint(...c));const ward=makePreview(6,0x80e6e0);ward.position.copy(site.corePos);ward.position.y+=.08;ward.material.opacity=.12;site.group.add(ward);site.wardMesh=ward;};
portalVisuals=restoreSiteVisuals;
const newClaim=foundSite;
foundSite=function(){const before=G.sites.length;newClaim();if(G.sites.length>before){const s=G.sites.at(-1);s.coreHp=s.coreMax=120;createClaimNodes(s);settlementNotice('Portal ward active: 6m sanctuary. Win five waves to protect the full claim.');}};
secureSite=function(){const s=G.site;if(!s)return;s.status='secured';s.edge.material.color.setHex(0x65c8b4);for(const line of s.routeLines||[])s.group.remove(line);s.routeLines=[];G.gold+=80;gainExperience(70);createClaimNodes(s);G.site=G.sites.find(o=>o.status==='pending')||null;if(G.site){G.site.status='active';G.phase='build';refreshRoutes();}else{G.phase='explore';G.dist={};}settlementNotice('Claim '+s.id+' secured. Enemy spawns are suppressed throughout its boundary.');updateHud();};
craftPortal=function(){const recipe={logs:40,stone:30,ore:20};if(G.gold<80||!canPay(recipe)){log('Portal kit: 80 gold, 40 wood, 30 stone, 20 ore');return false;}G.gold-=80;pay(recipe);economy().gateKits++;updateHud();return true;};
spawnRoamers=function(){};
function wildernessSpawn(point,type='grunt',scale){if(G.enemies.length>=128)return null;if(noSpawnAt(point)||blockedAt(point.x,point.z,point.y,.65,1.6,'nav'))return null;const e=spawnEnemy(type,null,scale||1+G.time/900);e.mode='wild';e.pos.copy(point);e.cell=worldToCell(point);e.home=point.clone();e.wanderDir=V3();e.wanderT=0;e.wildPath=[];e.wildRetry=0;e.mesh.position.copy(point);return e;}
function randomWildPoint(near=false){for(let i=0;i<30;i++){let x,z;if(near){const angle=G.rng()*Math.PI*2,distance=22+G.rng()*25;x=G.player.pos.x+Math.cos(angle)*distance;z=G.player.pos.z+Math.sin(angle)*distance;}else{x=(G.rng()-.5)*(WORLD-4)*CELL;z=(G.rng()-.5)*(WORLD-4)*CELL;}const p=V3(x,heightAt(x,z),z);if(inGrid(...worldToCell(p))&&!noSpawnAt(p)&&p.distanceTo(G.player.pos)>16&&!blockedAt(x,z,p.y,.7,1.6,'nav'))return p;}return null;}
const siegeUpdate=updateEnemies;
updateEnemies=function(dt){const wild=G.enemies.filter(e=>e.mode==='wild'),others=G.enemies.filter(e=>e.mode!=='wild');G.enemies=others;try{siegeUpdate(dt);}finally{G.enemies.push(...wild.filter(e=>!e.dead));}let planned=false;for(const e of wild){if(e.dead)continue;if(updateEnemyPhysics(e,dt))continue;e.slowT=(e.slowT||0)-dt;if(e.slowT<=0)e.slow=0;if(e.burnT>0){e.burnT-=dt;damage(e,(e.burn||0)*dt);if(e.dead)continue;}const distance=e.pos.distanceTo(G.player.pos),nearNpc=economy().workers.find(w=>w.hp>0&&w.pos.distanceTo(e.pos)<6),target=nearNpc?.pos||G.player.pos;const aggressive=e.pos.distanceTo(target)<35;let goal;
 if(aggressive){goal=target;e.wildRetry-=dt;if(walkSegment(e.pos,goal,e.d.size,'nav'))e.wildPath=[goal.clone()];else if(!planned&&e.wildRetry<=0){e.wildPath=commandPath(e.pos,goal,e.d.size);e.wildRetry=3;planned=true;}while(e.wildPath?.length&&e.pos.distanceTo(e.wildPath[0])<.35)e.wildPath.shift();goal=e.wildPath?.[0];}
 else{e.wanderT=(e.wanderT||0)-dt;if(e.wanderT<=0){const a=G.rng()*Math.PI*2;e.wanderDir=V3(Math.cos(a),0,Math.sin(a));e.wanderT=2+G.rng()*3;}goal=e.pos.clone().add(e.wanderDir);}
 if(goal&&e.pos.distanceTo(target)>e.d.size+.7){const dir=goal.clone().sub(e.pos);dir.y=0;dir.normalize();tryMove(e.pos,dir.x*e.d.spd*dt*(aggressive?1:.35),dir.z*e.d.spd*dt*(aggressive?1:.35));e.mesh.rotation.y=Math.atan2(dir.x,dir.z);}if(distance<e.d.size+.9&&Math.abs(e.pos.y-G.player.pos.y)<1.2)playerHit(e.d.dmg);e.prog=-distance;e.mesh.position.copy(e.pos);e.hb.scale.x=Math.max(.02,e.hp/e.maxHp);e.hb.lookAt(camera.position);e.hitT-=dt;e.body.material.emissive.setHex(e.hitT>0?0xffffff:e.burnT>0?0x662200:0);}
 G.enemies=G.enemies.filter(e=>!e.dead);const c=colony();c.spawnClock-=dt;if(c.spawnClock<=0){c.spawnClock=.9;const cap=Math.min(110,35+Math.floor(G.time/20));if(G.enemies.length<cap){const point=randomWildPoint(G.rng()<.65);if(point)wildernessSpawn(point,G.rng()<.15&&G.time>90?'brute':G.rng()<.25?'runner':'grunt');}}};
function gainExperience(amount){const p=G.player;p.level??=1;p.xp=(p.xp||0)+amount;while(p.xp>=p.level*35){p.xp-=p.level*35;p.level++;p.maxHp+=5;p.hp=Math.min(p.maxHp,p.hp+20);const unlock=UNLOCK_LEVELS.indexOf(p.level);settlementNotice('Level '+p.level+(unlock>=0?' — unlocked '+ABILITIES[G.classId][unlock][0]:' — +5 maximum health'));}G.uiNext=0;}
const xpDamage=damage;
damage=function(enemy,amount){const alive=!enemy.dead;xpDamage(enemy,amount);if(alive&&enemy.dead)gainExperience(enemy.type==='boss'?80:enemy.type==='brute'?18:8);};
function abilityUnlocked(i){return (G.player.level||1)>=UNLOCK_LEVELS[i];}
const learnedCast=castAbility,learnedSelect=activateAbility,learnedAuto=toggleAutomatic;
castAbility=function(i){return abilityUnlocked(i)?learnedCast(i):false;};
activateAbility=function(i){if(abilityUnlocked(i))learnedSelect(i);else log('Unlocks at level '+UNLOCK_LEVELS[i]);};
toggleAutomatic=function(i){if(abilityUnlocked(i))learnedAuto(i);};
function clearResidentTask(w){w.taskId=null;w.path=[];w.pathTarget=null;w.work=0;}
commandWorker=function(w,command,point){w.command=command==='work'?null:command;w.commandGoal=point?.clone()||null;w.staffId=null;clearResidentTask(w);w.state=command==='work'?'idle':command;};
function walkResident(w,destination,radius,dt){if(w.pos.distanceTo(destination)<=radius+.25)return true;w.retry=(w.retry||0)-dt;if(!w.pathTarget||w.pathTarget.distanceTo(destination)>1.5||(!w.path?.length&&w.retry<=0)){if(colony().pathBudget<=0)return false;colony().pathBudget--;w.path=workerRoute(w,destination,radius);w.pathTarget=destination.clone();w.retry=3;}while(w.path?.length&&w.pos.distanceTo(w.path[0])<.2)w.path.shift();if(w.path?.length){const delta=w.path[0].clone().sub(w.pos);delta.y=0;const len=delta.length();const p=w.pos.clone().add(delta.normalize().multiplyScalar(Math.min(len,dt*3.1)));p.y=heightAt(p.x,p.z);if(walkSegment(w.pos,p,.27,'nav')){w.pos.copy(p);w.mesh?.lookAt(p.x+delta.x,p.y,p.z+delta.z);}else{w.path=[];w.retry=1;}}return w.pos.distanceTo(destination)<=radius+.4;}
function availableLaborer(siteId){return economy().workers.find(w=>w.role==='laborer'&&w.siteId===siteId&&!w.staffId&&!w.training&&!w.command&&!w.cargo);}
function staffBuilding(t){if(t.construction||!t.b.produce)return false;const w=availableLaborer(t.siteId);if(!w){log('No free laborer at this settlement');return false;}if(economy().workers.some(w=>w.staffId===t.uid)){log('Already staffed');return false;}w.staffId=t.uid;clearResidentTask(w);w.state='assigned';return true;}
function trainResident(t){if(t.construction||!t.b.train)return false;const w=availableLaborer(t.siteId);if(!w||G.gold<35||!canPay({ore:5})){log('Requires a free laborer, 35 gold and 5 ore');return false;}G.gold-=35;pay({ore:5});w.training={building:t.uid,role:t.b.train,done:0};clearResidentTask(w);return true;}
updateWorkers=function(dt){const eco=economy();colony().pathBudget=3;for(const w of eco.workers){w.role??='laborer';w.hp??=60;w.maxHp??=60;w.job='laborer';w.attackCd=(w.attackCd||0)-dt;const site=G.sites.find(s=>s.id===w.siteId);if(!site)continue;const target=G.enemies.filter(e=>!e.dead&&e.pos.distanceTo(w.pos)<(w.role==='ranger'?13:w.role==='pyromancer'?10:2.5)).sort((a,b)=>a.pos.distanceToSquared(w.pos)-b.pos.distanceToSquared(w.pos))[0];
 if(target&&w.attackCd<=0){w.attackCd=w.role==='laborer'?1.4:1;const ranged=['ranger','pyromancer'].includes(w.role),origin=w.pos.clone().add(V3(0,1.1,0));if(!ranged||!projectileObstacle(origin,target.pos.clone().add(V3(0,target.d.size,0)),w.mesh)){if(ranged)tracer(origin,target.pos.clone().add(V3(0,1,0)),w.role==='ranger'?0xd8e6ac:0xff9955);if(w.role==='pyromancer'){for(const e of G.enemies)if(!e.dead&&e.pos.distanceTo(target.pos)<2.4)hitEnemy(e,10,w.pos,2);}else hitEnemy(target,w.role==='laborer'?3:w.role==='knight'?15:11,w.pos,w.role==='knight'?4:1);w.mesh.rotation.z=.15;}}
 w.hurtCd=(w.hurtCd||0)-dt;const attacker=G.enemies.find(e=>!e.dead&&e.pos.distanceTo(w.pos)<e.d.size+.6);if(attacker&&w.hurtCd<=0){w.hp-=attacker.d.dmg*.45;w.hurtCd=1;if(w.hp<=0){G.world.remove(w.mesh);settlementNotice((w.role==='laborer'?'Laborer':'Defender')+' '+w.id+' was lost');continue;}}else if(!attacker&&w.pos.distanceTo(site.corePos)<6)w.hp=Math.min(w.maxHp,w.hp+dt*2);
 if(w.command){w.state=w.command;if(w.command==='follow')walkResident(w,G.player.pos,2,dt);else if(w.command==='move'&&w.commandGoal&&walkResident(w,w.commandGoal,.25,dt))commandWorker(w,'stay');}
 else if(w.training){const t=G.towers.find(t=>t.uid===w.training.building);if(!t){w.training=null;continue;}w.state='training';if(walkResident(w,t.pos,buildRadius(t.b)+.7,dt)){w.training.done+=dt;if(w.training.done>=30){w.role=w.training.role;w.maxHp=w.role==='knight'?120:80;w.hp=w.maxHp;w.training=null;w.mesh.children[0].material.color.setHex(w.role==='knight'?0x809fb4:w.role==='ranger'?0x729e70:0xc87c54);settlementNotice('Resident '+w.id+' trained as '+w.role);}}}
 else if(w.role!=='laborer'){w.state='guarding';if(target&&w.role==='knight')walkResident(w,target.pos,1.6,dt);else if(w.pos.distanceTo(site.corePos)>8)walkResident(w,site.corePos,4,dt);}
 else if(w.staffId){const t=G.towers.find(t=>t.uid===w.staffId&&!t.construction);if(!t){w.staffId=null;continue;}w.state='producing';if(walkResident(w,t.pos,buildRadius(t.b)+.65,dt)){w.work=(w.work||0)+dt*(1+eco.harvestLevel*.3);if(w.work>=10){w.work-=10;eco[t.b.produce]+=t.b.produce==='logs'?3:1;if(t.b.id==='mine')eco.stone+=2;}}}
 else if(w.cargo>0){w.state='delivering';if(walkResident(w,site.corePos,2.4,dt)){eco[w.cargoKind||'logs']+=w.cargo;w.cargo=0;clearResidentTask(w);}}
 else {let t=G.towers.find(t=>t.uid===w.taskId&&t.construction);if(!t){t=G.towers.filter(t=>t.construction&&t.pos.distanceTo(w.pos)<80).sort((a,b)=>a.pos.distanceToSquared(w.pos)-b.pos.distanceToSquared(w.pos))[0];if(t){clearResidentTask(w);w.taskId=t.uid;}}
 if(t){w.state='building';if(walkResident(w,t.pos,buildRadius(t.b)+.8,dt)){t.construction.done+=dt;const progress=Math.min(1,t.construction.done/t.construction.total);t.mesh.scale.y=.25+progress*.75;t.mesh.traverse(o=>{if(o.isMesh&&o.material)o.material.opacity=.3+progress*.5;});if(t.construction.done>=t.construction.total){finishConstruction(t);clearResidentTask(w);}}}
 else{let node=eco.nodes.find(n=>n.id===w.targetId&&n.remaining>0&&n.siteId===site.id);if(!node){node=eco.nodes.filter(n=>n.siteId===site.id&&n.remaining>0).sort((a,b)=>a.pos.distanceToSquared(w.pos)-b.pos.distanceToSquared(w.pos))[0];w.targetId=node?.id;w.pathTarget=null;}if(node){w.state='harvesting';if(walkResident(w,node.pos,(node.radius||1)+.6,dt)){w.work=(w.work||0)+dt*(1+eco.harvestLevel*.3);if(w.work>=3){const count=Math.min(4,node.remaining);node.remaining-=count;w.cargo=count;w.cargoKind=node.kind;w.work=0;w.path=[];w.pathTarget=null;}}}else{w.state='idle';if(w.pos.distanceTo(site.corePos)>7)walkResident(w,site.corePos,4,dt);}}}
 if(w.mesh){const tool=w.mesh.getObjectByName('workTool');if(tool)tool.rotation.x=['building','harvesting','producing'].includes(w.state)?Math.sin(G.time*8)*.8:0;w.mesh.position.copy(w.pos);w.mesh.rotation.z=w.state==='building'||w.state==='harvesting'?Math.sin(G.time*7)*.1:0;}}
 eco.workers=eco.workers.filter(w=>w.hp>0);
 for(const t of G.towers){if(t.construction||t.b.id!=='house'||t.recruitPaused)continue;t.recruitTime=(t.recruitTime||0)+dt;const site=G.sites.find(s=>s.id===t.siteId&&s.status==='secured');if(t.recruitTime>=90&&site&&residents(site.id).length<housing(site.id)&&G.gold>=15){if(addResident(site)){G.gold-=15;t.recruitTime=0;settlementNotice('A new laborer arrived at gate '+site.id);}}}
 for(const s of G.sites){s.magicCd=(s.magicCd||0)-dt;if(s.magicCd<=0){const enemy=G.enemies.filter(e=>!e.dead&&e.pos.distanceTo(s.corePos)<14).sort((a,b)=>a.pos.distanceToSquared(s.corePos)-b.pos.distanceToSquared(s.corePos))[0];if(enemy){const from=s.corePos.clone().add(V3(0,2,0));if(!projectileObstacle(from,enemy.pos.clone().add(V3(0,1,0)),s.coreMesh)){tracer(from,enemy.pos.clone().add(V3(0,1,0)),0x82f4e7);hitEnemy(enemy,18,s.corePos,3);s.magicCd=1;}}}}
};
function provisionBase(){const p=G.player.pos.clone(),[cx,cz]=worldToCell(p),s={id:1,r:SITE_R,core:[cx,cz],corePos:tilePoint(cx,cz),coreMax:160,coreHp:160,gates:[],cells:[],status:'secured',wave:5,group:new THREE.Group(),wobble:{},routes:[],circular:true};for(let x=Math.max(0,cx-s.r);x<=Math.min(WORLD-1,cx+s.r);x++)for(let z=Math.max(0,cz-s.r);z<=Math.min(WORLD-1,cz+s.r);z++)if(Math.hypot(x-cx,z-cz)<=s.r){s.cells.push([x,z]);G.cells[x][z].site=1;}G.cells[cx][cz].type='core';G.sites.push(s);restoreSiteVisuals(s);createClaimNodes(s);rebuildCollision();const arrival=gateArrival(s);if(arrival)G.player.pos.copy(arrival);const money=G.gold,stock={logs:economy().logs,stone:economy().stone,ore:economy().ore};G.gold=99999;Object.assign(economy(),{logs:9999,stone:9999,ore:9999});baseProvisioning=true;
 try{for(const id of ['house','arrow','arrow']){const b=BUILDS.find(b=>b.id===id);let made=false;for(let ring=2;ring<10&&!made;ring++)for(let i=0;i<24&&!made;i++){const point=s.corePos.clone().add(V3(Math.cos(i*Math.PI/12)*ring*CELL,0,Math.sin(i*Math.PI/12)*ring*CELL));point.y=heightAt(point.x,point.z);if(!placementReason(b,point)&&Math.abs(point.y-G.player.pos.y)<.5&&walkSegment(G.player.pos,point,.27,'nav')){const n=G.towers.length;place(b,...worldToCell(point),point);made=G.towers.length>n;}}}}finally{baseProvisioning=false;G.gold=money;Object.assign(economy(),stock);}for(const role of ['laborer','laborer','knight','ranger'])addResident(s,role);G.phase='explore';G.site=null;G.playerMesh.position.copy(G.player.pos);}
const settlementNew=newRun;
newRun=function(...args){settlementNew(...args);Object.assign(economy(),{logs:140,stone:100,ore:50,fragments:0,gateKits:1});G.gold=260;G.player.level=1;G.player.xp=0;G.activeAbility=0;G.autoEnabled=Array(6).fill(false);colony();provisionBase();createDiscoveries();for(let i=0;i<22;i++){const p=randomWildPoint(false);if(p)wildernessSpawn(p);}setMsg('A home beyond the gate','Explore to grow stronger. B plans construction; E interacts. Your laborers handle the work.',7);updateHud();};
const settlementRestore=restoreSave;
restoreSave=function(s){worldRestoreInProgress=true;try{const copy=JSON.parse(JSON.stringify(s));copy.lairs=[];settlementRestore(copy);}finally{worldRestoreInProgress=false;}const c=colony();G.player.level??=1;G.player.xp??=0;G.activeAbility=abilityUnlocked(G.activeAbility)?G.activeAbility:0;G.autoEnabled=(G.autoEnabled||[]).map((v,i)=>!!v&&abilityUnlocked(i));for(const n of [...economy().ruins,...economy().nodes.filter(n=>n.cache)])if(n.mesh)G.world.remove(n.mesh);economy().ruins=[];economy().nodes=economy().nodes.filter(n=>!n.cache);for(const e of G.enemies)if(e.mode==='roam'){e.mode='wild';e.wildRetry=0;e.wildPath=[];}for(const w of economy().workers){w.job='laborer';w.role??='laborer';w.hp??=60;w.maxHp??=60;w.cargoKind??='logs';w.staffId??=null;c.nextNpc=Math.max(c.nextNpc,w.id+1);}for(const t of G.towers){t.uid??=c.nextBuilding++;c.nextBuilding=Math.max(c.nextBuilding,t.uid+1);t.siteId??=gateNear(t.pos,10000)?.id;if(t.construction)constructionLook(t);}for(const t of [...G.towers])if(t.b.retired){const site=G.sites.find(s=>s.id===t.siteId);if(site)addResident(site,'knight');G.world.remove(t.mesh);G.towers.splice(G.towers.indexOf(t),1);}if(!G.sites.length)provisionBase();for(const site of G.sites)createClaimNodes(site);restoreDiscoveries();rebuildCollision();if(G.site)refreshRoutes();updateHud();};window.bastion.restoreSave=restoreSave;
function closestInteraction(){const items=interactables().filter(i=>!['hostileGate','camp'].includes(i.kind));for(const d of colony().discoveries)if(!d.claimed&&d.pos.distanceTo(G.player.pos)<8)items.push({kind:'discovery',o:d,title:d.name});if(G.view!=='first')return items.sort((a,b)=>a.o.pos.distanceToSquared(G.player.pos)-b.o.pos.distanceToSquared(G.player.pos))[0]||null;const direction=camera.getWorldDirection(V3()),ray=new THREE.Ray(camera.position,direction),obstacle=projectileObstacle(camera.position,camera.position.clone().addScaledVector(direction,8));let best=null,dist=Infinity;for(const item of items){const p=item.o.pos.clone().add(V3(0,item.kind==='resource'?.8:1,0)),radius=item.kind==='tower'?buildRadius(item.o.b):item.kind==='portal'?1.6:item.kind==='resource'?Math.max(.6,item.o.radius||1):.8,hit=ray.intersectSphere(new THREE.Sphere(p,radius),V3());if(!hit)continue;const distance=hit.distanceTo(camera.position);if(obstacle&&distance>obstacle.distanceTo(camera.position)+.8)continue;if(distance<dist){best=item;dist=distance;}}return best;}
openInteraction=function(){const item=closestInteraction();if(item)interactWith(item);else log(G.view==='first'?'Aim at an object within 8m':'Move closer to an object to interact');};
interactWith=function(item){const {kind,o}=item,title=kind==='worker'?(o.role==='laborer'?'Laborer':CLASSES[o.role]?.name||'Resident')+' '+o.id:item.title;const actions=[],action=(label,run)=>actions.push({label,run:()=>{if(o.pos.distanceTo(G.player.pos)>8){log('Move closer');closeInteraction();return;}run();}});let info='';
 if(kind==='worker'){info=Math.ceil(o.hp||60)+' / '+(o.maxHp||60)+' health · '+o.state+' · Gate '+o.siteId;for(const [cmd,label]of [['follow','Follow me'],['stay','Stay here'],['work','Resume duties']])action(label,()=>{commandWorker(o,cmd);closeInteraction();});action('Move to location…',()=>{G.workerOrder=o.id;closeInteraction();});action('Return to home gate',()=>{const s=G.sites.find(s=>s.id===o.siteId);commandWorker(o,'move',gateArrival(s)||s.corePos);closeInteraction();});}
 if(kind==='tower'){info=o.b.description||'Defense structure. Enemies must retain an approach to each active portal.';if(o.construction)info+=' Construction '+Math.floor(o.construction.done/o.construction.total*100)+'% — '+Math.ceil(o.construction.total-o.construction.done)+' labor seconds remaining.';if(o.b.produce&&!o.construction){const w=economy().workers.find(w=>w.staffId===o.uid);info+=' '+(w?'Staffed by laborer '+w.id:'Unstaffed');action(w?'Release assigned laborer':'Assign a free laborer',()=>{if(w){w.staffId=null;clearResidentTask(w);}else staffBuilding(o);interactWith(item);});}if(o.b.train&&!o.construction)action('Train a laborer · 35 gold + 5 ore',()=>{trainResident(o);interactWith(item);});if(o.b.id==='house'&&!o.construction){info+=' '+residents(o.siteId).length+'/'+housing(o.siteId)+' residents · arrival in '+Math.max(0,Math.ceil(90-(o.recruitTime||0)))+'s';action(o.recruitPaused?'Resume recruitment':'Pause recruitment',()=>{o.recruitPaused=!o.recruitPaused;interactWith(item);});}action((o.construction?'Cancel plan':'Dismantle')+' · 60% refund',()=>{sellStructure(o);closeInteraction();});}
 if(kind==='portal'){const site=o.original;info=site.status+' · '+Math.ceil(site.coreHp)+'/'+site.coreMax+' integrity · '+(site.status==='secured'?Math.round(site.r*CELL):6)+'m spawn protection · magical bolts within 14m';if(site===G.site)action('Start next defense wave',()=>{startWave();closeInteraction();});action('Transfer a resident here…',()=>{const options=economy().workers.filter(w=>w.siteId!==site.id).map(w=>({label:(w.role||'laborer')+' '+w.id+' · from gate '+w.siteId,run:()=>{transferResident(w,site);closeInteraction();}}));showInteraction('Gate '+site.id+' · resident transfer','Existing residents must be within 10m of their source portal. No new residents are created.',options);});action('Craft portal kit · 80g, 40 wood, 30 stone, 20 ore',()=>{craftPortal();interactWith(item);});action('Repair 20 integrity · 10 stone',()=>{if(site.coreHp<site.coreMax&&pay({stone:10}))site.coreHp=Math.min(site.coreMax,site.coreHp+20);interactWith(item);});}
 if(kind==='resource'){info=o.remaining+' '+o.kind+' remaining. Environmental nodes regrow after five minutes; staffed production leaves these nodes intact.';action('Hand harvest',()=>{harvestNode(o);interactWith(item);});}
 if(kind==='chest'){info='A forgotten cache found in the wilderness.';action('Open · '+o.gold+' gold',()=>{if(!o.taken){o.taken=true;G.gold+=o.gold;G.world.remove(o.mesh);gainExperience(20);rebuildCollision();}closeInteraction();});}
 if(kind==='shrine'){info='Ancient magic offers a choice of relic.';action('Accept a blessing',()=>{if(!o.used){o.used=true;o.mesh.material.emissiveIntensity=0;closeInteraction();gainExperience(25);openDraft('shrine');}});}
 if(kind==='enemy'){info=Math.ceil(o.hp)+'/'+Math.ceil(o.maxHp)+' health';if(G.view!=='first')action('Select target',()=>{chooseTarget(o);closeInteraction();});if(o===livingTarget())action('Lock target',()=>{G.targetLocked=true;closeInteraction();});}
 if(kind==='discovery'){info=o.description;action(o.kind==='spring'?'Drink from the spring':o.kind==='relic'?'Study the monument':'Recover the fallen star',()=>{if(o.claimed)return;o.claimed=true;gainExperience(o.kind==='star'?60:40);if(o.kind==='spring')G.player.hp=G.player.maxHp;if(o.kind==='star'){economy().gateKits++;G.gold+=40;}if(o.kind==='relic'){closeInteraction();openDraft('shrine');return;}settlementNotice(o.name+' discovered');closeInteraction();});}
 showInteraction(title,info,actions);};
function buildCategory(b){return b.core?'Portals':b.category||'Defenses';}
function renderBuildCatalog(){if(!document.getElementById('buildCatalog')||!G)return;const category=colony().category||'Defenses',query=$('buildSearch').value.toLowerCase(),signature=[category,query,G.gold,economy().logs,economy().stone,economy().ore,G.selected,G.towers.length].join('/');if($('buildCatalog').dataset.signature===signature)return;$('buildCatalog').dataset.signature=signature;const tabs=$('buildCategories');tabs.innerHTML='';for(const name of ['Defenses','Housing','Training','Production','Portals']){const button=document.createElement('button');button.textContent=name;button.className=name===category?'selected':'';button.onclick=()=>{colony().category=name;renderBuildCatalog();};tabs.appendChild(button);}$('buildCatalog').innerHTML='';BUILDS.forEach((b,index)=>{if(b.retired||buildCategory(b)!==category||query&&!b.name.toLowerCase().includes(query))return;const button=document.createElement('button'),cost=b.core?'1 portal kit':buildCost(b)+' gold · '+recipeText(DEFENSE_RECIPES[b.id]||{});button.className='build-card'+(index===G.selected?' selected':'');const title=document.createElement('strong');title.textContent=b.name;const price=document.createElement('span');price.textContent=cost;const detail=document.createElement('small');detail.textContent=b.core?'Instant portal · 6m ward · five defense waves':(b.description||'Laborer-built defense. Place freely while keeping enemy routes open.')+' · '+(b.work||(b.wall?10:18))+' labor seconds';button.append(title,price,detail);button.onclick=()=>{G.selected=index;updateHud();renderBuildCatalog();};$('buildCatalog').appendChild(button);});}
function showSettlementLedger(){G.uiCursor=true;document.exitPointerLock?.();const panel=$('settlementPanel');panel.classList.remove('hidden');panel.innerHTML='<header><h2>Settlement ledger</h2><button id="ledgerClose">Close</button></header><p>Homes recruit. Laborers build and gather. Use E beside a structure to manage it.</p><div class="ledgerResearch"><button id="researchTools">Improve tools</button><button id="researchDefense">Improve defenses</button></div><div id="ledgerContent"></div>';$('researchTools').onclick=()=>{upgradeEconomy('harvestLevel');renderLedger();};$('researchDefense').onclick=()=>{upgradeEconomy('defenseLevel');renderLedger();};$('ledgerClose').onclick=()=>{panel.classList.add('hidden');G.uiCursor=false;captureFirstPerson();};renderLedger();}
function renderLedger(){if(!document.getElementById('ledgerContent'))return;const content=$('ledgerContent');content.innerHTML='';const eco=economy();$('researchTools').textContent='Tools '+eco.harvestLevel+' · '+recipeText({logs:20+eco.harvestLevel*10,stone:15+eco.harvestLevel*10});$('researchDefense').textContent='Defenses '+eco.defenseLevel+' · '+recipeText({stone:25+eco.defenseLevel*15,ore:10+eco.defenseLevel*5});const row=(heading,body)=>{const article=document.createElement('article'),h=document.createElement('strong'),p=document.createElement('p');h.textContent=heading;p.textContent=body;article.append(h,p);content.appendChild(article);};for(const s of G.sites)row('Gate '+s.id+' · '+s.status,residents(s.id).length+'/'+housing(s.id)+' residents · '+Math.ceil(s.coreHp)+' integrity');for(const w of economy().workers)row((w.role||'laborer')+' '+w.id,'Gate '+w.siteId+' · '+w.state+' · '+Math.ceil(w.hp||60)+' health');for(const t of G.towers.filter(t=>t.construction))row(t.b.name+' · construction',Math.floor(t.construction.done/t.construction.total*100)+'% complete');for(const n of colony().notices.slice(0,4))row('Recent event',n);}
updateEconomyUI=function(){if(!G||!document.getElementById('resourceStrip'))return;const e=economy();$('resourceStrip').textContent='Wood '+e.logs+'   Stone '+e.stone+'   Ore '+e.ore+'\nPortal kits '+e.gateKits+'   Residents '+e.workers.length;applyHarvestedNodes();};
const settlementUI=updateCombatUI;
updateCombatUI=function(){settlementUI();if(!G||!combatUIReady)return;for(let i=0;i<6;i++){const el=$('ability'+i),unlocked=abilityUnlocked(i);el.classList.toggle('ability-locked',!unlocked);el.disabled=G.buildMode||!unlocked;if(!unlocked)el.querySelector('.ability-cd').textContent='Lv '+UNLOCK_LEVELS[i];}$('playerUnitName').textContent=CLASSES[G.classId].name+' · Level '+(G.player.level||1);if(document.getElementById('experienceBar')){$('experienceFill').style.width=((G.player.xp||0)/((G.player.level||1)*35)*100)+'%';$('experienceLabel').textContent='Level '+(G.player.level||1)+' · '+(G.player.xp||0)+' / '+((G.player.level||1)*35)+' XP';$('constructionPanel').classList.toggle('hidden',!G.buildMode);if(G.time>=settlementUiAt){settlementUiAt=G.time+.5;renderBuildCatalog();renderLedger();const candidate=closestInteraction();$('interactPrompt').textContent=candidate?'E · '+(candidate.kind==='worker'?(candidate.o.role||'Laborer')+' '+candidate.o.id:candidate.title):'';}}};
const settlementTooltip=showMoveTooltip;
showMoveTooltip=function(i){settlementTooltip(i);if(!abilityUnlocked(i))$('moveTooltip').innerHTML='<strong>'+ABILITIES[G.classId][i][0]+'</strong><p>Unlocks at level '+UNLOCK_LEVELS[i]+'.</p><p>'+MOVE_INFO[G.classId][i]+'</p>';};
const settlementInstall=installIntegration;
installIntegration=function(){settlementInstall();const panel=document.createElement('section');panel.id='constructionPanel';panel.className='hidden';panel.innerHTML='<header><span>SETTLEMENT PLANNER</span><h2>Plan your next home</h2><p>Choose a blueprint, then click the world. Laborers travel to each site and build it.</p></header><input id="buildSearch" placeholder="Find a structure…" aria-label="Search structures"><nav id="buildCategories"></nav><div id="buildCatalog"></div>';document.body.appendChild(panel);$('buildSearch').oninput=renderBuildCatalog;const xp=document.createElement('div');xp.id='experienceBar';xp.innerHTML='<div id="experienceFill"></div><span id="experienceLabel"></span>';document.body.appendChild(xp);const prompt=document.createElement('div');prompt.id='interactPrompt';document.body.appendChild(prompt);$('settlementToggle').onclick=showSettlementLedger;$('help').innerHTML='<b>Frontier controls</b><div>W/S move · Shift sprint · Space jump · V view</div><div>Third person: LMB drag free look · RMB drag steer</div><div>Both mouse buttons move · A/D turn · RMB + A/D strafe</div><div>Wheel zoom · First person mouse look; hold Alt for cursor</div><div>1–6: select; repeat / LMB: cast; RMB move: auto</div><div>Tab target · Escape untarget · E interact</div><div>B construction planner · Enter defense wave</div><div>Menu/Pause deliberately pauses the game</div>';};
function restoreDiscoveries(){for(const d of colony().discoveries){if(d.mesh)continue;const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:d.kind==='spring'?0x79cbd1:d.kind==='star'?0xd9aa65:0x8f9b91,emissive:d.kind==='spring'?0x245c68:d.kind==='star'?0x8c511b:0x273a35,emissiveIntensity:.5,roughness:.5});const stone=new THREE.Mesh(d.kind==='spring'?new THREE.CylinderGeometry(1.1,1.3,.3,16):new THREE.OctahedronGeometry(d.kind==='star'?.8:1.1,0),mat);stone.position.y=d.kind==='spring'?.12:1;group.add(stone);if(d.kind==='relic')for(let i=0;i<5;i++){const pillar=new THREE.Mesh(new THREE.BoxGeometry(.35,1.5+(i%2)*.5,.35),new THREE.MeshStandardMaterial({color:0x777e76,roughness:1}));pillar.position.set(Math.cos(i*1.256)*2,.75,Math.sin(i*1.256)*2);group.add(pillar);}group.position.copy(d.pos);G.world.add(group);d.mesh=group;if(d.kind==='star'){const beam=new THREE.Mesh(new THREE.CylinderGeometry(.06,.3,16,8),new THREE.MeshBasicMaterial({color:0xffc779,transparent:true,opacity:.32,depthWrite:false}));beam.position.y=8;group.add(beam);}}}
function createDiscoveries(){for(let i=0;i<7;i++){const p=randomWildPoint(false);if(!p)continue;const kind=i%3===0?'spring':'relic';colony().discoveries.push({id:'discovery-'+i,kind,pos:p,name:kind==='spring'?'Moonwell':'Weathered runestone',description:kind==='spring'?'A cool, luminous spring. Restores your health once and grants exploration experience.':'A circle of ancient standing stones. Studying the carvings grants experience and a choice of relic.',claimed:false});}restoreDiscoveries();rebuildCollision();}
const naturalHarvest=applyHarvestedNodes;
applyHarvestedNodes=function(){const e=economy(),bodies=new Map((G.generatedBodies||[]).map(b=>[Math.round(b.x*100)+','+Math.round(b.z*100),b]));let changed=false;for(const n of e.nodes){if(n.cache)continue;const b=bodies.get(n.id);if(!b)continue;if(n.remaining<=0){n.respawnAt??=G.time+300;n.capacity??=n.kind==='logs'?24:32;b.regrowMatrices??=(b.draw||[]).map(part=>{const m=new THREE.Matrix4();part.mesh.getMatrixAt(part.index,m);return m;});}if(n.respawnAt&&G.time>=n.respawnAt){n.remaining=n.capacity||24;n.respawnAt=null;b.depleted=false;(b.draw||[]).forEach((part,i)=>{if(b.regrowMatrices?.[i]){part.mesh.setMatrixAt(part.index,b.regrowMatrices[i]);part.mesh.instanceMatrix.needsUpdate=true;}});changed=true;}}naturalHarvest();if(changed){rebuildCollision();if(G.site)refreshRoutes();}};
function terrainTexture(kind){const size=128,data=new Uint8Array(size*size*4),noise=makeNoise(hashStr('frontier/'+kind)),rng=mulberry32(hashStr(kind));for(let y=0;y<size;y++)for(let x=0;x<size;x++){const n=noise(x/15,y/15)*.45+noise(x/4,y/4)*.25+rng()*.3,grain=kind==='rock'?.65+n*.4-Math.pow(Math.abs(Math.sin(y*.19+noise(x/20,y/20)*5)),18)*.15:.65+n*.42;const i=(y*size+x)*4;data[i]=Math.min(255,255*grain);data[i+1]=Math.min(255,255*grain);data[i+2]=Math.min(255,255*grain);data[i+3]=255;}const texture=new THREE.DataTexture(new THREE.Uint8BufferAttribute(data,4).array,size,size);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.magFilter=THREE.LinearFilter;texture.minFilter=THREE.LinearMipmapLinearFilter;texture.generateMipmaps=true;texture.needsUpdate=true;return texture;}
const oldTexturedTerrain=buildTerrainMesh;
buildTerrainMesh=function(){const result=oldTexturedTerrain(),mesh=result?.isMesh?result:G.terrain;if(!mesh?.geometry)return result;const geometry=mesh.geometry,positions=geometry.attributes.position,normal=geometry.attributes.normal,uv=new Float32Array(positions.count*2),colors=new Float32Array(positions.count*3),noise=makeNoise(hashStr(G.seed+'biome'));geometry.clearGroups();const groundIndices=[],cliffIndices=[];for(let i=0;i<positions.count;i++){const x=positions.getX(i),y=positions.getY(i),z=positions.getZ(i),up=Math.abs(normal?.getY(i)||0)>.65;uv[i*2]=(up?x:Math.abs(normal?.getX(i)||0)>.5?z:x)*.55;uv[i*2+1]=(up?z:y)*.55;const mix=noise(x/25,z/25),color=up?new THREE.Color(0x61794b).lerp(new THREE.Color(0x9d9770),mix*.65):new THREE.Color(0x92928a).lerp(new THREE.Color(0x6a746f),mix);colors.set([color.r,color.g,color.b],i*3);if(i%3===0)(up?groundIndices:cliffIndices).push(i,i+1,i+2);}geometry.setIndex([...groundIndices,...cliffIndices]);geometry.addGroup(0,groundIndices.length,0);geometry.addGroup(groundIndices.length,cliffIndices.length,1);geometry.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const grass=terrainTexture('grass'),rock=terrainTexture('rock');mesh.material=[new THREE.MeshStandardMaterial({map:grass,bumpMap:grass,bumpScale:.1,vertexColors:true,side:THREE.DoubleSide,roughness:1}),new THREE.MeshStandardMaterial({map:rock,bumpMap:rock,bumpScale:.18,vertexColors:true,side:THREE.DoubleSide,roughness:.96})];return result;};
const livingWorldMeshes=buildWorldMeshes;
buildWorldMeshes=function(){G.lairs=[];livingWorldMeshes();const bark=terrainTexture('bark');const mapped=new Set();for(const b of G.generatedBodies||[])for(const part of b.draw||[]){const mesh=part.mesh;if(mapped.has(mesh))continue;mapped.add(mesh);if(mesh.material?.isMeshStandardMaterial){mesh.material.map=bark;mesh.material.bumpMap=bark;mesh.material.bumpScale=.07;mesh.material.needsUpdate=true;}}};
function animateWilderness(dt){const c=colony();c.day=(c.day||0)+dt;c.eventClock-=dt;if(c.eventClock<=0){c.eventClock=100+G.rng()*70;const p=randomWildPoint(true);if(p){const d={id:'star-'+Math.floor(G.time),kind:'star',pos:p,name:'Fallen star',description:'A shard of portal magic draws prowling creatures. Recover it for a portal kit, gold and experience.',claimed:false};c.discoveries.push(d);restoreDiscoveries();rebuildCollision();for(let i=0;i<5;i++){const q=p.clone().add(V3(Math.cos(i*1.256)*5,0,Math.sin(i*1.256)*5));q.y=heightAt(q.x,q.z);wildernessSpawn(q,i===0?'brute':'grunt');}settlementNotice('A star has fallen '+Math.round(p.distanceTo(G.player.pos))+'m away. Look for the amber beacon.');}}
 for(const d of c.discoveries){if(!d.mesh)continue;if(d.kind==='star'){d.mesh.rotation.y+=dt*.4;d.mesh.children[0].position.y=1+Math.sin(G.time*2)*.18;}d.mesh.children[0].material.emissiveIntensity=d.claimed?.08:.45+Math.sin(G.time+d.pos.x)*.15;}
 if(!G.birds){G.birds=new THREE.Group();const mat=new THREE.MeshBasicMaterial({color:0x344449});for(let i=0;i<9;i++){const bird=new THREE.Mesh(new THREE.ConeGeometry(.3,.8,3),mat);bird.rotation.z=Math.PI/2;G.birds.add(bird);}G.world.add(G.birds);}G.birds.children.forEach((bird,i)=>{const a=G.time*.09+i*.18;bird.position.set(G.player.pos.x+Math.cos(a)*25,G.player.pos.y+17+Math.sin(a*2+i)*2,G.player.pos.z+Math.sin(a)*25);bird.rotation.y=-a;bird.scale.y=.7+Math.sin(G.time*5+i)*.3;});sun.intensity=.85+Math.sin(c.day/150)*.18;
}
const settlementPlayer=updatePlayer;
updatePlayer=function(dt){settlementPlayer(dt);animateWilderness(dt);};
// Defense waves use reachable wilderness approaches, never a protected spawn point.
const wardedSpawn=spawnEnemy;
spawnEnemy=function(type,gate,scale){if(gate!=null&&G.site){let p=G.site.gatePos[gate];if(!p||noSpawnAt(p)){p=null;for(let i=0;i<24&&!p;i++){const angle=i*Math.PI/12,r=G.site.r*CELL+8+Math.floor(i/12)*10,q=G.site.corePos.clone().add(V3(Math.cos(angle)*r,0,Math.sin(angle)*r));q.y=heightAt(q.x,q.z);if(inGrid(...worldToCell(q))&&!noSpawnAt(q)&&!blockedAt(q.x,q.z,q.y,1.26,1.6,'nav')&&gridPlan(q,G.site.corePos,1.26))p=q;}if(!p){settlementNotice('This approach is protected; no enemy can materialize here.');return null;}}const e=wardedSpawn(type,null,scale);e.pos.copy(p);e.cell=worldToCell(p);e.routeId=gate;e.routeCursor=0;e.mesh.position.copy(p);return e;}return wardedSpawn(type,gate,scale);};

const plannedPreview=previewWall;
previewWall=function(){plannedPreview();if(G?.buildMode){const b=BUILDS[G.selected];$('tip').textContent=b.core?'Portal gate · instant ward · requires one portal kit':b.name+' blueprint · '+buildCost(b)+' gold · '+recipeText(DEFENSE_RECIPES[b.id]||{})+' · laborers build it';}};

const discoveryMinimap=drawMinimap;
drawMinimap=function(){discoveryMinimap();const ctx=$('mini').getContext('2d'),scale=160/WORLD;for(const d of colony().discoveries){if(d.claimed)continue;const [x,z]=worldToCell(d.pos);ctx.fillStyle=d.kind==='star'?'#ffd18a':d.kind==='spring'?'#82e0e9':'#d0abef';ctx.fillRect(x*scale-1.5,z*scale-1.5,3,3);}};
const discoveryCollision=rebuildCollision;
rebuildCollision=function(){if(G?.generatedBodies){G.generatedBodies=G.generatedBodies.filter(b=>!b.discovery);for(const d of G.economy?.settlement?.discoveries||[]){if(d.kind==='spring')continue;G.generatedBodies.push({x:d.pos.x,z:d.pos.z,y:d.pos.y,r:d.kind==='star'?.8:1.1,h:2,source:d,discovery:true});if(d.kind==='relic')for(let i=0;i<5;i++)G.generatedBodies.push({x:d.pos.x+Math.cos(i*1.256)*2,z:d.pos.z+Math.sin(i*1.256)*2,y:d.pos.y,r:.25,h:2,source:d,discovery:true});}}discoveryCollision();};

const residentModel=workerMesh;
workerMesh=function(job){const group=residentModel(job),tool=new THREE.Group();tool.name='workTool';tool.position.set(.35,.9,.2);const handle=new THREE.Mesh(new THREE.BoxGeometry(.08,.6,.08),new THREE.MeshStandardMaterial({color:0x947857})),head=new THREE.Mesh(new THREE.BoxGeometry(.32,.16,.15),new THREE.MeshStandardMaterial({color:0xaeb5b1,metalness:.45,roughness:.65}));head.position.y=.28;tool.add(handle,head);group.add(tool);return group;};
const settlementValidation=validateSave;
validateSave=function(save){settlementValidation(save);const p=save.state.player,validNumber=n=>Number.isFinite(n)&&n>=0&&n<=1e9;if(p.level!==undefined&&(!Number.isInteger(p.level)||p.level<1||p.level>10000))throw Error('Invalid character level');if(p.xp!==undefined&&!validNumber(p.xp))throw Error('Invalid character experience');for(const t of save.towers)if(t.construction&&(!validNumber(t.construction.done)||!validNumber(t.construction.total)||t.construction.total<=0))throw Error('Invalid construction progress');const colony=save.state.economy?.settlement;if(colony){if(!Array.isArray(colony.discoveries)||colony.discoveries.length>5000||colony.discoveries.some(d=>!['spring','star','relic'].includes(d.kind)||!Array.isArray(d.pos?.$v)||d.pos.$v.length!==3||!d.pos.$v.every(Number.isFinite)))throw Error('Invalid exploration landmarks');for(const w of save.state.economy.workers)if(!['laborer','knight','ranger','pyromancer'].includes(w.role)||!validNumber(w.hp)||!validNumber(w.maxHp))throw Error('Invalid settlement resident');}};
/* One placement point drives the cursor, click, keyboard and confirmation button. */
let confirmingBlueprint=false;
const placementAim=aimPoint;
aimPoint=function(){if(!G?.buildMode)return placementAim();if(mouseOverHud)return G.buildAim?.clone()||null;raycaster.setFromCamera({x:mouse.x,y:mouse.y},camera);const point=groundHit();G.buildAim=point?.clone()||null;return point;};
function inspectBlueprint(){const b=BUILDS[G.selected],hit=aimPoint();if(!hit)return {b,reason:'Point at terrain to choose a build location.'};const p=b.core?tilePoint(...worldToCell(hit)):buildPoint(...worldToCell(hit),hit),cell=worldToCell(p),side=b.wall?wallSide(...cell,hit):undefined;let reason=b.retired?'Train defenders at a training building.':b.core?coreReason(p):b.wall?wallPlacement(...cell,side):placementReason(b,p);if(!reason&&!b.core&&G.gold<buildCost(b))reason='Not enough gold: need '+buildCost(b)+', have '+G.gold+'.';if(!reason&&!b.core&&!canPay(DEFENSE_RECIPES[b.id]||{}))reason='Need materials: '+recipeText(DEFENSE_RECIPES[b.id]||{})+'.';return {b,p,cell,side,reason};}
const placementLog=log;
log=function(message){if(confirmingBlueprint&&G)G.buildFailure=message;placementLog(message);};
function confirmBlueprint(){if(!G?.buildMode||menuPaused||G.phase==='over')return;const plan=inspectBlueprint();if(plan.reason){G.buildSuccess=false;G.buildFeedback=plan.reason;G.buildFeedbackUntil=G.time+5;renderPlacementStatus();return false;}const before=G.towers.length+G.sites.length;G.buildFailure=null;confirmingBlueprint=true;try{place(plan.b,...plan.cell,plan.b.wall?plan.side:plan.p);}finally{confirmingBlueprint=false;}const success=G.towers.length+G.sites.length>before;G.buildSuccess=success;G.buildFeedback=success?(plan.b.core?'Portal gate placed.':plan.b.name+' blueprint placed. Laborers will build it.'):(G.buildFailure||'This position is blocked. Choose another spot.');G.buildFeedbackUntil=G.time+5;renderPlacementStatus();return success;}
const buildClick=clickWorld;
clickWorld=function(){if(G?.buildMode&&!G.workerOrder){confirmBlueprint();return;}return buildClick();};
function renderPlacementStatus(){if(!G?.buildMode||!document.getElementById('buildStatus'))return;const plan=inspectBlueprint(),feedback=G.time<(G.buildFeedbackUntil||0)?G.buildFeedback:null,text=feedback||plan.reason||'Ready: left-click the world, press F, or use Confirm blueprint.';$('buildStatus').textContent=text;$('buildStatus').classList.toggle('blocked',feedback?!G.buildSuccess:!!plan.reason);$('confirmBlueprint').disabled=!!plan.reason;$('confirmBlueprint').textContent=plan.b?.core?'Place portal gate · F':'Confirm blueprint · F';$('tip').textContent=plan.reason||'LMB / F confirms '+plan.b.name+' · '+(plan.b.core?'one portal kit':'laborers build it');if(G.cursor&&!plan.b.core)G.cursor.material.color.setHex(plan.reason?0xd86455:0x6bd5a8);}
const clearPlacementToggle=toggleBuildMode;
toggleBuildMode=function(){clearPlacementToggle();if(G){G.buildAim=null;G.buildFeedback=null;G.buildFeedbackUntil=0;}};
const confirmedPreview=previewWall;
previewWall=function(){confirmedPreview();renderPlacementStatus();};
const confirmInput=bindInput;
bindInput=function(){confirmInput();addEventListener('keydown',e=>{if(e.code!=='KeyF'||e.repeat||e.target?.closest?.('input,select,textarea')||!G?.buildMode||menuPaused||!$('draft').classList.contains('hidden'))return;e.preventDefault();confirmBlueprint();});};
const confirmInstall=installIntegration;
installIntegration=function(){confirmInstall();const footer=document.createElement('footer');footer.id='placementControls';footer.innerHTML='<p id="buildStatus" role="status" aria-live="polite">Point at terrain to choose a build location.</p><button id="confirmBlueprint">Confirm blueprint · F</button>'; $('constructionPanel').appendChild(footer);$('confirmBlueprint').onclick=confirmBlueprint;$('constructionPanel').querySelector('header p').textContent='Choose a blueprint, point at clear terrain, then left-click or press F. Laborers build confirmed plans.';};
