/* Physical footprints shared by placement, actors, projectiles and navigation. */
let candidateBody=null;
function buildRadius(b){return b.id==='ballista'?1.25:b.id==='gale'?.85:b.id==='guard'?.48:b.id==='spike'?Math.max(.7,CELL*.48):b.id==='tar'?.92:b.id==='arrow'?.75:.65;}
function buildHeight(b){return ({arrow:2.3,brazier:1.75,frost:1.85,ballista:1.6,guard:1.8,gale:2.2,spike:.5,tar:.1})[b.id]||2.25;}
function footprint(b,p,source){return b.id==='spike'?{x:p.x,z:p.z,y:p.y,r:0,h:buildHeight(b),hx:(CELL-.2)/2,hz:(CELL-.2)/2,source,walkable:true}:bodyCircle(p.x,p.z,p.y,buildRadius(b),buildHeight(b),source,!!b.trap);}
function bodiesOverlap(a,b){if(a.hx!==undefined&&b.hx!==undefined)return Math.abs(a.x-b.x)<a.hx+b.hx&&Math.abs(a.z-b.z)<a.hz+b.hz;if(a.hx!==undefined)return overlapsBody(a,b.x,b.z,b.r);return overlapsBody(b,a.x,a.z,a.r);}
function bodyCircle(x,z,y,r,h,source,walkable=false){return{x,z,y,r,h,source,walkable};}
function rebuildCollision(){if(!G)return;const bodies=[...(G.generatedBodies||[])];for(const t of G.towers){if(t.edge){const [dx,dz]=WALL_SIDES[t.edge];bodies.push({x:t.pos.x+dx*CELL/2,z:t.pos.z+dz*CELL/2,y:t.pos.y,r:0,h:2.25,hx:dx?.14:CELL/2+.12,hz:dz?.14:CELL/2+.12,source:t});}else bodies.push(footprint(t.b,t.pos,t));}for(const site of G.sites)bodies.push(bodyCircle(site.corePos.x,site.corePos.z,site.corePos.y,1.05,2.4,site));G.collisionBodies=bodies;G.bodyBins=new Map();for(const b of bodies){const r=b.r||Math.max(b.hx,b.hz);for(let x=Math.floor((b.x-r)/4);x<=Math.floor((b.x+r)/4);x++)for(let z=Math.floor((b.z-r)/4);z<=Math.floor((b.z+r)/4);z++){const k=x+','+z;if(!G.bodyBins.has(k))G.bodyBins.set(k,[]);G.bodyBins.get(k).push(b);}}G.nav=null;G.navLarge=null;placementCache.clear();}
function nearbyBodies(x,z,r){if(!G.bodyBins)rebuildCollision();const out=new Set();for(let i=Math.floor((x-r)/4);i<=Math.floor((x+r)/4);i++)for(let j=Math.floor((z-r)/4);j<=Math.floor((z+r)/4);j++)for(const b of G.bodyBins.get(i+','+j)||[])out.add(b);if(candidateBody)out.add(candidateBody);return out;}
function overlapsBody(b,x,z,r){if(b.hx!==undefined)return Math.hypot(Math.max(0,Math.abs(x-b.x)-b.hx),Math.max(0,Math.abs(z-b.z)-b.hz))<r;return Math.hypot(x-b.x,z-b.z)<r+b.r;}
function blockedAt(x,z,y,r=.35,h=1.65,ignore=null,placement=false){if(Math.abs(x)+r>=WORLD*CELL/2||Math.abs(z)+r>=WORLD*CELL/2)return true;for(const b of nearbyBodies(x,z,r)){if(b.source===ignore||b.source?.taken||(!placement&&b.walkable)||(!placement&&ignore==='nav'&&b.source?.corePos))continue;if(y+h>b.y+.04&&y<b.y+b.h-.04&&overlapsBody(b,x,z,r))return true;}if(ignore&&ignore!=='nav'&&!placement){for(const other of [G.player,...G.enemies]){if(other===ignore||other.dead>0||other.dead===true||!other.pos)continue;const rr=other.d?.size||.35;if(Math.abs(other.pos.y-y)>h)continue;const d=Math.hypot(x-other.pos.x,z-other.pos.z);if(d<r+rr&&(!ignore.pos||d<=Math.hypot(ignore.pos.x-other.pos.x,ignore.pos.z-other.pos.z)))return true;}}return false;}
solid=function(x,z){return !inGrid(x,z);};
function walkSegment(a,b,r=.35,ignore=null,allowFall=false){const steps=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/.22));let prev=a;for(let i=1;i<=steps;i++){const t=i/steps,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t,h=heightAt(x,z);if(h>(allowFall?a.y:prev.y)+.22||(!allowFall&&Math.abs(h-prev.y)>.3)||blockedAt(x,z,allowFall?a.y:h,r,1.6,ignore))return false;const [ax,az]=worldToCell(prev),[bx,bz]=worldToCell(V3(x,0,z));if(pendingWall&&wallCrossing(ax,az,bx,bz))return false;prev=V3(x,h,z);}return true;}
tryMove=function(pos,dx,dz){const actor=pos===G.player.pos?G.player:G.enemies.find(e=>e.pos===pos),r=actor?.d?.size||.35;const move=(x,z)=>{const end=V3(pos.x+x,pos.y,pos.z+z);if(walkSegment(pos,end,r,actor,true)){pos.x=end.x;pos.z=end.z;if(pos!==G.player.pos&&pos.y-heightAt(pos.x,pos.z)<.15)pos.y=heightAt(pos.x,pos.z);return true;}return false;};const count=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.2));for(let i=0;i<count;i++)if(!move(dx/count,dz/count)){move(dx/count,0);move(0,dz/count);}};
// A fine flow field leaves usable space around towers inside the same tile.
function makeFlow(radius=.45){if(!G.site)return null;const step=Math.min(.8,CELL/2),site=G.site,ext=(site.r+3)*CELL;let minX=site.corePos.x-ext,maxX=site.corePos.x+ext,minZ=site.corePos.z-ext,maxZ=site.corePos.z+ext;for(const e of G.enemies)if(e.mode==='siege'&&!e.dead){minX=Math.min(minX,e.pos.x-2);maxX=Math.max(maxX,e.pos.x+2);minZ=Math.min(minZ,e.pos.z-2);maxZ=Math.max(maxZ,e.pos.z+2);}const lim=WORLD*CELL/2-.01;minX=Math.max(-lim,minX);minZ=Math.max(-lim,minZ);maxX=Math.min(lim,maxX);maxZ=Math.min(lim,maxZ);const nx=Math.ceil((maxX-minX)/step),nz=Math.ceil((maxZ-minZ)/step),len=nx*nz,dist=new Float32Array(len).fill(Infinity),height=new Float32Array(len),open=new Uint8Array(len);const point=i=>V3(minX+(i%nx+.5)*step,height[i],minZ+(Math.floor(i/nx)+.5)*step),index=(x,z)=>{const a=Math.floor((x-minX)/step),b=Math.floor((z-minZ)/step);return a>=0&&b>=0&&a<nx&&b<nz?b*nx+a:-1;};for(let i=0;i<len;i++){const p=point(i);height[i]=heightAt(p.x,p.z);open[i]=!blockedAt(p.x,p.z,height[i],radius,1.65,'nav');}
 let goal=-1,goalScore=Infinity;for(let dz=-3;dz<=3;dz++)for(let dx=-3;dx<=3;dx++){const i=index(site.corePos.x+dx*step,site.corePos.z+dz*step);if(i<0||!open[i])continue;const p=point(i),score=p.distanceToSquared(site.corePos);if(score<goalScore&&walkSegment(site.corePos,p,radius,'nav')){goal=i;goalScore=score;}}const queue=[];if(goal>=0){dist[goal]=0;queue.push(goal);}let head=0;const adjacent=i=>{const x=i%nx,z=Math.floor(i/nx);return [[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dz])=>x+dx>=0&&z+dz>=0&&x+dx<nx&&z+dz<nz?i+dx+dz*nx:-1).filter(j=>j>=0);};while(head<queue.length){const i=queue[head++],p=point(i);for(const j of adjacent(i)){if(!open[j]||dist[j]!==Infinity)continue;const q=point(j);if(Math.abs(q.y-p.y)>step*.7+.08||!walkSegment(p,q,radius,'nav'))continue;dist[j]=dist[i]+1;queue.push(j);}}
 const nearest=(p)=>{const i=index(p.x,p.z);if(i>=0&&Number.isFinite(dist[i]))return i;let best=-1,score=Infinity;for(let dz=-3;dz<=3;dz++)for(let dx=-3;dx<=3;dx++){const j=index(p.x+dx*step,p.z+dz*step);if(j<0||!Number.isFinite(dist[j]))continue;const q=point(j),d=q.distanceToSquared(p);if(d<score){best=j;score=d;}}return best;};return{point,index,nearest,dist,adjacent,step};}
computeDist=function(){const flow=makeFlow(1.26),dist={};if(!flow)return dist;for(let i=0;i<flow.dist.length;i++)if(Number.isFinite(flow.dist[i])){const p=flow.point(i),[x,z]=worldToCell(p),k=key(x,z);dist[k]=Math.min(dist[k]??Infinity,flow.dist[i]*flow.step/CELL);}if(!candidateBody&&!pendingWall){G.nav=null;G.navLarge=flow;}return dist;};
pickNext=function(e){if(!G.site)return;const radius=e.d.size;let nav;if(radius>.5){if(!G.navLarge)G.navLarge=makeFlow(1.26);nav=G.navLarge;}else nav=G.nav|| (G.nav=makeFlow(.45));if(!nav)return;const i=nav.nearest(e.pos);if(i<0){e.next=null;return;}let best=i;for(const j of nav.adjacent(i))if(nav.dist[j]<nav.dist[best])best=j;const p=nav.point(best);e.next=worldToCell(p);e.target=p;};
function buildPoint(cx,cz,point){if(!point&&typeof raycaster!=='undefined'&&raycaster){const hit=aimPoint();if(hit){const [x,z]=worldToCell(hit);if(x===cx&&z===cz)point=hit;}}const p=point?.clone()||cellToWorld(cx,cz);p.x=Math.round(p.x*4)/4;p.z=Math.round(p.z*4)/4;p.y=heightAt(p.x,p.z);return p;}
function placementReason(b,p){const [cx,cz]=worldToCell(p),c=cellAt(cx,cz),r=buildRadius(b);if(!c||!G.site||c.site!==G.site.id)return 'Outside the active bastion';const shape=footprint(b,p,'candidate');if([...nearbyBodies(p.x,p.z,r*1.5)].some(o=>!o.source?.taken&&p.y+buildHeight(b)>o.y&&p.y<o.y+o.h&&bodiesOverlap(shape,o)))return 'Footprints overlap another object';for(const [dx,dz]of [[r,0],[-r,0],[0,r],[0,-r]]){const [x,z]=worldToCell(V3(p.x+dx,0,p.z+dz));if(cellAt(x,z)?.site!==G.site.id||Math.abs(heightAt(p.x+dx,p.z+dz)-p.y)>.12)return 'The whole footprint needs level ground inside the bastion';}if(p.distanceTo(G.player.pos)<r+.4)return 'Move away from this footprint';if(G.enemies.some(e=>!e.dead&&p.distanceTo(e.pos)<r+e.d.size))return 'An enemy occupies this footprint';const k='body/'+b.id+'/'+p.x+'/'+p.z;if(!placementCache.has(k)){candidateBody=footprint(b,p,'candidate');try{placementCache.set(k,b.trap||routeOpen(computeDist()));}finally{candidateBody=null;}}return placementCache.get(k)?'':'Leave enough space for the largest siege enemies to reach the core';}
const edgeCanPlace=canPlace,edgePlace=place,edgeSell=sell;
canPlace=function(b,x,z,point){return b.wall?edgeCanPlace(b,x,z,point):!placementReason(b,buildPoint(x,z,point?.isVector3?point:null));};
place=function(b,x,z,point){if(b.wall){edgePlace(b,x,z,point);rebuildCollision();if(G.site)refreshRoutes();return;}const p=buildPoint(x,z,point?.isVector3?point:null),reason=placementReason(b,p),cost=buildCost(b);if(reason||G.gold<cost){log(reason||'Not enough gold');return;}const [tx,tz]=worldToCell(p);const t={b,cx:tx,cz:tz,pos:p,paid:cost,freePlaced:true,cd:0,mesh:towerMesh(b)};t.mesh.position.copy(p);G.world.add(t.mesh);G.towers.push(t);if(!G.cells[tx][tz].tower)G.cells[tx][tz].tower=t;G.gold-=cost;G.placedCount[b.id]=(G.placedCount[b.id]||0)+1;rebuildCollision();refreshRoutes();updateHud();};
sell=function(x,z,side){if(side){edgeSell(x,z,side);rebuildCollision();if(G.site)refreshRoutes();return;}const p=buildPoint(x,z),t=G.towers.filter(t=>!t.edge&&p.distanceTo(t.pos)<buildRadius(t.b)+.25).sort((a,b)=>p.distanceTo(a.pos)-p.distanceTo(b.pos))[0];if(!t){edgeSell(x,z);rebuildCollision();if(G.site)refreshRoutes();return;}if(!G.site||cellAt(t.cx,t.cz).site!==G.site.id){log('That belongs to a secured bastion');return;}G.gold+=Math.round((t.paid??buildCost(t.b))*.6);G.placedCount[t.b.id]--;G.towers.splice(G.towers.indexOf(t),1);G.world.remove(t.mesh);G.cells[t.cx][t.cz].tower=G.towers.find(o=>!o.edge&&o.cx===t.cx&&o.cz===t.cz)||null;rebuildCollision();refreshRoutes();updateHud();};
const oldPreviewWall=previewWall;
previewWall=function(){oldPreviewWall();if(!G?.buildMode||!G.site||BUILDS[G.selected].wall)return;const hit=aimPoint();if(!hit)return;const [x,z]=worldToCell(hit),b=BUILDS[G.selected],p=buildPoint(x,z,hit),r=buildRadius(b),reason=placementReason(b,p);G.cursor.visible=true;G.cursor.position.copy(p).add(V3(0,.1,0));G.cursor.scale.set(r*2/(CELL-.1),1,r*2/(CELL-.1));G.cursor.material.color.setHex(!reason&&G.gold>=buildCost(b)?0x4ea88c:0xb2372f);$('tip').textContent=reason||b.name+' · '+buildCost(b)+' gold · quarter-meter snap · click/F place';};
// Local A* for roaming enemies when a straight route meets scenery or a wall.
function localRoute(from,to,r){const step=.7,minX=Math.min(from.x,to.x)-4,minZ=Math.min(from.z,to.z)-4,nx=Math.ceil((Math.abs(from.x-to.x)+8)/step),nz=Math.ceil((Math.abs(from.z-to.z)+8)/step);if(nx*nz>14000)return [];const idx=p=>clamp(Math.floor((p.z-minZ)/step),0,nz-1)*nx+clamp(Math.floor((p.x-minX)/step),0,nx-1),point=i=>{const p=V3(minX+(i%nx+.5)*step,0,minZ+(Math.floor(i/nx)+.5)*step);p.y=heightAt(p.x,p.z);return p;},start=idx(from),end=idx(to),cost=new Map([[start,0]]),parent=new Map(),queue=[start],closed=new Set();let found=-1,iterations=0;while(queue.length&&iterations++<4500){let best=0;for(let j=1;j<queue.length;j++)if(cost.get(queue[j])+point(queue[j]).distanceTo(to)<cost.get(queue[best])+point(queue[best]).distanceTo(to))best=j;const i=queue.splice(best,1)[0];if(i===end||point(i).distanceTo(to)<r+.8){found=i;break;}closed.add(i);const p=point(i),x=i%nx,z=Math.floor(i/nx);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){if(x+dx<0||z+dz<0||x+dx>=nx||z+dz>=nz)continue;const n=i+dx+dz*nx;if(closed.has(n))continue;const q=point(n);if(!walkSegment(p,q,r,'nav'))continue;const c=cost.get(i)+step;if(c<(cost.get(n)??Infinity)){cost.set(n,c);parent.set(n,i);if(!queue.includes(n))queue.push(n);}}}const path=[];for(let i=found;i>=0&&i!==start;i=parent.get(i)??-1){path.unshift(point(i));if(path.length>200)break;}return path;}
function roamDirection(e,desired){const goal=e.aggro?G.player.pos:e.home;if(!goal||desired.lengthSq()<.01)return desired;if(walkSegment(e.pos,goal,e.d.size,'nav')){e.detour=null;return desired;}if(!e.detour||e.detourUntil<G.time||e.detourGoal?.distanceTo(goal)>2){e.detour=localRoute(e.pos,goal,e.d.size);e.detourGoal=goal.clone();e.detourUntil=G.time+2;}while(e.detour?.length&&e.detour[0].distanceTo(e.pos)<.35)e.detour.shift();return e.detour?.length?e.detour[0].clone().sub(e.pos):desired;}

function supportHeight(pos,previousY){let floor=heightAt(pos.x,pos.z);for(const b of nearbyBodies(pos.x,pos.z,.05)){if(b.source?.taken)continue;const top=b.y+b.h;if(previousY>=top-.05&&top>floor&&overlapsBody(b,pos.x,pos.z,.02))floor=top;}return floor;}

const geometricWallPlacement=wallPlacement;
wallPlacement=function(x,z,side){if(!WALL_SIDES[side])return 'Choose a wall side';const p=cellToWorld(x,z),[dx,dz]=WALL_SIDES[side],wall={x:p.x+dx*CELL/2,z:p.z+dz*CELL/2,y:heightAt(p.x,p.z),r:0,h:2.25,hx:dx?.14:CELL/2+.12,hz:dz?.14:CELL/2+.12,source:'wall-candidate'};
 for(const b of nearbyBodies(wall.x,wall.z,CELL/2+.5)){if(b.source?.edge||b.source?.taken)continue;if(b.y+b.h<=wall.y||b.y>=wall.y+wall.h)continue;const overlap=b.hx!==undefined?Math.abs(b.x-wall.x)<b.hx+wall.hx&&Math.abs(b.z-wall.z)<b.hz+wall.hz:overlapsBody(wall,b.x,b.z,b.r);if(overlap)return 'The wall overlaps another object';}
 candidateBody=wall;try{return geometricWallPlacement(x,z,side);}finally{candidateBody=null;}};
