/* Seeded voxel recipes: shared geometry, articulated parts, no external model assets. */
const voxelCache=new Map();
function voxelGeometry(nx,ny,nz,seed,shape='box'){const key=[nx,ny,nz,seed,shape].join('/');if(voxelCache.has(key))return voxelCache.get(key);const cube=new THREE.BoxGeometry(1,1,1).toNonIndexed(),p=cube.attributes.position,n=cube.attributes.normal,vertices=[],normals=[],colors=[],rng=mulberry32(hashStr(key)),filled=(x,y,z)=>x>=0&&y>=0&&z>=0&&x<nx&&y<ny&&z<nz&&(shape==='box'||Math.pow((x+.5-nx/2)/(nx/2),2)+Math.pow((y+.5-ny/2)/(ny/2),2)+Math.pow((z+.5-nz/2)/(nz/2),2)<1.15);for(let x=0;x<nx;x++)for(let y=0;y<ny;y++)for(let z=0;z<nz;z++){if(!filled(x,y,z))continue;const shade=.76+rng()*.24;for(let face=0;face<6;face++){const j=face*6,dx=n.getX(j),dy=n.getY(j),dz=n.getZ(j);if(filled(x+dx,y+dy,z+dz))continue;for(let v=j;v<j+6;v++){vertices.push((x+.5-nx/2+p.getX(v))*.11,(y+.5+p.getY(v))*.11,(z+.5-nz/2+p.getZ(v))*.11);normals.push(dx,dy,dz);const eye=shape==='head'&&dz===1&&y>=ny-3&&y<=ny-2&&(x===1||x===nx-2);colors.push(eye?.18:shade,eye?.22:shade,eye?.14:shade);}}}cube.dispose();const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeBoundingSphere();voxelCache.set(key,geo);return geo;}
const CREATURE_RECIPES={grunt:{body:0x8b8365,head:0xb3a888},runner:{body:0x7ea34b,head:0xadbd70,lean:1},brute:{body:0x776458,head:0xa79a7d,bulk:1.3},stalker:{body:0x615375,head:0x9188af,lean:1},spitter:{body:0x769a47,head:0xb2b970},bulwark:{body:0x73838f,head:0x99a3a4,bulk:1.25},bomber:{body:0xca763b,head:0xedd278},frostling:{body:0x65abb8,head:0xb4e5e7},shaman:{body:0x9c609f,head:0xb29aaf},boss:{body:0x993e35,head:0xd6aa82,bulk:1.3},laborer:{body:0xa98c5d,head:0xc7a982},knight:{body:0x869ba9,head:0xbbc5ce},ranger:{body:0x547958,head:0xc0a484},pyromancer:{body:0x9f504c,head:0xd3b596}};
for(const [kind,recipe]of Object.entries(CREATURE_RECIPES))recipe.archetype=kind;
function voxelCreature(kind,seed=kind){const spec=CREATURE_RECIPES[kind]||CREATURE_RECIPES.grunt,group=new THREE.Group(),parts={},mat=color=>new THREE.MeshStandardMaterial({color,vertexColors:true,roughness:.92});const bodyMat=mat(spec.body),skin=mat(spec.head);const part=(name,x,y,z,nx,ny,nz,material,shape='box')=>{const mesh=new THREE.Mesh(voxelGeometry(nx,ny,nz,String(seed).slice(0,30)+name,shape),material);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;mesh.name=name;group.add(mesh);parts[name]=mesh;return mesh;};part('torso',0,.55,0,spec.bulk?7:5,7,4,bodyMat);part('head',0,1.3,0,5,5,5,skin,'head');part('legL',-.18,0,0,2,5,3,bodyMat);part('legR',.18,0,0,2,5,3,bodyMat);part('armL',-.4,.65,0,2,6,2,bodyMat);part('armR',.4,.65,0,2,6,2,bodyMat);if(kind==='ranger'||kind==='stalker')part('hood',0,1.69,-.1,6,2,5,bodyMat);if(kind==='knight'||kind==='bulwark')part('shield',-.45,.7,.2,1,7,5,bodyMat);if(kind==='shaman'||kind==='pyromancer')part('staff',.47,.1,.15,1,16,1,skin);const archetype=spec.archetype||kind;if(['grunt','runner','stalker'].includes(archetype)){part('earL',-.3,1.55,0,1,4,2,skin);part('earR',.3,1.55,0,1,4,2,skin);}if(['brute','bulwark'].includes(archetype)){part('hornL',-.23,1.8,0,2,4,2,skin);part('hornR',.23,1.8,0,2,4,2,skin);parts.armL.scale.set(1.4,1,1.4);parts.armR.scale.set(1.4,1,1.4);}if(archetype==='spitter')part('venomSack',0,.6,-.35,6,5,5,skin,'round');if(archetype==='bomber'){const fuse=part('fuse',0,1.83,0,1,4,1,skin);fuse.material=fuse.material.clone();fuse.material.emissive.setHex(0xff8022);fuse.material.emissiveIntensity=.7;}if(archetype==='frostling')for(const x of [-.3,0,.3])part('ice'+x,x,1.7,-.1,1,5,1,skin);// Limb geometry hangs down from a joint, rather than rotating around a foot.
for(const name of ['legL','legR','armL','armR']){const limb=parts[name],length=name.startsWith('leg')?.55:.66;limb.geometry=limb.geometry.clone();limb.geometry.translate(0,-length,0);limb.position.y+=length;}
const attach=(name,parent)=>{if(!parts[name])return;parts[name].position.sub(parent.position);parent.add(parts[name]);};
for(const name of ['hood','earL','earR','hornL','hornR','fuse','ice-0.3','ice0','ice0.3'])attach(name,parts.head);
attach('shield',parts.armL);attach('staff',parts.armR);
group.userData.arm=parts.armR;group.userData.parts=Object.values(parts);group.userData.voxelParts=parts;group.userData.recipe=kind;return group;}
function registerCreatureRecipe(id,spec,remember=true){if(!/^[a-z][a-z0-9_-]{0,30}$/.test(id)||ENEMIES[id])throw Error('Choose a new creature identifier');const base=ENEMIES[spec.base]||ENEMIES.grunt;ENEMIES[id]={...base,hp:clamp(Number(spec.hp)||base.hp,10,5000),spd:clamp(Number(spec.speed)||base.spd,.3,8),color:spec.color??base.color};names[id]=String(spec.name||id).slice(0,60);CREATURE_RECIPES[id]={...(CREATURE_RECIPES[spec.base]||CREATURE_RECIPES.grunt),body:spec.color??base.color,head:spec.headColor??0xb9a283};if(remember&&G){colony().species??={};colony().species[id]={...spec};}return id;}
const voxelEnemySpawn=spawnEnemy;
spawnEnemy=function(type,gate,scale){const e=voxelEnemySpawn(type,gate,scale);if(!e||e.rift||type==='watchtower')return e;const old=e.mesh,model=voxelCreature(type,type);old.remove(e.hb);model.add(e.hb);model.scale.setScalar(Math.max(.65,e.d.size*2));e.hb.position.y=2.1;model.position.copy(e.pos);G.world.remove(old);G.world.add(model);e.mesh=model;e.body=model.getObjectByName('torso');return e;};
workerMesh=function(role){return voxelCreature(CREATURE_RECIPES[role]?role:'laborer');};
makePlayerMesh=function(){return voxelCreature(G.classId);};
function animateVoxelActor(actor,dt){const model=actor.mesh||G.playerMesh,parts=model?.userData.voxelParts;if(!parts)return;const moved=actor.voxelLast?actor.pos.distanceTo(actor.voxelLast):0;actor.voxelLast=actor.pos.clone();const gait=clamp(moved/Math.max(dt,.001)/3,0,1),phase=G.time*(actor.role==='laborer'?8:10),work=/building|collecting|resetting/.test(actor.state||'');parts.legL.rotation.x=Math.sin(phase)*.55*gait;parts.legR.rotation.x=-Math.sin(phase)*.55*gait;parts.armL.rotation.x=-Math.sin(phase)*.4*gait;parts.armR.rotation.x=actor.swing>0||actor.workSwing>G.time||work?-.7+Math.sin(G.time*14)*.6:Math.sin(phase)*.4*gait;parts.armR.rotation.y=0;parts.head.rotation.y=Math.sin(G.time*.7+actor.pos.x)*.06;}
const voxelMotion=updatePlayer;
updatePlayer=function(dt){voxelMotion(dt);animateVoxelActor(G.player,dt);for(const w of economy().workers)animateVoxelActor(w,dt);for(const e of G.enemies){if(e.rift||e.type==='watchtower')continue;e.mesh.visible=e.pos.distanceTo(G.player.pos)<140;if(e.mesh.visible)animateVoxelActor(e,dt);}for(const c of colony().caravans||[])for(const w of [c,...c.escorts])animateVoxelActor(w,dt);};
const texturedObjectModel=towerMesh;
towerMesh=function(b){const group=texturedObjectModel(b);group.traverse(o=>{if(o.isMesh&&o.material?.isMeshStandardMaterial){o.material.flatShading=true;o.material.map??=terrainTexture(b.id==='arrow'||b.id==='house'?'bark':'rock');o.material.needsUpdate=true;}});return group;};
function voxelizeProp(group,seed){group.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||!o.geometry||!['CylinderGeometry','ConeGeometry','SphereGeometry','DodecahedronGeometry','IcosahedronGeometry'].includes(o.geometry.type))return;const old=o.geometry;old.computeBoundingBox();const bounds=old.boundingBox,size=bounds.getSize(V3()),nx=clamp(Math.round(size.x/.16),2,20),ny=clamp(Math.round(size.y/.16),2,28),nz=clamp(Math.round(size.z/.16),2,20),geo=voxelGeometry(nx,ny,nz,seed+old.type,old.type==='SphereGeometry'?'round':'box').clone();geo.scale(size.x/(nx*.11),size.y/(ny*.11),size.z/(nz*.11));geo.translate((bounds.min.x+bounds.max.x)/2,bounds.min.y,(bounds.min.z+bounds.max.z)/2);o.geometry=geo;if(o.material?.isMeshStandardMaterial){o.material.vertexColors=true;o.material.map=null;o.material.needsUpdate=true;}});return group;}
const voxelPropTower=towerMesh;towerMesh=function(b){return voxelizeProp(voxelPropTower(b),b.id);};
const voxelMoveAnimation=addMoveAnimation;addMoveAnimation=function(...args){const before=(G.moveAnimations||[]).length;const result=voxelMoveAnimation(...args);for(const effect of (G.moveAnimations||[]).slice(before))if(effect.mesh)voxelizeProp(effect.mesh,'spell');return result;};

const recipeRestore=restoreSave;restoreSave=function(save){const species=save.state?.economy?.settlement?.species||{};if(Object.keys(species).length>64)throw Error('Too many custom species');for(const [id,spec]of Object.entries(species))if(!ENEMIES[id])registerCreatureRecipe(id,spec,false);return recipeRestore(save);};window.bastion.restoreSave=restoreSave;
const speciesInstall=installIntegration;
installIntegration=function(){speciesInstall();const section=$('adminPanel').querySelector('section'),title=document.createElement('h3');title.textContent='Voxel creature laboratory';section.appendChild(title);const label=document.createElement('label');label.textContent='Creature seed';const input=document.createElement('input');input.id='creatureSeed';input.value='MOSS-GOBLIN';input.maxLength=40;label.appendChild(input);section.appendChild(label);uiButton(section,'Generate and spawn creature',()=>{const seed=input.value||'creature',hash=hashStr(seed)>>>0,id='variant_'+hash.toString(36),base=['grunt','runner','brute','shaman'][hash%4];if(!ENEMIES[id]){if(Object.keys(colony().species||{}).length>=64){log('This run already has 64 custom species');return;}registerCreatureRecipe(id,{base,name:seed,hp:35+hash%110,speed:1.5+(hash%28)/10,color:new THREE.Color().setHSL((hash%360)/360,.32,.43).getHex()});}const p=G.player.pos.clone().addScaledVector(cameraForward(),9);p.y=heightAt(p.x,p.z);const creature=frontierSpawnAt(p,id);log(creature?seed+' spawned. This recipe is stored in the save.':'Move to clear terrain before spawning this creature.');});};
