// Edge walls share an identity from either neighboring tile; centers stay independent.
const WALL_SIDES={N:[0,-1],E:[1,0],S:[0,1],W:[-1,0]};
let pendingWall=null;
function edgeKey(x,z,side){const [dx,dz]=WALL_SIDES[side];const a=key(x,z),b=key(x+dx,z+dz);return a<b?a+'|'+b:b+'|'+a;}
function wallIndex(){if(!G.wallIndex){G.wallIndex=new Map();for(const t of G.towers)if(t.edge)G.wallIndex.set(edgeKey(t.cx,t.cz,t.edge),t);}return G.wallIndex;}
function edgeBlocked(ax,az,bx,bz){const a=key(ax,az),b=key(bx,bz),k=a<b?a+'|'+b:b+'|'+a;return k===pendingWall||wallIndex().has(k);}
function wallCrossing(ax,az,bx,bz){if(ax===bx&&az===bz)return false;if(ax!==bx&&az!==bz)return edgeBlocked(ax,az,bx,az)||edgeBlocked(ax,az,ax,bz)||edgeBlocked(bx,az,bx,bz)||edgeBlocked(ax,bz,bx,bz);return edgeBlocked(ax,az,bx,bz);}
const terrainStep=stepOk;
stepOk=function(ax,az,bx,bz,extra){return !wallCrossing(ax,az,bx,bz)&&terrainStep(ax,az,bx,bz,extra);};
function wallSide(cx,cz,point){if(!point&&typeof raycaster!=='undefined'&&raycaster)point=aimPoint();if(!point)return 'N';const [px,pz]=worldToCell(point);if(px!==cx||pz!==cz)return 'N';const center=cellToWorld(cx,cz),dx=point.x-center.x,dz=point.z-center.z;return Math.abs(dx)>Math.abs(dz)?(dx>0?'E':'W'):(dz>0?'S':'N');}
function wallPlacement(cx,cz,side){const c=cellAt(cx,cz);if(!c||!G.site||c.site!==G.site.id)return 'Outside the active bastion';if(c.type==='core')return 'Keep the core clear';const [dx,dz]=WALL_SIDES[side],n=cellAt(cx+dx,cz+dz);if(!n)return 'Outside the world';if(c.ramp||!terrainPassable(cx,cz,cx+dx,cz+dz))return 'Choose a level edge, away from a cliff or ramp';if(wallIndex().has(edgeKey(cx,cz,side)))return 'This edge already has a wall';
 const cacheKey='edge/'+edgeKey(cx,cz,side);if(!placementCache.has(cacheKey)){pendingWall=edgeKey(cx,cz,side);try{placementCache.set(cacheKey,routeOpen(computeDist()));}finally{pendingWall=null;}}
 return placementCache.get(cacheKey)?'':'Keep a route from every gate to the core';}
const centeredCanPlace=canPlace;
canPlace=function(b,cx,cz,side){return b.wall?!wallPlacement(cx,cz,side||wallSide(cx,cz)):centeredCanPlace(b,cx,cz);};
function wallMesh(t){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x8c7a5c,roughness:.9}),half=CELL/2;const [dx,dz]=WALL_SIDES[t.edge];g.position.copy(t.pos);const add=(w,h,d,x,y,z)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;g.add(m);};
 for(const u of [-half,half])add(.24,2.25,.24,dx?dx*half:u,1.125,dz?dz*half:u);
 for(const y of [.65,1.65])add(dx?.18:CELL,.25,dz?.18:CELL,dx*half,y,dz*half);
 const count=Math.max(2,Math.round(CELL/.5));for(let i=1;i<count;i++){const u=-half+CELL*i/count;add(.12,1.9,.12,dx?dx*half:u,1,dz?dz*half:u);}return g;}
function invalidateWalls(){G.wallIndex=null;placementCache.clear();}
const centerPlace=place;
place=function(b,cx,cz,side){if(!b.wall)return centerPlace(b,cx,cz);side=side||wallSide(cx,cz);const reason=wallPlacement(cx,cz,side);if(reason){log(reason);return;}const cost=buildCost(b);if(G.gold<cost){log('Not enough gold');return;}const t={b,cx,cz,edge:side,paid:cost,cd:0,pos:cellToWorld(cx,cz)};t.pos.y=heightAt(t.pos.x,t.pos.z);t.mesh=wallMesh(t);G.towers.push(t);G.world.add(t.mesh);G.gold-=cost;G.placedCount[b.id]=(G.placedCount[b.id]||0)+1;invalidateWalls();refreshRoutes();updateHud();};
const centerSell=sell;
sell=function(cx,cz,side){const point=typeof raycaster!=='undefined'&&raycaster?aimPoint():null;const c=cellToWorld(cx,cz);const hitCell=point&&worldToCell(point);const nearEdge=side||point&&hitCell[0]===cx&&hitCell[1]===cz&&Math.max(Math.abs(point.x-c.x),Math.abs(point.z-c.z))>CELL*.3;
 const t=nearEdge&&wallIndex().get(edgeKey(cx,cz,side||wallSide(cx,cz,point)));if(!t){if(nearEdge){log('No wall on this edge; point at the tile center to sell its tower');return;}return centerSell(cx,cz);}if(!G.site||cellAt(t.cx,t.cz).site!==G.site.id){log('That belongs to a secured bastion');return;}const refund=Math.round((t.paid??buildCost(t.b))*.6);G.gold+=refund;G.placedCount[t.b.id]--;G.towers.splice(G.towers.indexOf(t),1);G.world.remove(t.mesh);t.mesh.traverse(o=>{o.geometry?.dispose();});t.mesh.children[0]?.material.dispose();invalidateWalls();refreshRoutes();log('Wall sold for '+refund+' gold');updateHud();};
function previewWall(){if(!G?.cursor)return;G.cursor.scale.set(1,1,1);if(G.wallOutline)G.wallOutline.visible=false;if(!G.buildMode||BUILDS[G.selected].id!=='barricade'||!G.site)return;const ap=aimPoint();if(!ap)return;const [x,z]=worldToCell(ap),side=wallSide(x,z,ap),[dx,dz]=WALL_SIDES[side],c=cellAt(x,z);G.cursor.visible=!!c&&c.site===G.site.id;if(!G.cursor.visible)return;if(!G.wallOutline){const h=CELL/2;G.wallOutline=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints([V3(-h,0,-h),V3(h,0,-h),V3(h,0,h),V3(-h,0,h)]),new THREE.LineBasicMaterial({color:0xe7dcc3,transparent:true,opacity:.7}));G.world.add(G.wallOutline);}G.wallOutline.visible=true;G.wallOutline.position.copy(cellToWorld(x,z));G.wallOutline.position.y=c.lvl*LSTEP+.04;const reason=wallPlacement(x,z,side),affordable=G.gold>=buildCost(BUILDS[G.selected]);G.cursor.scale.set(dx?.035:1,7,dz?.035:1);G.cursor.position.copy(cellToWorld(x,z));G.cursor.position.x+=dx*CELL/2;G.cursor.position.z+=dz*CELL/2;G.cursor.position.y=c.lvl*LSTEP+1;G.cursor.material.color.setHex(!reason&&affordable?0x4ea88c:0xb2372f);G.rangeRing.visible=false;$('tip').textContent=reason||(!affordable?'Not enough gold':side+' wall · '+buildCost(BUILDS[G.selected])+' gold · click/F place · point at edge + X/right-click sell');}

const baseMinimap=drawMinimap;
drawMinimap=function(){baseMinimap();const ctx=$('mini').getContext('2d'),scale=160/WORLD;ctx.strokeStyle='#d2b681';ctx.lineWidth=1.5;ctx.beginPath();for(const t of G.towers){if(!t.edge)continue;const [dx,dz]=WALL_SIDES[t.edge],x=(t.cx+.5+dx*.5)*scale,z=(t.cz+.5+dz*.5)*scale;ctx.moveTo(x-(dz?scale/2:0),z-(dx?scale/2:0));ctx.lineTo(x+(dz?scale/2:0),z+(dx?scale/2:0));}ctx.stroke();};
