const {chromium}=require('C:/Users/jchox/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4177/work/placement-qa.html');assert.equal(await page.getByRole('button',{name:/World gen/}).count(),0);await page.getByRole('button',{name:/New game Choose/}).click();const seed=page.getByPlaceholder('Leave blank for a random world');assert.equal(await seed.inputValue(),'');await seed.fill('GREEN-VALLEY');await page.getByRole('button',{name:'Continue to character'}).click();const f=page.frameLocator('iframe');await f.locator('#startBtn').click();await f.locator('#combatBar').waitFor({state:'visible'});const game=page.frames().find(f=>f.url()==='about:srcdoc');
 assert.deepEqual(await game.evaluate(()=>[RUN_SETTINGS.scale,RUN_SETTINGS.dynamic,G.seed]),[2,true,'GREEN-VALLEY']);await game.evaluate(()=>{G.admin={god:true};setView('third');G.cameraDistance=5;G.cameraPitch=-.18;});await page.waitForTimeout(400);await page.screenshot({path:'../outputs/rolling-base-qa.png'});
 await game.evaluate(()=>{const p=tilePoint(44,41);G.player.pos.copy(p);G.player.pos.y=heightAt(p.x,p.z);G.cameraYaw=1.8;G.cameraPitch=.03;G.cameraDistance=6;});await page.waitForTimeout(500);await page.screenshot({path:'../outputs/rolling-wilderness-qa.png'});
 const check=await game.evaluate(()=>{const p=G.playerMesh.userData.voxelParts,save=JSON.parse(JSON.stringify(snapshot())),size=WORLD;restoreSave(save);return {size,restored:WORLD,foliage:G.foliage.children[0].count,pivot:p.armR.position.y,seed:G.seed};});assert.equal(check.size,check.restored);assert(check.foliage>0);assert(check.pivot>1.2);
 // Read the rendered triangles back with a downward ray; collision should agree within a few centimetres.
 const error=await game.evaluate(()=>{G.terrain.updateMatrixWorld(true);let error=0;for(let i=0;i<20;i++){const x=G.player.pos.x+i*.31,z=G.player.pos.z+i*.23,h=heightAt(x,z),ray=new THREE.Raycaster(V3(x,h+5,z),V3(0,-1,0)),hit=ray.intersectObject(G.terrain)[0];if(!hit)throw Error('Missing ground');error=Math.max(error,Math.abs(hit.point.y-h));}return error;});assert(error<.04,'Visible mesh follows collision height');assert.deepEqual(errors,[]);console.log('PASS browser: simplified seed creation, 2x rolling ground, foliage, corrected shoulder pivot, render/collision agreement and save restore');
 }finally{await browser.close();}})();
