const {api:a,THREE,assert}=require('./combat-harness.cjs');
a.newRun('ranger','CAMPAIGN-QA');let g=a.getG(),eco=a.economy();g.enemies=[];g.gold=10000;eco.logs=eco.stone=eco.ore=10000;
const walls=g.towers.filter(t=>t.b.id==='barricade');assert.equal(walls.length,19);assert.equal(g.towers.filter(t=>t.b.id==='gate').length,1);assert.equal(a.builds.find(b=>b.id==='barricade').name,'Wall');
const edge=walls[0],wire=a.builds.find(b=>b.id==='wire');for(const layer of ['top','front']){a.colony().wireLayer=layer;assert.equal(a.edgeBuildReason(wire,edge.cx,edge.cz,edge.edge),'');const n=g.towers.length;a.place(wire,edge.cx,edge.cz,edge.edge);assert.equal(g.towers.length,n+1);assert(a.edgeBuildReason(wire,edge.cx,edge.cz,edge.edge));}assert.equal(g.site,null);console.log('PASS enclosed starting courtyard and two wire layers on one wall without an active siege');
const plan=g.towers.at(-1);g.player.pos.copy(a.edgeStructurePoint(plan)).add(new THREE.Vector3(0,0,1));const before=plan.construction.done;assert(a.helpBuild(plan));assert(plan.construction.done>before);assert(!a.helpBuild(plan),'Manual work cannot be spammed in one frame');console.log('PASS manual construction contributes work with a tap cooldown');
const w=eco.workers.find(w=>w.role==='laborer');g.player.pos.copy(g.sites[0].corePos).add(new THREE.Vector3(0,0,6));a.commandWorker(w,'follow');for(let i=0;i<60;i++){const before=w.pos.clone();g.time+=.1;a.updateWorkers(.1);assert(w.pos.distanceTo(before)<.65,'Follow does not teleport');assert(w.mesh.position.distanceTo(w.pos)<.001);}assert.equal(w.command,'follow');
const academy={b:a.builds.find(b=>b.id==='academy'),pos:w.pos.clone(),uid:9999,siteId:w.siteId};g.towers.push(academy);w.cargo=3;w.cargoKind='logs';assert(a.eligibleLaborers(academy).includes(w));assert(a.trainResident(academy,w.id));assert.equal(w.training.role,'pyromancer');assert.equal(w.cargo,3);g.towers.pop();w.training=null;console.log('PASS stable follow movement and academy reassignment of a following, resource-carrying laborer');
a.gainExperience(35);assert(!a.abilityUnlocked(1));assert(!a.learnTalent('0-1'));assert(a.learnTalent('0-0'));assert(a.abilityUnlocked(1));assert(!a.learnTalent('1-0'));a.gainExperience(70);assert(a.learnTalent('1-0'));console.log('PASS branching talent prerequisites, level gates and point spending');
const out=a.colony().outposts[0];assert(out);const merchant={pos:g.player.pos.clone(),hp:100,stock:{logs:2}};const gold=g.gold,logs=eco.logs;assert(a.tradeMerchant(merchant,'logs',true));assert.equal(g.gold,gold-2);assert.equal(eco.logs,logs+1);assert(a.tradeMerchant(merchant,'logs',false));assert.equal(eco.logs,logs);merchant.pos.x+=20;assert(!a.tradeMerchant(merchant,'logs',true));console.log('PASS merchant buy/sell costs, stock and interaction range');
eco.gateKits=5;a.setPos(48,32);a.foundSite();assert(g.site);const site=g.site;g.player.pos.copy(site.corePos).add(new THREE.Vector3(0,0,2));assert(a.startWave());assert(g.enemies.some(e=>e.rift&&e.portalSiteId===site.id));assert(g.spawnQueue.length>=32);assert(new Set(g.spawnQueue.map(q=>Math.round(Math.atan2(q.pos.z-site.corePos.z,q.pos.x-site.corePos.x)*100))).size>=8);g.spawnQueue=[];g.enemies=g.enemies.filter(e=>e.rift);site.wave=4;assert(!a.canFinishAssault());const rift=g.enemies[0];a.damage(rift,rift.hp+1);assert(a.canFinishAssault());console.log('PASS multi-direction siege, damageable hostile gate and final-wave gate requirement');
g.phase='build';g.player.pos.copy(g.sites[0].corePos).add(new THREE.Vector3(0,0,3));assert(a.teleportPlayer(site));assert(g.player.pos.distanceTo(site.corePos)<8);console.log('PASS teleport between living friendly portals');
const saved=JSON.parse(JSON.stringify(a.snapshot()));a.validateSave(saved);a.restoreSave(saved);g=a.getG();assert.equal(g.player.talents.length,2);assert(g.towers.some(t=>t.b.id==='wire'&&t.wireLayer==='top'));for(const t of g.towers.filter(t=>t.b.id==='wire'))assert(t.mesh.position.distanceTo(a.edgeStructurePoint(t))<.001);console.log('PASS new walls, wire offsets, residents, portals and talent save/load');

// Capture retains surviving hostile defenses instead of granting replacements.
a.newRun('knight','CAPTURE-QA');g=a.getG();eco=a.economy();const settlement=a.colony().outposts[0];assert(settlement);const survivors=g.enemies.filter(e=>e.outpostId===settlement.id&&e.type==='watchtower').length;for(const e of g.enemies.filter(e=>e.outpostId===settlement.id&&e.type!=='watchtower'))a.damage(e,e.hp*4);g.player.pos.copy(settlement.pos);const count=g.towers.length;assert(a.captureOutpost(settlement));assert.equal(g.towers.length,count+survivors);assert(settlement.captured);console.log('PASS hostile settlement capture preserves surviving buildings');
// A hand-built ramp changes the actual terrain navigation surface.
g.enemies=[];g.gold=10000;eco.logs=eco.stone=eco.ore=10000;const x=10,z=10;g.cells[x][z].lvl=0;g.cells[x][z].ramp=null;g.cells[x][z+1].lvl=1;g.cells[x][z+1].ramp=null;a.colony().rampRotation=0;const ramp=a.builds.find(b=>b.id==='ramp'),p=a.tilePoint(x,z);assert.equal(a.placementReason(ramp,p),'');a.place(ramp,x,z,p);const slope=g.towers.at(-1);assert.equal(slope.b.id,'ramp');a.finishConstruction(slope);assert.equal(g.cells[x][z].ramp,null);assert(slope.mesh.visible);console.log('PASS constructed ramp modifies the terrain used by navigation');
