const {api:a,settings,THREE,assert}=require('./combat-harness.cjs');
a.newRun('knight','COMBAT-QA');a.setPos(32,32);a.foundSite();assert(a.getG().site);a.getG().gold=100000;const g=a.getG(),arrow=a.builds.find(b=>b.id==='arrow');const p=a.cellToWorld(34,32);p.y=a.heightAt(p.x,p.z);const left=p.clone().add(new THREE.Vector3(-1.7,0,0)),right=p.clone().add(new THREE.Vector3(1.7,0,0));assert(a.canPlace(arrow,34,32,left));a.place(arrow,34,32,left);assert(a.canPlace(arrow,34,32,right));a.place(arrow,34,32,right);assert.equal(g.towers.filter(t=>t.cx===34&&t.cz===32).length,2);assert(!a.canPlace(arrow,34,32,left));assert(Number.isFinite(g.dist['34,32']),'Tile with two towers still has a traversable route');const snap=JSON.parse(JSON.stringify(a.snapshot()));a.restoreSave(snap);assert.equal(a.getG().towers.filter(t=>t.cx===34&&t.cz===32).length,2);assert(a.getG().towers[0].pos.distanceTo(left)<.1);
const tree=a.getG().generatedBodies.find(b=>b.source==='tree');assert(tree);assert(a.blockedAt(tree.x,tree.z,tree.y,.35));const rock=a.getG().generatedBodies.find(b=>b.source==='rock');assert(rock&&a.blockedAt(rock.x,rock.z,rock.y,.35));const camp=a.getG().generatedBodies.find(b=>b.source==='tent');assert(camp&&a.blockedAt(camp.x,camp.z,camp.y,.35));
console.log('PASS: several tower footprints per tile, overlap rejection, open in-tile path, precise placement saves, generated prop collision.');
for(const classId of ['knight','ranger','pyromancer']){a.newRun(classId,'COMBAT-QA');a.setPos(32,32);let g=a.getG();const e=a.spawnEnemy('brute',null,1);e.mode='roam';e.home=g.player.pos.clone();e.wanderDir=new THREE.Vector3();e.wanderT=1;e.pos.copy(g.player.pos).add(new THREE.Vector3(0,0,2));e.mesh.position.copy(e.pos);a.select(e);a.setCombatMode('target');for(let i=0;i<6;i++){g.abilityCds=[];e.dead=false;e.hp=e.maxHp;g.player.hp=g.player.maxHp-40;assert(a.castAbility(i),classId+' ability '+i);if(a.ABILITIES[classId][i][2]==='heal')assert(g.player.hp>g.player.maxHp-40);}const save=JSON.parse(JSON.stringify(a.snapshot()));a.restoreSave(save);assert.equal(a.getG().combatMode,'target');assert.equal(a.getG().abilityCds.length,save.state.abilityCds.length);}
console.log('PASS: all 18 class abilities execute; healing, target mode and cooldown saves work.');
a.newRun('ranger','COMBAT-QA');a.setPos(32,32);for(const view of ['top','third','first']){const g=a.getG();g.view=view;g.combatMode='free';g.abilityCds=[];const aim=a.abilityAim().point,origin=a.shotOrigin();assert(a.castAbility(0));const dir=g.bolts.at(-1).vel.clone().normalize(),expected=aim.sub(origin).normalize();assert(dir.dot(expected)>.999,view+' reticle trajectory');}
const g2=a.getG();g2.bolts=[];g2.abilityCds=[];const auto=a.spawnEnemy('brute',null,1);auto.pos.copy(g2.player.pos).add(new THREE.Vector3(0,0,5));auto.home=auto.pos.clone();auto.mode='roam';auto.wanderDir=new THREE.Vector3();auto.wanderT=1;a.setCombatMode('auto');a.updatePlayer(.1);assert(g2.bolts.length>0,'Auto fires without a held attack input');a.pushEnemy(auto,g2.player.pos,20);assert(auto.impulse.length()>0);auto.pos.copy(a.cellToWorld(35,35));g2.cells[35][35].lvl=3;auto.pos.y=a.heightAt(auto.pos.x,auto.pos.z);auto.pos.x+=2.9;a.pushEnemy(auto,auto.pos.clone().add(new THREE.Vector3(-2,0,0)),20);let fell=false;for(let i=0;i<200&&!auto.dead;i++){a.updateEnemyPhysics(auto,.025);if(auto.pos.y<8)fell=true;}assert(fell,'Knockback carries enemy off platform');assert(auto.cell,'Displaced enemy updates its current cell');
console.log('PASS: top/third/first reticle direction, auto attack, knockback and platform falls.');
a.installCombat();a.toggleAdmin();a.node('adminGold').value='2345';a.node('adminHealth').value='500';a.node('adminGod').checked=true;a.node('adminCooldown').checked=true;a.node('adminApply').onclick();assert.equal(g2.gold,2345);assert.equal(g2.player.maxHp,500);a.playerHit(9999);assert.equal(g2.player.hp,500);a.node('adminUpgrade').value='u_blade';const power=g2.player.melee;a.node('adminUpgradeAdd').onclick();assert.equal(g2.player.melee,power+6);a.node('adminReset').onclick();assert.equal(g2.abilityCds.length,0);a.toggleAdmin();const adminSave=JSON.parse(JSON.stringify(a.snapshot()));a.restoreSave(adminSave);assert(a.getG().admin.god);
console.log('PASS: testing menu gold/health/invulnerability/upgrade/cooldown controls and save persistence.');
// Displaced siege enemies must actually return to a route and reach the core.
for(const type of ['grunt','brute','boss']){a.newRun('knight','COMBAT-QA');a.setPos(32,32);a.foundSite();const g=a.getG();g.admin={god:true};g.site.coreHp=g.site.coreMax=100;const e=a.spawnEnemy(type,0,1);g.enemies=g.enemies.filter(o=>o===e);a.pushEnemy(e,e.pos.clone().add(new THREE.Vector3(-1,0,0)),12);for(let i=0;i<2600&&!e.dead;i++){g.time+=.05;a.updateEnemies(.05);}assert(e.dead&&g.site.coreHp<100,type+' recovers a route after displacement and reaches core');}
console.log('PASS: grunt, brute and boss recover after knockback and physically reach the core.');
// Projectiles stop at real geometry before reaching a target behind it.
a.newRun('ranger','COMBAT-QA');a.setPos(32,32);const sg=a.getG(),origin=sg.player.pos.clone();const obstacle=new THREE.Mesh(new THREE.BoxGeometry(4,4,.5),new THREE.MeshBasicMaterial());obstacle.position.copy(origin).add(new THREE.Vector3(0,2,3));sg.world.add(obstacle);const shielded=a.spawnEnemy('brute',null,1);shielded.pos.copy(origin).add(new THREE.Vector3(0,0,6));shielded.home=shielded.pos.clone();shielded.mode='roam';shielded.mesh.position.copy(shielded.pos);a.select(shielded);a.setCombatMode('target');const hp=shielded.hp;assert(a.castAbility(0));for(let i=0;i<30;i++)a.updateBolts(.02);assert.equal(shielded.hp,hp,'Wall intercepts the shot');sg.world.remove(obstacle);sg.abilityCds=[];assert(a.castAbility(0));for(let i=0;i<30;i++)a.updateBolts(.02);assert(shielded.hp<hp,'Shot reaches target when the wall is removed');
console.log('PASS: projectile line-of-sight collision and unobstructed target hits.');
