const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),THREE=require('three');
const {generateWorld}=require('../lib/world.ts');
class Element{constructor(){this.children=[];this.style={};this.dataset={};this.value='';this.classes=new Set(['hidden']);this.classList={add:s=>this.classes.add(s),remove:s=>this.classes.delete(s),contains:s=>this.classes.has(s),toggle:(s,on)=>{if(on??!this.classes.has(s))this.classes.add(s);else this.classes.delete(s);}};}set innerHTML(v){this.html=v;if(v==='')this.children=[];}get innerHTML(){return this.html||'';}appendChild(c){c.parent=this;this.children.push(c);}get firstChild(){return this.children[0];}querySelector(){return new Element();}addEventListener(){}remove(){if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);}getContext(){return new Proxy({},{get:()=>()=>{}});}}
const nodes=new Map();const document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id);},createElement:()=>new Element(),body:new Element(),pointerLockElement:null,exitPointerLock(){},addEventListener(){}};
let source=fs.readFileSync('work/bastion-integrated.js','utf8');source=source.slice(0,source.lastIndexOf('try{initThree();'));
const settings={seed:'COMBAT-QA',size:64,hilliness:0,trees:.22,scale:1,dynamic:false};
const sandbox={parent:{__lastBastionBridge:{THREE,generateWorld,settings,started(){},notify(){},menu(){},save(){return true;}}},document,console,innerWidth:1200,innerHeight:800,devicePixelRatio:1,setTimeout:()=>0,setInterval:()=>0,requestAnimationFrame:()=>0,addEventListener(){}};sandbox.window=sandbox;
vm.createContext(sandbox);vm.runInContext(source+`\nscene=new THREE.Scene();camera=new THREE.PerspectiveCamera();sun=new THREE.DirectionalLight();renderer={render(){}};globalThis.api={worldToCell,gridPlan,tilePoint,commandWorker,sellStructure,harvestNode,interactables,toggleAutomatic,chooseTarget,clearTarget,abilityOutOfRange,buildTerrainMesh,cornerHeights,updateCombatUI,economy,summonWorker,updateWorkers,craftPortal,upgradeEconomy,updateAutomaticAbilities,createClaimNodes,coreReason,activateAbility,clickWorld,updateCamera,selectCore,previewWall,placementReason,updateAbilityEffects,bindInput,getCamera:()=>camera,setKeys:k=>keys=k,getKeys:()=>keys,castAbility,sceneAim,abilityAim,shotOrigin,setCombatMode,updateEnemyPhysics,pushEnemy,blockedAt,walkSegment,buildRadius,makeFlow,projectileObstacle,rebuildCollision,installCombat,toggleAdmin,playerHit,ABILITIES,select:e=>selectedEnemy=e,pause:p=>menuPaused=p,node:id=>document.getElementById(id),stepOk,edgeKey,wallPlacement,jumpPlayer,tryMove,updatePlayer,expandTerrain,toggleBuildMode,newRun,foundSite,startWave,spawnEnemy,damage,place,sell,canPlace,secureSite,snapshot,restoreSave,validateSave,openDraft,closeDraft,updateEnemies,updateTowers,updateBolts,makeWave,terrainPassable,cellToWorld,heightAt,getG:()=>G,builds:BUILDS,setPos:(x,z)=>{G.player.pos=cellToWorld(x,z);G.player.pos.y=heightAt(G.player.pos.x,G.player.pos.z);}};`,sandbox);

module.exports={api:sandbox.api,settings,THREE,assert};
