process.env.GAME_SCALE='4';
const {api:a,THREE,assert}=require('./combat-harness.cjs');
a.newRun('ranger','EXPEDITION-QA');let g=a.getG(),eco=a.economy();assert.equal(a.cellToWorld(10,10).distanceTo(a.cellToWorld(11,10)),24);assert.equal(g.towers.filter(t=>t.b.id==='arrow').length,2);assert(g.towers.filter(t=>t.b.id==='arrow').every(t=>a.assignedGunner(t)?.role==='ranger'));assert(a.colony().landmarks.some(l=>l.kind==='water'));assert(a.colony().landmarks.some(l=>l.kind==='village'));assert(a.colony().landmarks.some(l=>l.kind==='dungeon'));assert(g.playerMesh.userData.voxelParts);console.log('PASS 4x world, human-scale towers with ranger crews, voxel player and seeded exploration landmarks');
g.enemies=[];g.gold=10000;eco.logs=eco.stone=eco.ore=10000;const x=10,z=10;for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++){g.cells[x+dx][z+dz].lvl=0;g.cells[x+dx][z+dz].ramp=null;}g.cells[x][z+1].lvl=1;a.colony().rampRotation=0;const p=a.tilePoint(x,z),b=a.builds.find(b=>b.id==='ramp');a.place(b,x,z,p);const stairs=g.towers.at(-1);assert.equal(stairs.b.name,'Wall stairs');a.finishConstruction(stairs);const points=a.stairWaypoints(stairs);assert.equal(points[1].y-points[0].y,12);assert.equal(g.cells[x][z].ramp,null,'Stairs do not reshape the entire tile');assert(a.walkSegment(points[0],points[1],.27,'nav'),'Flight is traversable');assert(a.walkSegment(points[1],points[2],.27,'nav'),'Top landing reaches upper terrain');assert.equal(a.heightAt(p.x,p.z),0,'Tile center stays on the ground');assert.equal(a.supportHeight(p,20),0,'No invisible support across the tile');console.log('PASS side-running stairs rise 12m, connect their landing and preserve the rest of the tile');
// A diagonal point contact is not a walkable bridge.
for(const [dx,dz,h]of [[0,0,1],[1,1,1],[1,0,0],[0,1,0]])g.cells[20+dx][20+dz].lvl=h;const q=a.tilePoint(20,20),corner=q.clone().add(new THREE.Vector3(11.9,0,11.9)),end=q.clone().add(new THREE.Vector3(12.1,0,12.1));assert(!a.walkSegment(corner,end,.35,'nav'));assert(a.blockedAt(q.x+12.1,q.z+12.1,0,.35),'Capsule cannot squeeze between tall corner faces');console.log('PASS raised platforms touching at a point do not form a bridge or a capsule-sized gap');
const tower=g.towers.find(t=>t.b.id==='arrow'),gunner=a.assignedGunner(tower);a.commandWorker(gunner,'follow');assert(!a.assignedGunner(tower));assert(!a.staffDefense(tower,eco.workers.find(w=>w.role==='laborer').id));assert(a.staffDefense(tower,gunner.id));const trap={b:a.builds.find(b=>b.id==='spike'),pos:g.player.pos.clone(),needsReset:true};a.resetTrap(trap);assert(trap.needsReset);a.resetTrap(trap);assert(trap.needsReset);a.resetTrap(trap);assert(!trap.needsReset);console.log('PASS defense class requirements, release on orders and manual trap reset work');
const id=a.registerCreatureRecipe('test_goblin',{base:'runner',name:'Test Goblin',hp:50,speed:3,color:0x668877});const e=a.spawnEnemy(id,null,1);assert(e.mesh.userData.voxelParts);assert.equal(e.maxHp,50);e.pos.copy(g.player.pos).add(new THREE.Vector3(10,0,0));a.damage(e,1);assert.equal(e.aggroId,'player');console.log('PASS dynamically registered voxel species and damage-triggered aggro');
// Test normal saved species; custom recipes are serialized by the expedition layer.
const saved=JSON.parse(JSON.stringify(a.snapshot()));a.restoreSave(saved);g=a.getG();assert(a.colony().landmarks.length);assert(g.towers.find(t=>t.stairsVersion));assert(g.playerMesh.userData.voxelParts);assert(g.enemies.find(e=>e.type==='test_goblin'));console.log('PASS stairs, crew assignments, landmarks and voxel model save restoration');
