const {api:a,THREE,assert}=require('./combat-harness.cjs');
a.newRun('ranger','COMBAT-QA');a.setPos(32,32);let g=a.getG();g.view='third';g.cameraYaw=.72;g.cameraPitch=-.31;a.updateCamera();const before=a.getCamera().position.clone(),rotation=a.getCamera().quaternion.clone();
a.activateAbility(1);assert.equal(g.bolts.length,0,'Free aim selects without firing');assert.equal(g.activeAbility,1);a.clickWorld();assert.equal(g.bolts.length,5,'LMB fires selected split shot');a.updateCamera();assert(before.distanceTo(a.getCamera().position)<1e-9);assert(rotation.angleTo(a.getCamera().quaternion)<1e-6,'Attacks leave camera unchanged');
for(const view of ['first','third','top']){g.view=view;a.toggleBuildMode();assert.equal(g.view,view);a.toggleBuildMode();assert.equal(g.view,view);}
a.setCombatMode('target');const e=a.spawnEnemy('brute',null,1);e.pos.copy(g.player.pos).add(new THREE.Vector3(0,0,5));a.select(e);g.abilityCds=[];const count=g.bolts.length;a.activateAbility(0);assert.equal(g.bolts.length,count+1);a.activateAbility(3);assert.equal(g.armedArea,3);assert(!(g.skills||[]).some(s=>s.type==='snare'),'Target AoE waits for ground confirmation');a.clickWorld();assert(g.skills.some(s=>s.type==='snare'));
console.log('PASS: free selection/LMB firing, target activation/AoE arming, camera independence and view preservation.');
a.newRun('knight','COMBAT-QA');a.setPos(32,32);a.foundSite();g=a.getG();const nav=g.navLarge,arrow=a.builds.find(b=>b.id==='arrow'),start=performance.now();for(let i=0;i<1000;i++){const p=a.cellToWorld(34,32);p.x+=(i%20)*.25-2.5;p.z+=Math.floor(i/20)%20*.25-2.5;a.placementReason(arrow,p);}const elapsed=performance.now()-start;assert.equal(g.navLarge,nav);assert(elapsed<1000,'1000 previews must stay below one second, got '+elapsed);console.log('PASS: 1,000 build previews in '+elapsed.toFixed(1)+'ms, without navigation rebuilds.');
a.newRun('knight','COMBAT-QA');g=a.getG();const tree=g.generatedBodies.find(b=>b.source==='tree');g.player.pos.set(tree.x,tree.y+tree.h+.2,tree.z);g.player.vy=-5;for(let i=0;i<120;i++)a.updatePlayer(.025);assert(Math.hypot(g.player.pos.x-tree.x,g.player.pos.z-tree.z)>tree.r+.34,'Falling player is deflected out of tree');
console.log('PASS: falling into a tree crown does not embed the player.');
a.newRun('knight','COMBAT-QA');a.setPos(32,32);g=a.getG();const player=g.player.pos.clone();a.selectCore();const core=a.builds.find(b=>b.core);g.player.pos.x-=12;player.copy(g.player.pos);a.place(core,32,32);assert(g.site,'Core placed at cursor cell');assert(g.player.pos.equals(player),'Core placement does not move player');assert.equal(g.site.core[0],32);console.log('PASS: core is a placeable structure and leaves player position unchanged.');
