process.env.GAME_PLATEAUS='1';process.env.GAME_SCALE='2';
const {api:a,assert,THREE}=require('./combat-harness.cjs');const {generateWorld}=require('../lib/world.ts');
const world=generateWorld({seed:'PLATEAU-QA',size:64,scale:2,hilliness:.15,trees:.22,terrainMode:'plateaus'});assert(world.stats.ramps>50);assert.equal(world.stats.reachable,4096);assert(world.cells.every(c=>Number.isInteger(c.h)));console.log('PASS original connected plateau topology, integer levels and ramps');
a.newRun('ranger','PLATEAU-QA');let g=a.getG();assert.equal(g.towers.filter(t=>t.b.id==='arrow').length,2);assert(g.towers.some(t=>t.b.id==='house'));const ramps=g.cells.flat().filter(c=>c.ramp).length;assert(ramps>50);
// Controlled cliff and landing, with generated object collision removed only in this test area.
for(let x=10;x<16;x++)for(let z=10;z<16;z++){g.cells[x][z].lvl=0;g.cells[x][z].ramp=null;}for(let x=10;x<16;x++)for(let z=13;z<16;z++)g.cells[x][z].lvl=1;
g.cells[12][12].ramp=[0,1];g.generatedBodies=g.generatedBodies.filter(b=>{const [x,z]=a.worldToCell(new THREE.Vector3(b.x,0,b.z));return x<10||x>=16||z<10||z>=16;});a.rebuildCollision();
const base=a.tilePoint(12,12),foot=base.clone().add(new THREE.Vector3(0,0,-6.1)),crest=base.clone().add(new THREE.Vector3(0,0,6.1));foot.y=a.heightAt(foot.x,foot.z);crest.y=a.heightAt(crest.x,crest.z);assert(a.walkSegment(foot,crest,.35,'nav'),'Player walks the eased ramp and both landings');assert(a.walkSegment(foot,crest,.27,'nav'),'Resident walks ramp');
const high=a.tilePoint(14,13),rim=a.plateauSurface(14,13,high.x,high.z-6)-a.plateauVariation(high.x,high.z-6),inside=a.plateauSurface(14,13,high.x,high.z-4)-a.plateauVariation(high.x,high.z-4);assert(inside===6);assert(rim>5.5&&rim<6,'Rounding stays within the cliff rim');assert(!a.terrainPassable(14,12,14,13),'Vertical cliff is not a walking connection');
let lo=Infinity,hi=-Infinity;for(let i=0;i<50;i++){const h=a.plateauVariation(150+i,90+i*.3);lo=Math.min(lo,h);hi=Math.max(hi,h);}assert(hi-lo>.05&&hi-lo<.37,'Plain relief stays subtle');console.log('PASS rounded lips, subtle plain relief and walkable eased ramps; cliffs remain cliffs');
const p=a.tilePoint(12,12),before={height:a.heightAt(p.x,p.z),towers:g.towers.length,ramps:g.cells.flat().filter(c=>c.ramp).length};a.expandTerrain();g=a.getG();assert.equal(g.cells.length,80);assert.equal(a.heightAt(p.x,p.z),before.height);assert.equal(g.towers.length,before.towers);assert(g.cells.flat().filter(c=>c.ramp).length>=before.ramps);const save=JSON.parse(JSON.stringify(a.snapshot()));a.restoreSave(save);assert.equal(a.heightAt(p.x,p.z),before.height);console.log('PASS plateau expansion and save restoration preserve ramps, heights and buildings');
