const {api:a,THREE,assert}=require('./combat-harness.cjs');
a.newRun('ranger','SETTLEMENT-QA');let g=a.getG(),eco=a.economy();assert.equal(g.sites.length,1);assert.equal(g.site,null);assert.equal(g.sites[0].status,'secured');assert.equal(g.towers.filter(t=>!t.edge).map(t=>t.b.id).sort().join(','),'arrow,arrow,house');assert.equal(eco.workers.length,4);assert.equal(eco.workers.filter(w=>w.role==='laborer').length,2);assert(g.enemies.length>0);assert(g.enemies.every(e=>e.mode==='wild'&&!a.noSpawnAt(e.pos)));assert.equal(g.lairs.length,0);assert(!eco.nodes.some(n=>n.cache));assert.equal(g.player.level,1);assert(a.abilityUnlocked(0));assert(!a.abilityUnlocked(1));assert.equal(a.castAbility(1),false);a.gainExperience(35);assert.equal(g.player.level,2);assert(!a.abilityUnlocked(1));assert(a.learnTalent('0-0'));assert(a.abilityUnlocked(1));assert(!a.abilityUnlocked(2));assert.equal(g.terrain.geometry.groups.length,2,'Two terrain batches, not per-triangle draw calls');
console.log('PASS starting settlement, roaming spawn wards, environmental-only nodes, levels and batched terrain textures');
// Find a legal plan near the gate, and verify costs, travel, construction and staffing.
g.gold=5000;eco.logs=eco.stone=eco.ore=500;g.enemies=[];const mine=a.builds.find(b=>b.id==='mine');let built=null;for(let x=28;x<37&&!built;x++)for(let z=28;z<37&&!built;z++){const p=a.cellToWorld(x,z);p.y=a.heightAt(p.x,p.z);if(!a.placementReason(mine,p)){const n=g.towers.length;a.place(mine,x,z,p);if(g.towers.length>n)built=g.towers.at(-1);}}assert(built?.construction);assert.equal(built.construction.done,0);const laborers=eco.workers.filter(w=>w.role==='laborer');for(const w of laborers)a.commandWorker(w,'stay');for(let i=0;i<20;i++){g.time+=.1;a.updateWorkers(.1);}assert.equal(built.construction.done,0,'No building without labor');a.commandWorker(laborers[0],'work');const before=laborers[0].pos.clone();for(let i=0;i<2500&&built.construction;i++){g.time+=.1;a.updateWorkers(.1);}assert(!built.construction,'Laborer travels and completes build');assert(before.distanceTo(laborers[0].pos)>.5);assert(a.staffBuilding(built));const ore=eco.ore;for(let i=0;i<500;i++){g.time+=.1;a.updateWorkers(.1);}assert(eco.ore>ore,'Staffed mine generates ore');
console.log('PASS paid blueprints remain inactive without labor; travel, construction and staffed mine output');
// House recruitment consumes gold and respects local beds.
const home=g.towers.find(t=>t.b.id==='house');home.recruitTime=89.9;const population=eco.workers.length;a.updateWorkers(.2);assert.equal(eco.workers.length,population+1);assert(eco.workers.at(-1).pos.distanceTo(g.sites[0].corePos)<6);const fakeSite={...g.sites[0],id:2,corePos:g.sites[0].corePos.clone().add(new THREE.Vector3(20,0,0))};fakeSite.corePos.y=a.heightAt(fakeSite.corePos.x,fakeSite.corePos.z);g.sites.push(fakeSite);const transfer=eco.workers.at(-1);g.player.pos.copy(fakeSite.corePos);assert(a.transferResident(transfer,fakeSite));assert.equal(transfer.siteId,2);assert.equal(eco.workers.length,population+1,'Transfer does not create a resident');g.sites.pop();transfer.siteId=1;
const saved=JSON.parse(JSON.stringify(a.snapshot()));a.restoreSave(saved);g=a.getG();eco=a.economy();assert.equal(g.player.level,2);assert.equal(eco.workers.length,population+1);assert(g.towers.some(t=>t.uid===built.uid&&!t.construction));assert(eco.workers.some(w=>w.staffId===built.uid));assert.equal(g.lairs.length,0);assert(g.terrain.geometry.groups.length===2);console.log('PASS housing recruitment, gate-only resident transfer and settlement save/load');

// Training consumes a laborer and time, instead of directly spawning a guard.
const lodge=a.builds.find(b=>b.id==='barracks');let training=null;for(let x=25;x<40&&!training;x++)for(let z=25;z<40&&!training;z++){const p=a.cellToWorld(x,z);p.y=a.heightAt(p.x,p.z);if(!a.placementReason(lodge,p)){const count=g.towers.length;a.place(lodge,x,z,p);if(g.towers.length>count)training=g.towers.at(-1);}}assert(training);a.finishConstruction(training);for(const w of eco.workers){w.command=null;w.staffId=null;w.cargo=0;w.training=null;}assert(a.trainResident(training));const trainee=eco.workers.find(w=>w.training);assert.equal(trainee.role,'laborer');for(let i=0;i<2000&&trainee.training;i++){g.time+=.1;a.updateWorkers(.1);}assert.equal(trainee.role,'knight');assert(!trainee.training);console.log('PASS training requires a real laborer to reach the lodge and spend 30 seconds learning');
// A gate's own geometry must not intercept its magical defense.
g.enemies=[];const enemy=a.spawnEnemy('grunt',null,1);enemy.mode='wild';const core=g.sites[0].corePos;enemy.pos.copy(core).add(new THREE.Vector3(0,0,4));enemy.pos.y=a.heightAt(enemy.pos.x,enemy.pos.z);enemy.mesh.position.copy(enemy.pos);const hp=enemy.hp;g.sites[0].magicCd=0;for(const w of eco.workers)w.attackCd=99;a.updateWorkers(.1);assert(enemy.hp<hp,'Portal magical defense damages nearby enemy');console.log('PASS gate magical defenses fire through their own visual effects');
const node=eco.nodes.find(n=>g.generatedBodies.some(b=>Math.round(b.x*100)+','+Math.round(b.z*100)===n.id));assert(node);node.remaining=0;a.applyHarvestedNodes();assert(node.respawnAt>g.time);g.time=node.respawnAt+.1;a.applyHarvestedNodes();assert(node.remaining>0);node.remaining=0;a.applyHarvestedNodes();assert(node.respawnAt>g.time,'Repeated depletion schedules another regrowth');console.log('PASS environmental nodes regrow without creating portal resource caches');
a.setPos(48,32);a.foundSite();assert(g.site,'Expansion portal has reachable approaches');const claim=g.site,outer=claim.corePos.clone().add(new THREE.Vector3(8,0,0));outer.y=a.heightAt(outer.x,outer.z);assert(a.noSpawnAt(claim.corePos));assert(!a.noSpawnAt(outer),'Only the inner ward suppresses spawns before defense victory');a.startWave();a.updateEnemies(.1);assert(g.enemies.filter(e=>e.mode==='siege').every(e=>!a.noSpawnAt(e.pos)),'Wave enemies respect all spawn wards');const logs=eco.logs,stone=eco.stone;a.secureSite();assert(a.noSpawnAt(outer),'Victory protects full claim');assert.equal(eco.logs,logs);assert.equal(eco.stone,stone);assert(!eco.nodes.some(n=>n.cache));assert.equal(eco.ruins.length,0);console.log('PASS immediate inner ward, protected wave spawns, full-claim protection after defense and no spawned resource caches');
