process.env.GAME_PLATEAUS='1';process.env.GAME_SCALE='2';
const {api:a,assert,THREE}=require('./combat-harness.cjs');a.newRun('knight','TRAVERSAL-QA');const g=a.getG();g.enemies=[];
for(let x=8;x<17;x++)for(let z=8;z<17;z++){g.cells[x][z].lvl=z>=13?1:0;g.cells[x][z].ramp=null;}g.cells[12][12].ramp=[0,1];g.generatedBodies=[];a.rebuildCollision();
const p=a.tilePoint(12,12);g.player.pos.copy(p).add(new THREE.Vector3(0,0,-6.2));g.player.pos.y=a.heightAt(g.player.pos.x,g.player.pos.z);g.player.vy=0;const start=g.player.pos.z;
for(let i=0;i<45;i++)a.tryMove(g.player.pos,0,.32);assert(g.player.pos.z-start>13,'Low-framerate movement climbs the whole ramp without stalling');assert(Math.abs(g.player.pos.y-a.heightAt(g.player.pos.x,g.player.pos.z))<.001);console.log('PASS grounded ramp movement at large per-frame steps');
const cliff=a.tilePoint(14,12);g.player.pos.copy(cliff).add(new THREE.Vector3(0,0,5.34));g.player.pos.y=a.heightAt(g.player.pos.x,g.player.pos.z);g.cameraYaw=0;g.player.stamina=100;g.player.vy=0;a.setKeys({Space:true,KeyW:true});assert(a.beginClimb());const bottom=g.player.pos.y;for(let i=0;i<65;i++){g.time+=.05;a.advanceClimb(.05);}assert(g.player.pos.y>bottom+5,'Player scales the six-metre cliff');assert(!g.player.climbing,'Mantles onto the top');assert(g.player.stamina<70);console.log('PASS terrain wall attachment, stamina drain and ledge mantle');
g.player.pos.copy(cliff).add(new THREE.Vector3(0,0,5.34));g.player.pos.y=a.heightAt(g.player.pos.x,g.player.pos.z);g.player.stamina=1;g.player.climbDelay=0;g.player.climbExhausted=false;assert(!a.beginClimb(),'Cannot latch with negligible stamina');g.player.stamina=4;assert(a.beginClimb());for(let i=0;i<8;i++){g.time+=.05;a.advanceClimb(.05);}assert(!g.player.climbing&&g.player.climbExhausted);a.setKeys({});g.player.pos.y=a.heightAt(g.player.pos.x,g.player.pos.z);for(let i=0;i<60;i++){g.time+=.05;a.advanceClimb(.05);}assert(g.player.stamina>25&&!g.player.climbExhausted);console.log('PASS exhaustion releases the wall, grounded rest restores stamina');
const from=cliff.clone().add(new THREE.Vector3(0,3,0)),to=from.clone().add(new THREE.Vector3(0,0,14)),hit=a.physicalRay(from,to);assert(hit&&hit.z<cliff.z+6.05,'Gameplay ray hits opaque rocky cliff');
g.player.stamina=90;a.setKeys({Space:true,KeyW:true});assert(a.beginClimb());const save=JSON.parse(JSON.stringify(a.snapshot()));assert(!save.state.player.climbing);a.restoreSave(save);assert.equal(a.getG().player.stamina,90);console.log('PASS physical targeting hits cliffs and climbing saves contain no transient contact');

const restored=a.getG(),wallPos=a.tilePoint(10,10);restored.player.pos.copy(wallPos);restored.player.stamina=100;restored.player.climbDelay=0;restored.player.climbExhausted=false;restored.cameraYaw=0;restored.generatedBodies.push({x:wallPos.x,z:wallPos.z+.65,y:wallPos.y,h:2.25,hx:3,hz:.14,source:{id:'test-wall'}});a.rebuildCollision();a.setKeys({Space:true,KeyW:true});assert(a.beginClimb(),'Constructed wall supports climbing');for(let i=0;i<25;i++){restored.time+=.05;a.advanceClimb(.05);}assert(restored.player.pos.y>=wallPos.y+2.1);console.log('PASS constructed-wall climbing');
