'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {Mountain,Play,FolderOpen,SlidersHorizontal,ArrowLeft,Shield} from 'lucide-react';
import WorldLab from './world-lab';
import {generateWorld,type Settings,type World} from '@/lib/world';
import {bastionSource} from '@/lib/bastion-source';
import {parseSave,SAVE_KEY,type SaveGame} from '@/lib/save-game';
const DEFAULT:Settings={seed:'MEGABONK',size:64,hilliness:.15,trees:.22,scale:1,dynamic:false};
type Session={id:number;settings:Settings;saved:SaveGame|null};
type GameWindow=Window & {bastion?:{pause:(paused:boolean)=>void;save:()=>boolean}};
export default function Bastion(){
 const [screen,setScreen]=useState<'menu'|'world'|'game'>('menu'),[settings,setSettings]=useState<Settings>(DEFAULT),[saved,setSaved]=useState<SaveGame|null>(null),[session,setSession]=useState<Session|null>(null),[started,setStarted]=useState(false),[notice,setNotice]=useState(''),[maps,setMaps]=useState<World[]>([]),[setup,setSetup]=useState(false);const iframe=useRef<HTMLIFrameElement>(null),timeout=useRef<ReturnType<typeof setTimeout>|null>(null);
 const notify=(message:string)=>{setNotice(message);if(timeout.current)clearTimeout(timeout.current);timeout.current=setTimeout(()=>setNotice(''),6500);};
 useEffect(()=>{try{const stored=localStorage.getItem('bastion-maps-v1');if(stored)setMaps(JSON.parse(stored));const raw=localStorage.getItem(SAVE_KEY);if(raw)setSaved(parseSave(raw));}catch{notify('The saved game could not be read. You can still start a new run.');}return()=>{if(timeout.current)clearTimeout(timeout.current);};},[]);
 const menu=()=>{(iframe.current?.contentWindow as GameWindow|null)?.bastion?.pause(true);setScreen('menu');};
 const start=(load:SaveGame|null)=>{if(started)(iframe.current?.contentWindow as GameWindow|null)?.bastion?.save();const config=load?load.config:{...settings,size:Math.max(64,settings.size),scale:settings.scale??1,dynamic:settings.dynamic??false};setSetup(false);setSession({id:Date.now(),settings:config,saved:load});setStarted(false);setScreen('game');};
 useEffect(()=>{if(!session)return;const bridge={THREE,generateWorld,settings:session.settings,saved:session.saved,notify,started:()=>setStarted(true),menu,save:(value:SaveGame,silent=false)=>{try{const raw=JSON.stringify(value);const checked=parseSave(raw);localStorage.setItem(SAVE_KEY,raw);setSaved(checked);if(!silent)notify('Game saved on this device.');return true;}catch{notify('Saving failed. Browser storage may be full or unavailable; keep this run open.');return false;}}};(window as Window & {__lastBastionBridge?:unknown}).__lastBastionBridge=bridge;if(iframe.current)iframe.current.srcdoc=bastionSource;return()=>{delete (window as Window & {__lastBastionBridge?:unknown}).__lastBastionBridge;};},[session]);
 const resume=()=>{setScreen('game');(iframe.current?.contentWindow as GameWindow|null)?.bastion?.pause(false);iframe.current?.focus();};
 const exportSave=()=>{if(!saved)return;const blob=new Blob([JSON.stringify(saved)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='last-bastion-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const importSave=async(file:File|undefined)=>{if(!file)return;try{if(file.size>12000000)throw new Error('Save file is too large.');const value=parseSave(await file.text());setSaved(value);notify('Save imported. Choose Load saved game to continue.');}catch(error){notify(error instanceof Error?error.message:'Could not import this save.');}};
 return <div className="bastion-shell">
 {session&&<iframe key={session.id} ref={iframe} title="Last Bastion game" className={`game-frame ${screen==='game'?'':'game-paused'}`} allow="fullscreen; pointer-lock"/>}
 {screen==='world'&&<><WorldLab initialSettings={settings} onConfigure={setSettings} onSave={world=>{try{const next=[world,...maps].slice(0,12);localStorage.setItem("bastion-maps-v1",JSON.stringify(next));setMaps(next);setSettings({...world.settings,terrain:world});notify("Map saved. Select it in New game.");}catch{notify("Map storage is full. Remove a saved map before saving another.");}}}/><button className="return-menu" onClick={menu}><ArrowLeft size={16}/> Main menu</button></>}
 {screen==='menu'&&<><div className="menu-backdrop"><WorldLab initialSettings={settings}/></div><div className="main-menu"><div className="menu-story"><span className="menu-kicker"><Shield size={17}/> A PROCEDURAL DEFENSE ROGUELIKE</span><h1>Last<br/><em>Bastion.</em></h1><p>Find your ground.<br/>Build your defenses. Hold the line.</p><div className="menu-rule"/><span className="menu-footnote">CLAIM. DEFEND. HARVEST. EXPAND.</span></div><nav className="menu-actions" aria-label="Main menu"><span className="menu-kicker">THE WILDS ARE WAITING</span>{session&&<button className="menu-choice resume" onClick={resume}><Play/><span>{started?'Resume game':'Continue setup'}<small>Return to your current session</small></span><b>↗</b></button>}<button className="menu-choice" onClick={()=>setSetup(true)}><Shield/><span>New game<small>Choose Knight, Ranger, or Pyromancer</small></span><b>↗</b></button><button className="menu-choice" disabled={!saved} onClick={()=>saved&&start(saved)}><FolderOpen/><span>Load saved game<small>{saved?`${saved.classId} · wave ${saved.state.wave} · ${new Date(saved.savedAt).toLocaleString()}`:'No saved game on this device yet'}</small></span><b>↗</b></button><button className="menu-choice" onClick={()=>setScreen('world')}><SlidersHorizontal/><span>World gen<small>Shape the terrain for your next run</small></span><b>↗</b></button><div className="menu-settings"><Mountain size={17}/><p>Seed <strong>{settings.seed||'Random'}</strong> · {Math.max(64,settings.size)} × {Math.max(64,settings.size)}<br/>{(settings.scale??1).toFixed(2)}× terrain · {settings.hilliness.toFixed(2)} hilliness<small>Small saved maps are extended to 64 × 64 while preserving their terrain. Enable procedural expansion in New game.</small></p></div><div className="save-files"><button disabled={!saved} onClick={exportSave}>Export save</button><label>Import save<input type="file" accept=".json,application/json" onChange={e=>{void importSave(e.target.files?.[0]);e.target.value='';}}/></label></div><p className="save-note">Save anytime in-game. Autosaves every 30 seconds.<br/>Saves stay in this browser on this device.</p></nav></div></>}
 {setup&&<div className="world-setup"><section><h2>Create a new world</h2><label>Starting map<select value={settings.terrain?String(maps.indexOf(settings.terrain)):'fresh'} onChange={e=>{const w=maps[Number(e.target.value)];setSettings(w?{...w.settings,terrain:w,dynamic:settings.dynamic,maxSize:settings.maxSize}:{...settings,terrain:undefined});}}><option value="fresh">Current seed and generator settings</option>{maps.map((w,i)=><option key={i} value={i}>{w.settings.seed} · {w.settings.size} × {w.settings.size}</option>)}</select></label><label><input type="checkbox" checked={settings.dynamic??false} onChange={e=>setSettings({...settings,dynamic:e.target.checked})}/> Generate more terrain as I explore</label>{settings.dynamic&&<label>Maximum world size<select value={settings.maxSize||0} onChange={e=>setSettings({...settings,maxSize:Number(e.target.value)||undefined})}><option value={0}>No chosen limit (browser ceiling: 1024)</option>{[80,128,256,512,1024].filter(n=>n>=Math.max(64,settings.size)).map(n=><option key={n} value={n}>{n} × {n} tiles</option>)}</select></label>}<p>Existing land stays intact as new terrain appears at the edges. Larger worlds use more memory. Space jumps; B switches between combat and building; C changes targeting; Tab cycles targets.</p><div className="save-files"><button onClick={()=>start(null)}>Continue to character</button><button onClick={()=>setSetup(false)}>Cancel</button></div>{maps.length>0&&<details><summary>Saved maps ({maps.length})</summary>{maps.map((w,i)=><div key={i}>{w.settings.seed} · {w.settings.size}² <button onClick={()=>{const next=maps.filter((_,j)=>i!==j);setMaps(next);localStorage.setItem('bastion-maps-v1',JSON.stringify(next));if(settings.terrain===w)setSettings({...settings,terrain:undefined});}}>Remove</button></div>)}</details>}</section></div>}
 {notice&&<div className="app-notice" role="status">{notice}</div>}
 </div>;
}
