import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { cellHeight, heightAt, growWorld, random, TILE, RISE, MAX_SIZE, type World } from './world';
export type Explorer=ReturnType<typeof createExplorer>;
export function createExplorer(host:HTMLDivElement,onStats?:(stats:World["stats"])=>void){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D world. Drag to orbit, scroll to zoom. In Explore mode use WASD to move.');renderer.domElement.tabIndex=0;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#171b24');const camera=new THREE.PerspectiveCamera(45,1,.1,100000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=5;controls.maxDistance=50000;
 scene.add(new THREE.HemisphereLight(0x8a7fa8,0x1a1522,1.1));const sun=new THREE.DirectionalLight(0xffe2b8,1.8);sun.position.set(-60,150,70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.bias=-.001;sun.shadow.normalBias=.035;scene.add(sun);scene.add(sun.target);
 let terrain=new THREE.Group(),pathGroup=new THREE.Group(),gridGroup=new THREE.Group(),w:World|null=null,mode:'orbit'|'walk'='orbit',options={fog:true,paths:false,grid:false};scene.add(terrain,pathGroup,gridGroup);
 const keys=new Set<string>(),player=new THREE.Group();const mat=(color:number)=>new THREE.MeshStandardMaterial({color,roughness:1,flatShading:true});const coat=mat(0xf6ad45),dark=mat(0x26343c),skin=mat(0xf6d1a1);
 const body=new THREE.Mesh(new THREE.CapsuleGeometry(.36,.55,2,5),coat);body.position.y=.92;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.29,6,5),skin);head.position.y=1.65;player.add(head);const hat=new THREE.Mesh(new THREE.ConeGeometry(.48,.48,6),coat);hat.position.y=2;player.add(hat);const pack=new THREE.Mesh(new THREE.BoxGeometry(.55,.65,.3),dark);pack.position.set(0,1,.4);player.add(pack);scene.add(player);
 let vy=0,grounded=true,frame=0,last=0;const pos=new THREE.Vector3(),offset=new THREE.Vector3();
 function disposeGroup(g:THREE.Group){g.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments||o instanceof THREE.Line){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if('map' in m)(m.map as THREE.Texture|null)?.dispose();m.dispose();}}});g.clear();}
 function texture(seed:string,base:string){const c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d')!;ctx.fillStyle=base;ctx.fillRect(0,0,64,64);const r=random(seed);for(let i=0;i<850;i++){ctx.fillStyle=r()>.5?'rgba(255,239,176,.10)':'rgba(13,27,16,.13)';ctx.fillRect(Math.floor(r()*32)*2,Math.floor(r()*32)*2,2+Math.floor(r()*3),2);}const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestMipmapNearestFilter;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;return t;}
 function setWorld(world:World,preserve=false){const ratio=(world.settings.scale??1)/(w?.settings.scale??1),oldPos=pos.clone();w=world;const scale=w.settings.scale??1;disposeGroup(terrain);disposeGroup(pathGroup);disposeGroup(gridGroup);const n=w.settings.size,span=n*TILE,minX=w.originX*TILE,minZ=w.originZ*TILE;terrain.scale.setScalar(scale);pathGroup.scale.setScalar(scale);gridGroup.scale.setScalar(scale);
 const topMat=new THREE.MeshStandardMaterial({map:texture('grass','#789847'),roughness:1,side:THREE.DoubleSide});const cliffMat=new THREE.MeshStandardMaterial({map:texture('stone','#6d6b56'),roughness:1,side:THREE.DoubleSide});
 const tp:number[]=[],tu:number[]=[],sp:number[]=[],su:number[]=[],lines:number[]=[],paths:number[]=[];
 const quad=(p:number[],uv:number[],a:number[],b:number[],c:number[],d:number[],v=1)=>{p.push(...a,...b,...d,...b,...c,...d);uv.push(0,0,1,0,0,v,1,0,1,v,0,v);};
 for(const c of w.cells){const x=c.x*TILE,z=c.z*TILE;const corners=[[x,cellHeight(c,x,z),z],[x+TILE,cellHeight(c,x+TILE,z),z],[x+TILE,cellHeight(c,x+TILE,z+TILE),z+TILE],[x,cellHeight(c,x,z+TILE),z+TILE]];quad(tp,tu,corners[0],corners[3],corners[2],corners[1]);
 for(let i=0;i<4;i++){const a=corners[i],b=corners[(i+1)%4];quad(sp,su,[a[0],-4,a[2]],[b[0],-4,b[2]],b,a,(Math.max(a[1],b[1])+4)/RISE);lines.push(a[0],a[1]+.04,a[2],b[0],b[1]+.04,b[2]);}
 if(c.parent>=0){const p=w.cells[c.parent],cx=(c.x+.5)*TILE,cz=(c.z+.5)*TILE,px=(p.x+.5)*TILE,pz=(p.z+.5)*TILE,mx=(cx+px)/2,mz=(cz+pz)/2;paths.push(cx,cellHeight(c,cx,cz)+.12,cz,mx,cellHeight(c,mx,mz)+.12,mz,mx,cellHeight(p,mx,mz)+.12,mz,px,cellHeight(p,px,pz)+.12,pz);}}
 function mesh(p:number[],uv:number[],m:THREE.Material){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.computeVertexNormals();const o=new THREE.Mesh(g,m);o.receiveShadow=true;o.castShadow=true;terrain.add(o);}
 mesh(tp,tu,topMat);mesh(sp,su,cliffMat);
 function wire(p:number[],color:number,group:THREE.Group,opacity:number){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));group.add(new THREE.LineSegments(g,new THREE.LineBasicMaterial({color,transparent:true,opacity})));}wire(lines,0xbed38a,gridGroup,.55);wire(paths,0xffd16b,pathGroup,1);
 const treeCells=w.cells.filter(c=>!c.ramp&&c.parent!==-1&&random(`${w!.settings.seed}/${c.x}/${c.z}/tree-pick`)()<w!.settings.trees);const count=treeCells.length;const trunk=new THREE.InstancedMesh(new THREE.CylinderGeometry(.28,.4,3,5),mat(0x514c32),count);const leaves=new THREE.InstancedMesh(new THREE.ConeGeometry(2.2,5.5,6),mat(0x416640),count*2);const dummy=new THREE.Object3D();treeCells.forEach((c,i)=>{const r=random(`${w!.settings.seed}/${c.x}/${c.z}/tree`);const x=(c.x+.5)*TILE+(r()-.5)*2.6,z=(c.z+.5)*TILE+(r()-.5)*2.6,y=c.h*RISE,s=.7+r()*.55;dummy.position.set(x,y+1.5*s/scale,z);dummy.scale.setScalar(s/scale);dummy.rotation.y=r()*Math.PI;dummy.updateMatrix();trunk.setMatrixAt(i,dummy.matrix);for(let k=0;k<2;k++){dummy.position.y=y+(3.7+k*1.75)*s/scale;dummy.scale.setScalar(s*(1-k*.23)/scale);dummy.updateMatrix();leaves.setMatrixAt(i*2+k,dummy.matrix);leaves.setColorAt(i*2+k,new THREE.Color().setHSL(.25+r()*.075,.3+r()*.1,.22+r()*.1));}});trunk.castShadow=leaves.castShadow=true;leaves.receiveShadow=true;terrain.add(trunk,leaves);
 const rocks=w.cells.filter(c=>!c.ramp&&c.parent!==-1&&random(`${w!.settings.seed}/${c.x}/${c.z}/rock-pick`)()<.13);const stones=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(.9,0),mat(0x8b8d77),rocks.length);rocks.forEach((c,i)=>{const r=random(`${w!.settings.seed}/${c.x}/${c.z}/rock`);dummy.position.set((c.x+.2+r()*.6)*TILE,c.h*RISE+.35/scale,(c.z+.2+r()*.6)*TILE);dummy.scale.set((1+r())/scale,(.5+r()*.4)/scale,(.6+r())/scale);dummy.rotation.set(r(),r()*6,r());dummy.updateMatrix();stones.setMatrixAt(i,dummy.matrix);});stones.castShadow=true;terrain.add(stones);
 // Low boundary rim keeps the playable extent legible without hiding the terrain.
 const rimMat=mat(0x4a5044);for(let i=0;i<4;i++){const wall=new THREE.Mesh(new THREE.BoxGeometry(i<2?span+1:.6,2,i<2?.6:span+1),rimMat);wall.position.set(minX+(i<2?span/2:i===2?-.3:span+.3),-3,minZ+(i<2?(i===0?-.3:span+.3):span/2));terrain.add(wall);}
 const base=new THREE.Mesh(new THREE.PlaneGeometry(span*12,span*12),mat(0x243232));base.rotation.x=-Math.PI/2;base.position.set(minX+span/2,-5,minZ+span/2);base.receiveShadow=true;terrain.add(base);
 sun.position.set((minX-span*.35)*scale,Math.max(130,(w.stats.height*RISE+80)*scale),(minZ+span*.5)*scale);sun.target.position.set((minX+span/2)*scale,0,(minZ+span/2)*scale);Object.assign(sun.shadow.camera,{left:-span*scale,right:span*scale,top:span*scale,bottom:-span*scale,far:100000});sun.shadow.camera.updateProjectionMatrix();
 if(preserve){pos.multiplyScalar(ratio);camera.position.add(pos.clone().sub(oldPos));controls.target.add(pos.clone().sub(oldPos));if(mode==='orbit'&&ratio!==1)resetCamera();}else{const root=w.cells[w.root];pos.set((root.x+.5)*TILE*scale,root.h*RISE*scale,(root.z+.5)*TILE*scale);vy=0;resetCamera();if(mode==='walk')followCamera();}player.position.copy(pos);setOptions(options);onStats?.(w.stats);
 }
 function resetCamera(){if(!w)return;const scale=w.settings.scale??1,span=w.settings.size*TILE*scale,h=w.stats.height*RISE*scale,cx=(w.originX+w.settings.size/2)*TILE*scale,cz=(w.originZ+w.settings.size/2)*TILE*scale;const radius=Math.max(span,h*1.8),aspect=host.clientWidth/Math.max(1,host.clientHeight),factor=Math.max(1,1/aspect);controls.target.set(cx,h*.4,cz);camera.position.set(cx+radius*.85*factor,h*.4+radius*.85*factor,cz+radius*.95*factor);sun.position.set(cx-span*.85,Math.max(130,h+80),cz);sun.target.position.set(cx,0,cz);Object.assign(sun.shadow.camera,{left:-span,right:span,top:span,bottom:-span,far:100000});sun.shadow.camera.updateProjectionMatrix();controls.update();}
 function followCamera(){controls.target.copy(pos).add(new THREE.Vector3(0,1,0));camera.position.copy(pos).add(new THREE.Vector3(0,8,12));controls.update();}
 function setMode(m:'orbit'|'walk'){mode=m;keys.clear();controls.enablePan=m==='orbit';controls.minDistance=m==='walk'?3:5;controls.maxDistance=m==='walk'?28:50000;if(m==='walk')followCamera();else resetCamera();}
 function setOptions(o:typeof options){options=o;pathGroup.visible=o.paths;gridGroup.visible=o.grid;scene.fog=o.fog&&w?new THREE.Fog(0x171b24,w.settings.size*TILE*(w.settings.scale??1)*2,w.settings.size*TILE*(w.settings.scale??1)*4.5):null;}
 function sample(x:number,z:number){if(!w)return null;const scale=w.settings.scale??1,h=heightAt(w,x/scale,z/scale);return h===null?null:h*scale;}
 function setScale(scale:number){if(w&&scale!==(w.settings.scale??1))setWorld({...w,settings:{...w.settings,scale}},true);}
 function setDynamic(dynamic:boolean){if(w)w.settings={...w.settings,dynamic};}
 const valid=new Set(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight']);
 function key(code:string,down:boolean){if(down)keys.add(code);else keys.delete(code);}
 const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,[role=slider],button'))return;if(mode==='walk'&&valid.has(e.code)){e.preventDefault();key(e.code,true);}};const up=(e:KeyboardEvent)=>key(e.code,false);const blur=()=>keys.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
 const resize=()=>{const width=host.clientWidth,height=host.clientHeight;if(!width||!height)return;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function tick(t:number){frame=requestAnimationFrame(tick);const dt=Math.min((t-last)/1000||0,.04);last=t;if(mode==='walk'&&w){offset.copy(camera.position).sub(controls.target);const forward=new THREE.Vector3(-offset.x,0,-offset.z).normalize(),right=new THREE.Vector3(-forward.z,0,forward.x);let f=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),s=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'));const move=forward.multiplyScalar(f).addScaledVector(right,s);if(move.lengthSq()>0)move.normalize().multiplyScalar((keys.has('ShiftLeft')||keys.has('ShiftRight')?13:7)*dt);if(keys.has('Space')&&grounded){vy=9;grounded=false;}
 const old=pos.clone();for(const axis of ['x','z'] as const){const next=pos[axis]+move[axis],x=axis==='x'?next:pos.x,z=axis==='z'?next:pos.z,h=sample(x,z);if(h!==null&&h<=pos.y+.28)pos[axis]=next;}
 const ground=sample(pos.x,pos.z)??0;vy-=24*dt;pos.y+=vy*dt;if(pos.y<=ground){pos.y=ground;vy=0;grounded=true;}else grounded=false;if(move.lengthSq()>.00001)player.rotation.y=Math.atan2(move.x,move.z);player.position.copy(pos);const delta=pos.clone().sub(old);camera.position.add(delta);controls.target.copy(pos).add(new THREE.Vector3(0,1,0));const camGround=sample(camera.position.x,camera.position.z);if(camGround!==null)camera.position.y=Math.max(camera.position.y,camGround+1.5);}
 if(mode==='walk'&&w?.settings.dynamic&&w.settings.size<MAX_SIZE){const tile=TILE*(w.settings.scale??1),x=pos.x/tile-w.originX,z=pos.z/tile-w.originZ;if(Math.min(x,z,w.settings.size-x,w.settings.size-z)<4)setWorld(growWorld(w),true);}
 if(mode==='walk'){sun.position.copy(pos).add(new THREE.Vector3(24,44,16));sun.target.position.copy(pos);Object.assign(sun.shadow.camera,{left:-55,right:55,top:55,bottom:-55,far:180});sun.shadow.camera.updateProjectionMatrix();}
 controls.update();renderer.render(scene,camera);}
 frame=requestAnimationFrame(tick);
 return{getWorld:()=>w,setWorld,setMode,setOptions,setScale,setDynamic,resetCamera,key,dispose(){cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);controls.dispose();disposeGroup(terrain);disposeGroup(pathGroup);disposeGroup(gridGroup);disposeGroup(player);sun.shadow.dispose();renderer.dispose();renderer.domElement.remove();}};
}


