import fs from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

export const slug = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

export function parseWiki(markdown) {
  const chapters = [];
  let chapter, section;
  const lines = markdown.replace(/\r/g, '').split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line || line.startsWith('# ')) continue;
    if (line.startsWith('## ')) {
      const title = line.slice(3);
      chapter = {
        id: slug(title),
        title,
        group: ['Design and source map', 'Maintenance notes'].includes(title)
          ? 'Design reference'
          : 'Play guide',
        intro: '',
        sections: [],
      };
      chapters.push(chapter);
      section = null;
      continue;
    }
    if (!chapter) throw new Error('Wiki content must be inside a chapter');
    if (line.startsWith('### ')) {
      const title = line.slice(4);
      section = { id: slug(title), title, blocks: [] };
      chapter.sections.push(section);
      continue;
    }
    if (!section) {
      chapter.intro += (chapter.intro ? ' ' : '') + line;
      continue;
    }
    if (line.startsWith('|')) {
      const rows = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        rows.push(
          lines[i]
            .trim()
            .slice(1, -1)
            .split('|')
            .map((cell) => cell.trim()),
        );
        i++;
      }
      i--;
      const [headers, separator, ...body] = rows;
      if (
        !separator?.every((cell) => /^:?-+:?$/.test(cell)) ||
        body.some((row) => row.length !== headers.length)
      )
        throw new Error('Invalid wiki table in ' + section.title);
      section.blocks.push({ type: 'table', headers, rows: body });
      continue;
    }
    if (line.startsWith('- ')) {
      const items = [];
      while (i < lines.length && lines[i].trim().startsWith('- ')) {
        items.push(lines[i].trim().slice(2));
        i++;
      }
      i--;
      section.blocks.push({ type: 'list', items });
      continue;
    }
    let text = line;
    while (
      i + 1 < lines.length &&
      lines[i + 1].trim() &&
      !/^(#|- |\|)/.test(lines[i + 1].trim())
    )
      text += ' ' + lines[++i].trim();
    section.blocks.push({ type: 'paragraph', text });
  }
  if (
    !chapters.length ||
    new Set(chapters.map((c) => c.id)).size !== chapters.length
  )
    throw new Error('Missing or duplicate wiki chapters');
  for (const c of chapters)
    if (
      !c.sections.length ||
      new Set(c.sections.map((s) => s.id)).size !== c.sections.length
    )
      throw new Error('Missing or duplicate sections in ' + c.title);
  return chapters;
}

const root = new URL('../', import.meta.url);
export async function buildWiki(check = false) {
  const content = parseWiki(
    await fs.readFile(new URL('docs/GAME-WIKI.md', root), 'utf8'),
  );
  const output =
    '// Generated by scripts/build-wiki.mjs. Edit docs/GAME-WIKI.md.\n' +
    'export type WikiBlock = {type:"paragraph";text:string} | {type:"list";items:string[]} | {type:"table";headers:string[];rows:string[][]};\n' +
    'export type WikiSection = {id:string;title:string;blocks:WikiBlock[]};\n' +
    'export type WikiChapter = {id:string;title:string;group:string;intro:string;sections:WikiSection[]};\n' +
    'export const wikiChapters: WikiChapter[] = ' +
    JSON.stringify(content, null, 2) +
    ';\n';
  const target = new URL('lib/game-wiki.generated.ts', root);
  if (check) {
    if ((await fs.readFile(target, 'utf8')) !== output)
      throw new Error('Wiki bundle is stale. Run npm run build:wiki.');
  } else await fs.writeFile(target, output);
  return content;
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const chapters = await buildWiki(process.argv.includes('--check'));
  console.log(
    `Wiki ready: ${chapters.length} chapters, ${chapters.reduce((n, c) => n + c.sections.length, 0)} sections.`,
  );
}
