const fs=require('fs');let html=fs.readFileSync('game/last-bastion-original.html','utf8');
const source=html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];let code=source;
function rep(a,b){if(!code.includes(a))throw Error('Integration anchor missing: '+a.slice(0,80));code=code.replace(a,b);}
rep('function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}','function mulberry32(a){const rng=function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};rng.getState=()=>a|0;rng.setState=v=>{a=v|0};return rng}');
rep('const WORLD=100, CELL=2, HALF=(WORLD-1)/2, SITE_R=9, WAVES_PER_SITE=5, SITES_TO_WIN=4, MAX_WAVE=WAVES_PER_SITE*SITES_TO_WIN, LSTEP=1.7;','let WORLD=RUN_SETTINGS.size, HALF=(WORLD-1)/2;const CELL=6*RUN_SETTINGS.scale, SITE_R=9, WAVES_PER_SITE=5, SITES_TO_WIN=4, MAX_WAVE=WAVES_PER_SITE*SITES_TO_WIN, LSTEP=3*RUN_SETTINGS.scale;');
rep('renderer.shadowMap.enabled=true;','renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.outputColorSpace=THREE.SRGBColorSpace;');
rep('0x1a1522,.7','0x1a1522,1.1');rep('DirectionalLight(0xffe2b8,.9)','DirectionalLight(0xffe2b8,1.8)');
rep('const s=30;','sun.shadow.normalBias=.035;sun.shadow.bias=-.0001;const s=55;');
rep('far:120','far:180');rep('new THREE.Fog(0x120f18,60,125)','new THREE.Fog(0x120f18,80,Math.max(180,WORLD*CELL*.9))');
rep('G.phase=\'build\';refreshRoutes();',"G.sites.push(site);G.phase='build';refreshRoutes();");
rep("if(!free(cx,cz)){log('Clear ground is needed for a core');return}","if(!free(cx,cz)||cellAt(cx,cz).ramp){log('Clear, flat ground is needed for a core');return}");
rep('if(f>.56&&rng()<.7)', 'if(f>.56&&rng()<Math.min(.8,RUN_SETTINGS.trees*2.5))');
rep('(24+rng()*20)+i*2','(WORLD*.24+rng()*WORLD*.16)+i');rep('pickSpot(8,46)','pickSpot(8,WORLD*.46)');rep('pickSpot(14,46)','pickSpot(14,WORLD*.46)');
code=code.replaceAll('Space starts','Enter starts');
code=code.replaceAll('lvlCol[c.lvl+1]','lvlCol[clamp(c.lvl+1,0,3)]').replaceAll('lc[c.lvl+1]','lc[clamp(c.lvl+1,0,3)]');
rep('if(!G||G.phase===\'over\'||!$(\'draft\').classList.contains(\'hidden\'))return;',"if(menuPaused||!G||G.phase==='over'||!$('draft').classList.contains('hidden'))return;");
code=code.replaceAll("if(!G||G.phase==='over'||!$('draft').classList.contains('hidden'))return;","if(menuPaused||!G||G.phase==='over'||!$('draft').classList.contains('hidden'))return;");
rep('G.time+=dt;', 'if(menuPaused)return;G.time+=dt;');
const visualStart=source.indexOf('  // meshes\n',source.indexOf('function foundSite'));
// Handle the supplied CRLF file without depending on its line endings.
const foundSource=source.slice(source.indexOf('function foundSite'),source.indexOf('function wobble'));
const meshes=foundSource.slice(foundSource.indexOf('// meshes'),foundSource.indexOf("G.phase='build'"));
let restoreVisuals=`function restoreSiteVisuals(site){const [cx,cz]=site.core,r=site.r,id=site.id;G.world.add(site.group);${meshes}}`;
const integration=fs.readFileSync('game/integration.js','utf8')+'\n'+fs.readFileSync('game/walls.js','utf8')+'\n'+fs.readFileSync('game/spatial.js','utf8')+'\n'+fs.readFileSync('game/combat.js','utf8')+'\n'+fs.readFileSync('game/lifecycle.js','utf8')+'\n'+fs.readFileSync('game/rework.js','utf8')+'\n'+fs.readFileSync('game/portals.js','utf8')+'\n'+fs.readFileSync('game/navigation.js','utf8')+'\n'+fs.readFileSync('game/controls.js','utf8')+'\n'+fs.readFileSync('game/settlement.js','utf8')+'\n'+fs.readFileSync('game/frontier-structures.js','utf8')+'\n'+fs.readFileSync('game/frontier-npcs.js','utf8')+'\n'+fs.readFileSync('game/frontier-war.js','utf8')+'\n'+fs.readFileSync('game/frontier-ui.js','utf8');
rep('function buildWorldMeshes(){','function buildWorldMeshes(){G.generatedBodies=[];');
rep('dummy.position.set(p.x+jx,y+.5,p.z+jz);',"G.generatedBodies.push({...bodyCircle(p.x+jx,p.z+jz,y,.24,3.3*s,'tree'),draw:[{mesh:crown,index:i},{mesh:trunk,index:i}]});dummy.position.set(p.x+jx,y+.5,p.z+jz);");
rep('rock.setMatrixAt(i,dummy.matrix)',"rock.setMatrixAt(i,dummy.matrix);G.generatedBodies.push({...bodyCircle(p.x,p.z,G.cells[x][z].lvl*LSTEP,.85*s*1.2,1.7*s,'rock'),draw:[{mesh:rock,index:i}]})");
rep('t.castShadow=true;G.world.add(t);',"t.castShadow=true;G.world.add(t);G.generatedBodies.push(bodyCircle(l.pos.x,l.pos.z,l.pos.y,2.6,3.4,'tent'));");
rep('c.mesh=m}',"c.mesh=m;G.generatedBodies.push(bodyCircle(c.pos.x,c.pos.z,c.pos.y,.62,.9,c))}");
rep('s.mesh=m}',"s.mesh=m;G.generatedBodies.push(bodyCircle(s.pos.x,s.pos.z,s.pos.y,.5,3.2,s))}");
rep('gate.castShadow=true;site.group.add(gate);',"gate.castShadow=true;site.group.add(gate);for(const side of [-1,1]){const post=new THREE.Mesh(new THREE.BoxGeometry(.25,2.8,.45),new THREE.MeshStandardMaterial({color:0x3a3145}));post.position.set(side*2,-1.4,0);post.castShadow=true;gate.add(post);const gp=post.position.clone().applyQuaternion(gate.quaternion).add(gate.position);G.generatedBodies.push({...bodyCircle(gp.x,gp.z,gp.y-1.4,.25,2.8,'gate'),postMesh:post});}");
rep('if(dir.length()>.4&&!(e.aggro', 'dir=roamDirection(e,dir);if(dir.length()>.4&&!(e.aggro');
rep('const gate=new THREE.Mesh(new THREE.BoxGeometry(2.4,3,.6)', 'const gate=new THREE.Mesh(new THREE.BoxGeometry(4.2,.35,.6)');
rep('gate.position.y+=1.5;', 'gate.position.y+=3;');
rep('G.playerMesh.position.copy(P.pos);G.playerMesh.rotation.y=P.yaw;', 'G.playerMesh.position.copy(P.pos);G.playerMesh.rotation.y=P.yaw;');
rep("if(solid(cx,cz)||(cellAt(cx,cz)&&cellAt(cx,cz).type==='core'))", "if(false)");
rep("e.pos.distanceTo(G.site.corePos)<1.4||(e.cell[0]===G.site.core[0]&&e.cell[1]===G.site.core[1])", "e.pos.distanceTo(G.site.corePos)<1.2+e.d.size");
code=code.replaceAll("Math.abs(e.pos.x-t.pos.x)<CELL/2&&Math.abs(e.pos.z-t.pos.z)<CELL/2", "Math.abs(e.pos.y-t.pos.y)<.65&&(b.id==='tar'?Math.hypot(e.pos.x-t.pos.x,e.pos.z-t.pos.z)<.92+e.d.size:Math.abs(e.pos.x-t.pos.x)<(CELL-.2)/2&&Math.abs(e.pos.z-t.pos.z)<(CELL-.2)/2)");
rep('const spd=e.d.spd*(1-Math.min(.75,e.slow));', 'if(updateEnemyPhysics(e,dt))continue;const spd=e.d.spd*(1-Math.min(.75,e.slow));');
rep('const nd=G.dist[key(...e.next)];', 'if(dist<.25)e.next=null;const nd=e.next?G.dist[key(...e.next)]:undefined;');
rep('if(P.dead>0||P.hurtT>0)return;', 'if(P.dead>0||P.hurtT>0||G.admin?.god)return;');
rep("if(/^Digit[1-8]$/.test(e.code)){G.selected=+e.code[5]-1;updateHud()}", "if(/^Digit[1-9]$/.test(e.code)){if(G.buildMode){G.selected=+e.code[5]-1;updateHud()}else castAbility(+e.code[5]-1)}if(e.code==='KeyT')cycleTarget();if(e.code==='KeyZ')setCombatMode(combatMode()==='auto'?'free':'auto');");
rep("addEventListener('keydown',e=>{if(menuPaused||!G", "addEventListener('keydown',e=>{if(e.target?.closest?.('input,select,textarea'))return;if(e.code==='F2'){e.preventDefault();toggleAdmin();return;}if(menuPaused||!G");
rep("    if(e.button===0){keys.MouseL=true;", "    if(!G.buildMode&&combatMode()==='target'){if(e.button===0)selectTarget();else if(e.button===2)castAbility(0);return;}if(!G.buildMode&&combatMode()==='auto')return;\n    if(e.button===0){keys.MouseL=true;");
rep("if(b.id==='arrow'){damage(target,towerDmg(t));", "if(b.id==='gale'){hitEnemy(target,towerDmg(t),t.pos,20);tracer(t.pos.clone().add(V3(0,1.5,0)),target.pos.clone().add(V3(0,target.d.size,0)),0x8ee9ef);}else if(b.id==='arrow'){hitEnemy(target,towerDmg(t),t.pos,1.5);");
rep("else if(b.id==='guard'){damage(target,towerDmg(t));", "else if(b.id==='guard'){hitEnemy(target,towerDmg(t),t.pos,5);");
rep('life:1.2,pierce:', 'life:1.2,knock:10,pierce:');
rep('updateCamera();renderer.render(scene,camera);','previewWall();updateCamera();renderer.render(scene,camera);');
rep("if(e.code==='Space'){e.preventDefault();startWave()}","if(e.code==='Space'){e.preventDefault();jumpPlayer()}if(e.code==='Enter')startWave();if(e.code==='Tab'){e.preventDefault();toggleBuildMode()}");
rep("if(e.code==='KeyF'){","if(e.code==='KeyF'&&G.buildMode){");rep("if(e.code==='KeyX'){","if(e.code==='KeyX'&&G.buildMode){");
rep("else P.pos.y=heightAt(P.pos.x,P.pos.z);",";");
rep("const canFight=G.phase!=='build';","const canFight=!G.buildMode;");
const lockStart=code.indexOf("    if(G.view!=='top'&&document.pointerLockElement!==c&&!G.noLock){");
const lockEnd=code.indexOf("    if(e.button===0)",lockStart);
if(lockStart<0||lockEnd<0)throw Error('Missing lock handler');
code=code.slice(0,lockStart)+"    if(!G.buildMode&&combatMode()==='free'&&G.view!=='top'&&document.pointerLockElement!==c)requestAimLock();\n"+code.slice(lockEnd);
rep("if(G){G.noLock=true;log('Mouse lock is unavailable here. Aim by moving the mouse, turn with Q, E or arrow keys.')}","if(G&&!G.noLock){G.noLock=true;log('Mouse capture unavailable: hold a mouse button and drag to aim. Tab opens building.')}");
rep("if(document.pointerLockElement===c&&G&&G.view!=='top')", "if(G&&!menuPaused&&!G.buildMode&&combatMode()==='free'&&G.view!=='top'&&(document.pointerLockElement===c||keys.MouseL||keys.MouseR))");
rep("else{P.baseYaw+=turn*2.4*dt;P.yaw=P.baseYaw-mouse.x*1.5;P.pitch=clamp(mouse.y*.8,-1.1,1.1)}", "else{P.yaw+=turn*2.4*dt;P.baseYaw=P.yaw;if(keys.ArrowUp)P.pitch=clamp(P.pitch+1.5*dt,-1.1,1.1);if(keys.ArrowDown)P.pitch=clamp(P.pitch-1.5*dt,-1.1,1.1)}");
code=code.replaceAll("if(G.phase==='build'){const ap=aimPoint();","if(G.buildMode&&G.phase==='build'){const ap=aimPoint();");
rep("mouse.x=(e.clientX/innerWidth)*2-1;mouse.y=-(e.clientY/innerHeight)*2+1;","if(e.target.closest?.('button,input,select,#combatBar,#unitFrames,#runToolbar,#missionActions,#adminPanel,#hotbar')){mouseOverHud=true;return;}if(document.pointerLockElement!==c){mouse.x=(e.clientX/innerWidth)*2-1;mouse.y=-(e.clientY/innerHeight)*2+1;}else{mouse.x=0;mouse.y=0;}");
rep("if(ap&&!paused&&G.site&&G.phase!=='explore')","if(ap&&!paused&&G.buildMode&&G.site&&G.phase!=='explore')");

rep('keys[e.code]=true;',"keys[e.code]=true;if(e.repeat)return;");
rep('mx*P.speed*dt,mz*P.speed*dt','mx*P.speed*dt*(keys.ShiftLeft||keys.ShiftRight?1.55:1),mz*P.speed*dt*(keys.ShiftLeft||keys.ShiftRight?1.55:1)');
rep('multiplyScalar(-5.5)','multiplyScalar(-(G.cameraDistance||8))');
rep('p.y+34,p.z+15','p.y+(G.cameraDistance||8)*4.25,p.z+(G.cameraDistance||8)*1.875');
rep('const t={b,cx,cz,cd:0,','const t={b,cx,cz,paid:cost,cd:0,');
rep('Math.round(buildCost(t.b)*.6)','Math.round((t.paid??buildCost(t.b))*.6)');
rep('refund+=buildCost(t.b)','refund+=t.paid??buildCost(t.b)');
rep('renderer.toneMappingExposure=1.15','renderer.toneMappingExposure=1.45');
rep('0x1a1522,1.1','0x252d32,1.65');
rep('new THREE.Color(0x2b2434)','new THREE.Color(0x465343)');
rep('new THREE.Color(0x3b3346)','new THREE.Color(0x53604a)');
rep('new THREE.Color(0x4d4458)','new THREE.Color(0x65705a)');
rep('wallCol=new THREE.Color(0x17131d)','wallCol=new THREE.Color(0x30382e)');
rep('new THREE.Color(0x1f2c27)','new THREE.Color(0x354b35)');
rep("sun.target.position.copy(p);","sun.target.position.copy(p);");
code=code.replace("const f=facing(),r=V3(-f.z,0,f.x);if(keys.KeyW)","const f=cameraForward(),r=V3(-f.z,0,f.x);if(keys.KeyW)");
code=code.replace("const len=Math.hypot(mx,mz);", "if(G.view==='top'){const f=cameraForward(),right=V3(-f.z,0,f.x),dx=mx,dz=mz;mx=right.x*dx-f.x*dz;mz=right.z*dx-f.z*dz;}const len=Math.hypot(mx,mz);");
code=code.replace("for(let x=cx-r;x<=cx+r;x++)for(let z=cz-r;z<=cz+r;z++){const c=G.cells[x][z];c.site=id;", "for(let x=cx-r;x<=cx+r;x++)for(let z=cz-r;z<=cz+r;z++){if(Math.hypot(x-cx,z-cz)>r)continue;const c=G.cells[x][z];c.site=id;");
code=code.replace("(Math.abs(x-cx)===r||Math.abs(z-cz)===r)","Math.hypot(x-cx,z-cz)>=r-1");
code=code.replace("if(keys.MouseL&&canFight&&(G.view!=='top'||!mouseOverHud))meleeAttack();",'').replace('if(keys.MouseR&&canFight)rangedAttack();','');
code=code.replace('[0,1,p11,p01,0,1],[0,-1,p00,p10,3,2]', '[0,1,p11,p01,1,0],[0,-1,p00,p10,2,3]');
code=code.replace("if(ap&&!paused&&G.buildMode&&G.site&&G.phase!=='explore')", "if(ap&&!paused&&G.buildMode)");
code=code.replace('if(!ch.taken&&ch.pos.distanceTo(P.pos)<1.6)', 'if(false)').replace('if(!sh.used&&sh.pos.distanceTo(P.pos)<2.2)', 'if(false)');
html=html.replace(/(<b>Controls<\/b>[\s\S]*?id="helpToggle">hide<\/span>)[\s\S]*?(?=\n  <\/div>)/, '$1<div>W/S move · Space jump · Shift sprint · V view</div><div>First person: mouse look · hold Alt for cursor</div><div>Third person: A/D rotate; RMB + A/D strafe</div><div>Top view: RMB rotates; WASD moves</div><div>1–6/click: select move; repeat or LMB: cast</div><div>RMB a move: toggle automatic use</div><div>Tab: target · Escape: clear target · E: interact</div><div>B: build/combat · 1–9 defenses · 0 portal</div><div>LMB places · E sells · Enter starts a wave</div><div>Menu/Pause pauses; switching tabs does not</div>');
const updatedFound=code.slice(code.indexOf('function foundSite'),code.indexOf('function wobble'));
restoreVisuals=`function restoreSiteVisuals(site){const [cx,cz]=site.core,r=site.r,id=site.id;G.world.add(site.group);${updatedFound.slice(updatedFound.indexOf('// meshes'),updatedFound.indexOf('G.sites.push(site)'))}}`;
rep('initThree();bindInput();buildStart();requestAnimationFrame(frame);',`${restoreVisuals}\n${integration}\ntry{initThree();bindInput();buildStart();installIntegration();requestAnimationFrame(frame);}catch(err){bridge.notify('Game could not start: '+err.message);bridge.menu();}`);
code=code.replaceAll('Mouse lock is unavailable here. Aim by moving the mouse, turn with Q, E or arrow keys.','Mouse capture unavailable: hold a mouse button and drag to aim. Tab opens building.');
code=code.replace('${i+1}</div><div class="n">${b.name}', '${b.core?0:i+1}</div><div class="n">${b.name}');
code=code.replace('for(const s of G.sites){s.coreMesh.rotation.y+=dt*.6;s.coreMesh.position.y=s.corePos.y+1.6+Math.sin(G.time*2+s.id)*.1}', '');
code=code.replaceAll('B founds a bastion.','B opens building. Select 0 to place a portal gate.').replaceAll('0x120f18','0x87999f');
code=code.replaceAll('Bastion secured','Claim secured').replaceAll('Explore. Found the next one with B.','Summon workers in Settlement. Salvage enemy gates to craft your next portal.').replaceAll("'Bastion '+s.id", "'Portal '+s.id").replaceAll('New bastions claim','New portal gates claim').replaceAll('Securing a bastion','Securing a portal claim');
code=code.replace('G.lairs=[];const nL=5;', 'G.lairs=[];const nL=0;').replace('const inSite=!!(c&&c.site===G.site.id);','const inSite=!!c;');
code='const bridge=parent.__lastBastionBridge;const THREE=bridge.THREE;const RUN_SETTINGS=bridge.settings;\n'+code;
html=html.replace(/<link href="https:\/\/fonts.googleapis.com[^>]+>/,'').replace(/<script src="https:\/\/cdnjs[^>]+><\/script>/,'');
html=html.replace(/<script>\s*[\s\S]*?<\/script>/,()=>'<script>'+code+'</script>');
html=html.replace('</style>',fs.readFileSync('game/combat.css','utf8')+'\n'+fs.readFileSync('game/settlement.css','utf8')+'\n'+fs.readFileSync('game/frontier.css','utf8')+'\n</style>');
html=html.replace('</style>',`#runToolbar{position:fixed;top:12px;left:50%;transform:translateX(-50%);z-index:35;display:flex;gap:7px;align-items:center;background:#171821dc;border:1px solid #75694e;padding:7px;border-radius:5px}#runToolbar button{font-size:14px;padding:7px 10px}#saveState{font-size:12px;padding:0 8px;color:#b6b09e}#start .lead{font-size:17px}#start .panel{max-height:90vh;overflow:auto}#hotbar{bottom:16px}#help{bottom:130px}#relics{bottom:130px}@media(max-width:800px){#saveState{display:none}#runToolbar{top:auto;bottom:110px}#hotbar{max-width:96vw;flex-wrap:wrap;justify-content:center}.tl{width:180px}.tr .big{font-size:26px}}\n</style>`);
html=html.replaceAll('Space starts','Enter starts').replaceAll('WASD move, mouse aim, V change view','WASD move · Space jump · Shift sprint · V view').replaceAll('1 to 8 pick a build, F or click to place','Tab toggles building · 1–8 select · F or click places').replaceAll('Q, E or arrows turn without mouse lock','Click to capture aim; hold a mouse button to drag aim if capture is unavailable. Q/E also turn.');
html=html.replaceAll('press Space','press Enter').replaceAll('Space to','Enter to');
html=html.replaceAll('Space starts','Enter starts').replaceAll('WASD move, mouse aim, V change view','WASD move · Space jump · Shift sprint · V view').replaceAll('1 to 8 pick a build, F or click to place','Tab toggles building · 1–8 select · F or click places').replaceAll('Q, E or arrows turn without mouse lock','Click to capture aim; hold a mouse button to drag aim if capture is unavailable. Q/E also turn.');
html=html.replaceAll('press Space','press Enter').replaceAll('Space to','Enter to');
html=html.replace(/<p class="lead">[^<]*<\/p>/, '<p class="lead">Your first settlement awaits: a warded portal, a home, two watchtowers, and four residents. Explore a living wilderness, earn levels, and choose relics. Plan construction for your laborers, train defenders, staff production, and expand through portal gates. Survive five waves to secure each new claim.</p>');
html=html.replace('Four bastions win the run.','Secure portal claims, summon workers, harvest resources, and salvage enemy portals to craft your next expansion.').replace('Bastion core','Portal gate').replace('The bastion fell','The portal fell');
html=html.replace('There are no roads:','Connected chains and ramps form the terrain. There are no roads:');
html=html.replace('</style>',`#hotbar{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));width:min(780px,calc(100% - 24px));max-width:none;gap:5px}#hotbar .slot{width:auto;min-width:0}#missionActions{position:fixed;top:86px;left:50%;transform:translateX(-50%);display:flex;gap:6px;flex-wrap:wrap;justify-content:center;max-width:90%;z-index:12}#missionActions button{font-size:14px;padding:7px 11px;border-radius:4px}#missionHint{flex-basis:100%;text-align:center;color:#d2d8bf;font-size:12px;text-shadow:0 1px 4px #000}#runToolbar{top:12px;bottom:auto}#centerMsg,#cross{pointer-events:none}#start~#missionActions{display:none}body:has(#start.hidden) #missionActions{display:flex}body:has(#start:not(.hidden)) #missionActions{display:none}@media(max-width:800px){#hotbar{grid-template-columns:repeat(4,minmax(0,1fr));bottom:10px}#hotbar .slot{padding:5px 4px}.slot .n{font-size:13px;min-height:24px}.slot .p{font-size:12px}#runToolbar{top:76px;bottom:auto;white-space:nowrap}#missionActions{top:124px;width:94%;max-width:none}#centerMsg{top:29%;font-size:23px;width:90%}#tip{bottom:158px;white-space:normal;width:90%}#log{top:178px;font-size:13px;max-width:70%}#relics{bottom:157px}.tl{left:12px;top:12px;width:160px}.tr{right:12px;top:12px}.tr .wave{font-size:15px}.tr .view{font-size:12px}}\n</style>`);
fs.writeFileSync('lib/bastion-source.ts','// Generated from the supplied prototype and game/integration.js.\nexport const bastionSource='+JSON.stringify(html)+';\n');
fs.writeFileSync('work/bastion-integrated.js',code);
console.log('Integrated Last Bastion mechanics and terrain bridge.');
